/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function arrow_right_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M2.25 12H22.5M15 19.5L22.5 12M22.5 12L15 4.5"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default arrow_right_medium
