/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function arrow_up_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.53 3.22a.75.75 0 00-1.06 0l-7.5 7.5a.75.75 0 101.06 1.06l6.22-6.22v14.69a.75.75 0 001.5 0V5.56l6.22 6.22a.75.75 0 101.06-1.06l-7.5-7.5z"
        fill="#000"
      />
    </svg>
  )
}

export default arrow_up_medium
