/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function arrow_left(props) {
  return (
    <svg width={16} height={16} viewBox="0 0 16 16" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.31066 9L8.03033 12.7197C8.32322 13.0126 8.32322 13.4874 8.03033 13.7803C7.73744 14.0732 7.26256 14.0732 6.96967 13.7803L1.96967 8.78033C1.67678 8.48744 1.67678 8.01256 1.96967 7.71967L6.96967 2.71967C7.26256 2.42678 7.73744 2.42678 8.03033 2.71967C8.32322 3.01256 8.32322 3.48744 8.03033 3.78033L4.31066 7.5L13.5 7.5C13.9142 7.5 14.25 7.83579 14.25 8.25C14.25 8.66421 13.9142 9 13.5 9L4.31066 9Z"
        fill="black"
      />
    </svg>
  )
}

export default arrow_left
