/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function attachment_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M23.25 9.9L12.273 20.878a6.75 6.75 0 01-9.546-9.546l9.016-9.015a4.5 4.5 0 116.363 6.363L9.091 17.7a2.25 2.25 0 01-3.182-3.181L14.925 5.5"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default attachment_medium
