/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function bell(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M6.756 14.067a1.299 1.299 0 002.492 0M8 2.4a4.667 4.667 0 014.667 4.667c0 4.384.933 5.133.933 5.133H2.4s.933-1.192.933-5.133A4.667 4.667 0 018 2.4zm0 0V1"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default bell
