/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function bowling(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M11.306 10.361a.778.778 0 11-1.556 0 .778.778 0 011.556 0zm2.333-.467a.778.778 0 11-1.556 0 .778.778 0 011.556 0zm-1.867-1.866a.778.778 0 11-1.555 0 .778.778 0 011.555 0z"
        fill="#000"
      />
      <path
        d="M5.667 5.667V2.4a1.4 1.4 0 00-2.8 0v3.267m2.8 0a7.14 7.14 0 011.866 4.666 7.105 7.105 0 01-1.56 4.314.933.933 0 01-.732.353H3.292a.935.935 0 01-.73-.353A7.105 7.105 0 011 10.333a7.14 7.14 0 011.867-4.666m2.8 0h-2.8m6.412.119a4.666 4.666 0 110 9.093"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default bowling
