/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const bubble = props => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" {...props}>
    <path
      clipRule="evenodd"
      d="M8.477.75a6.75 6.75 0 0 0-5.91 3.471 6.762 6.762 0 0 0 .168 6.856L.75 15.25l4.169-1.987a6.756 6.756 0 0 0 7.805-.472 6.77 6.77 0 0 0 2.14-7.527A6.761 6.761 0 0 0 8.477.75z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default bubble
