/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg viewBox="0 0 16 16" {...props}>
    <g clipPath="url(#clip0)">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.75 0a.75.75 0 0 1 .75.75v2.125a.75.75 0 1 1-1.5 0V.75A.75.75 0 0 1 4.75 0zM1.656 2.563a.156.156 0 0 0-.156.156v10.876c0 .086.07.156.156.156h12.689c.086 0 .156-.07.156-.156V2.719a.156.156 0 0 0-.156-.156h-.907a.75.75 0 0 1 0-1.5h.907c.914 0 1.656.741 1.656 1.656v10.876c0 .914-.742 1.656-1.656 1.656H1.656A1.656 1.656 0 0 1 0 13.595V2.719c0-.915.742-1.656 1.656-1.656h.907a.75.75 0 0 1 0 1.5h-.907zM3.47 6.5a.75.75 0 0 1 .75-.75h7.563a.75.75 0 0 1 0 1.5H4.22a.75.75 0 0 1-.75-.75zm3.469-5.282a.75.75 0 1 0 0 1.5h2.125a.75.75 0 1 0 0-1.5H6.938zM10.5 2.875a.75.75 0 0 0 1.5 0V.75a.75.75 0 0 0-1.5 0v2.125z"
      />
    </g>
    <defs>
      <clipPath id="clip0">
        <path d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
)

export default SvgComponent
