/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const calendar_medium = props => (
  <svg viewBox="0 0 25 24" fill="none" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.752 0a.75.75 0 0 1 .75.75V3h9V.75a.75.75 0 1 1 1.5 0V3h3.75a2.25 2.25 0 0 1 2.25 2.25v16.5a2.25 2.25 0 0 1-2.25 2.25h-19.5a2.25 2.25 0 0 1-2.25-2.25V5.25A2.25 2.25 0 0 1 2.252 3h3.75V.75a.75.75 0 0 1 .75-.75zm9.75 4.5V6a.75.75 0 1 0 1.5 0V4.5h3.75a.75.75 0 0 1 .75.75V9h-21V5.25a.75.75 0 0 1 .75-.75h3.75V6a.75.75 0 0 0 1.5 0V4.5h9zm-15 6h21v11.25a.75.75 0 0 1-.75.75h-19.5a.75.75 0 0 1-.75-.75V10.5z"
      fill="#000"
    />
  </svg>
)

export default calendar_medium
