/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function camper_trailer(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M6.6 12.1538C6.6 13.1734 5.76427 14 4.73333 14C3.7024 14 2.86667 13.1734 2.86667 12.1538M6.6 12.1538C6.6 11.1342 5.76427 10.3077 4.73333 10.3077C3.7024 10.3077 2.86667 11.1342 2.86667 12.1538M6.6 12.1538H12.2M2.86667 12.1538H1.93333C1.42498 12.1538 1 11.7335 1 11.2308V2.92308C1 2.42031 1.42498 2 1.93333 2H8.46667C10.5001 2 12.2 3.68123 12.2 5.69231V12.1538M12.2 12.1538H15M3.8735 7C3.52986 7 3.25128 6.72448 3.25128 6.38462V4.84615C3.25128 4.50629 3.52986 4.23077 3.8735 4.23077H6.22906C6.5727 4.23077 6.85128 4.50629 6.85128 4.84615V6.38462C6.85128 6.72448 6.5727 7 6.22906 7H3.8735Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default camper_trailer
