/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chain_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M9.423 17.913l-.912.865A4.524 4.524 0 015.4 20a4.524 4.524 0 01-3.111-1.222A4.068 4.068 0 011 15.826c0-1.107.464-2.168 1.289-2.95l4.667-4.429a4.515 4.515 0 012.938-1.222 4.551 4.551 0 013.033.996 4.115 4.115 0 011.513 2.684 4.014 4.014 0 01-.811 2.945m1.126-7.932l.734-.696A4.524 4.524 0 0118.6 4c1.167 0 2.286.44 3.111 1.222A4.068 4.068 0 0123 8.174a4.068 4.068 0 01-1.289 2.95l-4.667 4.428a4.516 4.516 0 01-2.939 1.221 4.551 4.551 0 01-3.031-.996 4.115 4.115 0 01-1.513-2.684 4.014 4.014 0 01.811-2.945"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default chain_medium
