/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chat_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 25 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M6.751 12.75l-3 3v-5.024A5.239 5.239 0 016.001.75h3a5.252 5.252 0 015.033 3.75m9.217 9a5.25 5.25 0 00-5.25-5.25h-3a5.25 5.25 0 100 10.5h.75l4.5 4.5v-5.024a5.238 5.238 0 003-4.726z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default chat_medium
