/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function check_alt_01_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g clipPath="url(#clip-a0b25c)">
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M23.827 1.672a.75.75 0 00-1.152-.96L10.412 15.43a.984.984 0 01-1.557-.058l-3.743-5.24a.75.75 0 10-1.22.872l3.743 5.24a2.484 2.484 0 003.93.146L23.826 1.672zM1.5 12.802a9.214 9.214 0 019.255-9.255c1.454 0 2.894.312 4.112.921a.75.75 0 10.67-1.341c-1.45-.725-3.123-1.08-4.782-1.08A10.714 10.714 0 000 12.802a10.714 10.714 0 0010.755 10.756A10.714 10.714 0 0021.51 12.802c0-.842-.12-1.671-.233-2.346a.75.75 0 10-1.48.246c.11.659.213 1.387.213 2.1a9.214 9.214 0 01-9.256 9.256A9.214 9.214 0 011.5 12.802z"
          fill="#000"
        />
      </g>
    </svg>
  )
}

export default check_alt_01_medium
