/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg viewBox="0 0 16 16" {...props}>
    <path d="M0 0h16v16H0z" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.012 5.298a.75.75 0 1 0-1.024-1.096l-6.97 6.505L3.03 7.72a.75.75 0 0 0-1.06 1.06l3.498 3.498a.748.748 0 0 0 1.046.018l7.498-6.998z"
    />
  </svg>
)

export default SvgComponent
