/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chevron_right(props) {
  return (
    <svg width={16} height={16} viewBox="0 0 16 16" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.28033 2.96967C5.98744 2.67678 5.51256 2.67678 5.21967 2.96967C4.92678 3.26256 4.92678 3.73744 5.21967 4.03033L9.18934 8L5.21967 11.9697C4.92678 12.2626 4.92678 12.7374 5.21967 13.0303C5.51256 13.3232 5.98744 13.3232 6.28033 13.0303L10.7803 8.53033C11.0732 8.23744 11.0732 7.76256 10.7803 7.46967L6.28033 2.96967Z"
        fill="black"
      />
    </svg>
  )
}

export default chevron_right
