/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chevron_left_medium(props) {
  return (
    <svg width={24} height={24} viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M15.9053 5.78033C16.1982 5.48744 16.1982 5.01256 15.9053 4.71967C15.6124 4.42678 15.1376 4.42678 14.8447 4.71967L8.09467 11.4697C7.80178 11.7626 7.80178 12.2374 8.09467 12.5303C8.0949 12.5306 8.09513 12.5308 8.09537 12.531L14.8447 19.2803C15.1376 19.5732 15.6124 19.5732 15.9053 19.2803C16.1982 18.9874 16.1982 18.5126 15.9053 18.2197L9.68566 12L15.9053 5.78033Z"
        fill="black"
      />
    </svg>
  )
}

export default chevron_left_medium
