/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chevron_up(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.53 5.22l4.5 4.5a.75.75 0 11-1.06 1.06L8 6.81l-3.97 3.97a.75.75 0 11-1.06-1.06l4.5-4.5a.748.748 0 011.06 0z"
        fill="#000"
      />
    </svg>
  )
}

export default chevron_up
