/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const chevron_down_medium = props => (
  <svg viewBox="0 0 24 24" fill="none" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5.78 8.095a.75.75 0 0 0-1.06 1.06l6.75 6.75a.75.75 0 0 0 1.061 0l6.75-6.75a.75.75 0 0 0-1.061-1.06L12 14.315l-6.22-6.22z"
      fill="#000"
    />
  </svg>
)

export default chevron_down_medium
