/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const chevron_right_medium = props => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.28 4.72a.75.75 0 00-1.06 1.06L14.44 12l-6.22 6.22a.75.75 0 101.06 1.06l6.75-6.749a.75.75 0 000-1.061L9.28 4.72z"
      fill="#000"
    />
  </svg>
)

export default chevron_right_medium
