/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chevron_right_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.155 4.72a.75.75 0 00-1.06 1.06l6.22 6.22-6.22 6.22a.75.75 0 101.06 1.06l6.75-6.749a.75.75 0 000-1.061l-6.75-6.75z"
        fill="#000"
      />
    </svg>
  )
}

export default chevron_right_medium
