/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg viewBox="0 0 16 16" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.53 5.22l4.5 4.5a.75.75 0 1 1-1.06 1.06L8 6.81l-3.97 3.97a.75.75 0 1 1-1.06-1.06l4.5-4.5a.748.748 0 0 1 1.06 0z"
    />
  </svg>
)

export default SvgComponent
