/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function clock(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M8 5.5V8l2.5 2.5M15 8A7 7 0 111 8a7 7 0 0114 0z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default clock
