/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function coins_3_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M21.75 7.5v3M20.25 9h3M2.25.75v3m-1.5-1.5h3m3.75 16.5H18a.75.75 0 01.75.75v3a.75.75 0 01-.75.75H7.5a.75.75 0 01-.75-.75v-3a.75.75 0 01.75-.75zm1.5-4.5h10.5a.75.75 0 01.75.75v3a.75.75 0 01-.75.75H9a.75.75 0 01-.75-.75v-3a.75.75 0 01.75-.75zm-4.5-4.5H15a.75.75 0 01.75.75v3a.75.75 0 01-.75.75H4.5a.75.75 0 01-.75-.75v-3a.75.75 0 01.75-.75zM6 5.25h10.5a.75.75 0 01.75.75v3a.75.75 0 01-.75.75H6A.75.75 0 015.25 9V6A.75.75 0 016 5.25z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default coins_3_medium
