/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function compose_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 25"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M18.75 14.251v7.5a1.5 1.5 0 01-1.5 1.5h-15a1.5 1.5 0 01-1.5-1.5v-15a1.5 1.5 0 011.5-1.5h7.5m11.78.401l1.061-1.061a2.25 2.25 0 10-3.182-3.182L18.348 2.47m3.182 3.182l-8.485 8.485-3.712.531.53-3.713 8.485-8.485m3.182 3.182L18.348 2.47"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default compose_medium
