/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function contract(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M9.84198 11.248L9.44812 14.509C9.41503 14.6877 9.5022 14.8671 9.66313 14.9515C9.82406 15.0359 10.0212 15.0056 10.1494 14.8767L11.2837 13.7431L12.418 14.8767C12.5463 15.0052 12.7433 15.0353 12.9041 14.951C13.065 14.8667 13.1524 14.6877 13.1198 14.509L12.721 11.2256"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.2667 11.7333C12.5553 11.7333 13.6 10.6886 13.6 9.39997C13.6 8.11131 12.5553 7.06665 11.2667 7.06665C9.97801 7.06665 8.93335 8.11131 8.93335 9.39997C8.93335 10.6886 9.97801 11.7333 11.2667 11.7333Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M7.06679 13.1333H3.33347C2.81801 13.1333 2.40015 12.7154 2.40015 12.1999V1.93333C2.40015 1.41787 2.81801 1 3.33347 1H9.94704C10.1944 1.00005 10.4316 1.0983 10.6066 1.27315L12.3936 3.06017C12.5685 3.23513 12.6667 3.47236 12.6668 3.71972V5"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default contract
