/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function cookie_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M20.799 9.057a3.665 3.665 0 01-3.669-3.69 3.636 3.636 0 01-3.945.314A3.668 3.668 0 0111.554 1 10.997 10.997 0 001.443 8.904a11.009 11.009 0 004.255 12.11 10.997 10.997 0 0016.769-5.633c.708-2.192.71-4.55.009-6.743a3.628 3.628 0 01-1.677.42z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M7.5 13a2.5 2.5 0 100-5 2.5 2.5 0 000 5zm7 6a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M8 17a1 1 0 11-2 0 1 1 0 012 0zm7-7a1 1 0 11-2 0 1 1 0 012 0zm5 3a1 1 0 11-2 0 1 1 0 012 0z"
        fill="#000"
      />
    </svg>
  )
}

export default cookie_medium
