/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function customer_service_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M4.3 9.2C2.7536 9.2 1.5 10.4536 1.5 12V14.8C1.5 16.3464 2.7536 17.6 4.3 17.6H5C5.3866 17.6 5.7 17.2866 5.7 16.9V9.9C5.7 9.5134 5.3866 9.2 5 9.2H4.3ZM4.3 9.2C4.3 4.9474 7.74746 1.5 12 1.5C14.0422 1.5 16.0007 2.31125 17.4448 3.75528C18.8888 5.19931 19.7 7.15783 19.7 9.2M19.7 17.6H19C18.6135 17.6 18.3 17.2866 18.3 16.9V9.9C18.3 9.5134 18.6135 9.2 19 9.2H19.7M19.7 17.6C21.2464 17.6 22.5 16.3464 22.5 14.8V12C22.5 10.4536 21.2464 9.2 19.7 9.2M19.7 17.6V18.3C19.7 19.8464 18.4464 21.1 16.9 21.1H14.8M14.8 21.1C14.8 20.3268 14.1733 19.7 13.4001 19.7H12.0001C11.2269 19.7 10.6001 20.3268 10.6001 21.1C10.6001 21.8732 11.2269 22.5 12.0001 22.5H13.4001C14.1733 22.5 14.8 21.8732 14.8 21.1Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default customer_service_medium
