/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function document_contract_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M5 5h5.5M5 8h8.5M5 19h6.5m1.5 4H2.5a1 1 0 01-1-1V2a1 1 0 011-1h10.036a1 1 0 01.764.354l4.963 5.866a1 1 0 01.237.646m-1.637 9.312l-.591 5.098a.61.61 0 00.322.654c.242.125.537.08.73-.11l1.701-1.675 1.702 1.675a.63.63 0 00.729.11.61.61 0 00.323-.654l-.598-5.131m-2.181.75c1.933 0 3.5-1.544 3.5-3.448S20.933 11 19 11s-3.5 1.543-3.5 3.447c0 1.904 1.567 3.448 3.5 3.448z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default document_contract_medium
