/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function download_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.75 16.19V1.5a.75.75 0 00-1.5 0v14.69L5.03 9.97a.75.75 0 00-1.06 1.06l7.5 7.5a.75.75 0 001.06 0l7.5-7.5a.75.75 0 10-1.06-1.06l-6.22 6.22zM3 22a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 22z"
        fill="#000"
      />
    </svg>
  )
}

export default download_medium
