/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg
    id="Layer_1"
    x="0px"
    y="0px"
    viewBox="0 0 24 24"
    style={{
      enableBackground: 'new 0 0 24 24'
    }}
    xmlSpace="preserve"
    {...props}
  >
    <g>
      <path
        className="st0"
        d="M17.5,19.8H6.5c-0.4,0-0.8-0.3-0.8-0.8s0.3-0.8,0.8-0.8h10.9c0.4,0,0.8,0.3,0.8,0.8S17.9,19.8,17.5,19.8z"
      />
      <path
        className="st0"
        d="M12,17.3c-0.2,0-0.4-0.1-0.5-0.2L6,11.6c-0.3-0.3-0.3-0.8,0-1.1s0.8-0.3,1.1,0l5,5l5-5c0.3-0.3,0.8-0.3,1.1,0\n\t\ts0.3,0.8,0,1.1l-5.5,5.5C12.4,17.2,12.2,17.3,12,17.3z"
      />
      <path
        className="st0"
        d="M12,13.5c-0.4,0-0.7-0.3-0.8-0.7l-0.1-7.8c0-0.4,0.3-0.8,0.7-0.8c0,0,0,0,0,0c0.4,0,0.7,0.3,0.8,0.7l0.1,7.8\n\t\tC12.8,13.1,12.4,13.5,12,13.5C12,13.5,12,13.5,12,13.5z"
      />
    </g>
  </svg>
)

export default SvgComponent
