/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function download_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M8.28 13.47a.75.75 0 00-1.06 1.06l1.06-1.06zM12 18.25l-.53.53a.75.75 0 001.06 0l-.53-.53zm4.78-3.72a.75.75 0 10-1.06-1.06l1.06 1.06zm-4.03-9.78a.75.75 0 00-1.5 0h1.5zM4 22.25a.75.75 0 000 1.5v-1.5zm16 1.5a.75.75 0 000-1.5v1.5zM7.22 14.53l4.25 4.25 1.06-1.06-4.25-4.25-1.06 1.06zm5.31 4.25l4.25-4.25-1.06-1.06-4.25 4.25 1.06 1.06zM11.25 4.75v13.5h1.5V4.75h-1.5zM4 23.75h16v-1.5H4v1.5z"
        fill="#000"
      />
    </svg>
  )
}

export default download_medium
