/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function edit_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M2.52 16.345L.75 23.25l6.905-1.771M2.52 16.345l5.135 5.134M2.52 16.345L16.605 2.26m-8.95 19.219L21.739 7.394m0 0l.415-.415a3.637 3.637 0 00.035-5.169 3.637 3.637 0 00-5.17.035l-.414.415m5.134 5.134L16.605 2.26"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default edit_medium
