/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function email(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M1.25484 3.31332C1.09686 3.49245 1 3.7341 1 4V12C1 12.5523 1.41787 13 1.93333 13H14.0667C14.5821 13 15 12.5523 15 12V4C15 3.73001 14.9001 3.48501 14.7378 3.30509M1.25484 3.31332C1.42499 3.12039 1.66604 3 1.93333 3H14.0667C14.3301 3 14.5681 3.11697 14.7378 3.30509M1.25484 3.31332L7.18332 7.88206C7.42341 8.0674 7.70825 8.16667 8 8.16667C8.29175 8.16667 8.5766 8.0674 8.81668 7.88206L14.7378 3.30509"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default email
