/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const error = props => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" {...props}>
    <path
      d="M12 18a.333.333 0 100 .667.333.333 0 000-.667v0"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M12 15.333V8.666"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
    />
    <path
      clipRule="evenodd"
      d="M13.441 2.898a1.605 1.605 0 00-2.882 0L2.14 20.052A1.352 1.352 0 003.353 22h17.294a1.352 1.352 0 001.215-1.948L13.44 2.898z"
      stroke="#000"
      strokeWidth={1.2}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default error
