/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function exclamation_triangle_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M12 13.818v-5m10.656 8.513a3.203 3.203 0 01-.142 3.14 3.241 3.241 0 01-1.183 1.121 3.274 3.274 0 01-1.584.408H4.253c-.555 0-1.1-.14-1.585-.408a3.24 3.24 0 01-1.183-1.122 3.205 3.205 0 01-.14-3.139L9.09 3.784c.27-.536.686-.987 1.2-1.302a3.272 3.272 0 013.42 0c.514.315.929.766 1.199 1.302l7.747 13.547z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12 16.286a1.285 1.285 0 100 2.57 1.285 1.285 0 000-2.57z"
        fill="#000"
      />
    </svg>
  )
}

export default exclamation_triangle_medium
