/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function exclamation_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.75 3.25a.75.75 0 00-1.5 0v11.868a.75.75 0 001.5 0V3.25zm-1.583 15.503a1.5 1.5 0 111.667 2.495 1.5 1.5 0 01-1.667-2.495z"
        fill="#000"
      />
    </svg>
  )
}

export default exclamation_medium
