/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function exclamation_circled_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M1.5 12C1.5 6.201 6.201 1.5 12 1.5S22.5 6.201 22.5 12 17.799 22.5 12 22.5 1.5 17.799 1.5 12zM12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm.75 6.25a.75.75 0 00-1.5 0v7.25a.75.75 0 001.5 0V6.25zm-1.306 9.919a1 1 0 111.111 1.662 1 1 0 01-1.11-1.662z"
        fill="#000"
      />
    </svg>
  )
}

export default exclamation_circled_medium
