/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function exclamation_medium(props) {
  return (
    <svg width={24} height={24} viewBox="0 0 24 24" fill="none" {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 3C12.4142 3 12.75 3.33579 12.75 3.75V14.25C12.75 14.6642 12.4142 15 12 15C11.5858 15 11.25 14.6642 11.25 14.25V3.75C11.25 3.33579 11.5858 3 12 3ZM10.9259 18.4259C11.2168 18.1351 11.6046 18 12 18C12.3954 18 12.7832 18.1351 13.0741 18.4259C13.3649 18.7168 13.5 19.1046 13.5 19.5C13.5 19.8954 13.3649 20.2832 13.0741 20.5741C12.7832 20.8649 12.3954 21 12 21C11.6046 21 11.2168 20.8649 10.9259 20.5741C10.6351 20.2832 10.5 19.8954 10.5 19.5C10.5 19.1046 10.6351 18.7168 10.9259 18.4259Z"
        fill="black"
      />
    </svg>
  )
}

export default exclamation_medium
