/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function exclamation(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8 1.75a.75.75 0 01.75.75v7a.75.75 0 01-1.5 0v-7A.75.75 0 018 1.75zm-.893 10.357A1.25 1.25 0 018 11.75c.32 0 .646.11.893.357s.357.573.357.893c0 .32-.11.646-.357.893A1.249 1.249 0 018 14.25c-.32 0-.646-.11-.893-.357A1.249 1.249 0 016.75 13c0-.32.11-.646.357-.893z"
        fill="#000"
      />
    </svg>
  )
}

export default exclamation
