/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function file_pdf_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M13 23H2.5C1.94772 23 1.5 22.5523 1.5 22V2C1.5 1.44772 1.94772 1 2.5 1H12.5362C12.8304 1 13.1096 1.12951 13.2996 1.35406L18.2634 7.22036C18.4162 7.40092 18.5 7.62979 18.5 7.86631V9"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M9.29 12H6.5V19H8V16.3H9.29C10.8 16.3 11.68 15.51 11.68 14.15C11.68 12.79 10.8 12 9.29 12ZM9.05 15.1H8V13.2H9.05C9.81 13.2 10.16 13.5 10.16 14.15C10.16 14.8 9.81 15.1 9.05 15.1Z"
        fill="black"
      />
      <path
        d="M14.7316 12H12.6816V19H14.7316C16.9116 19 18.3016 17.61 18.3016 15.5C18.3016 13.39 16.9116 12 14.7316 12ZM14.5916 17.8H14.1816V13.2H14.5916C15.9616 13.2 16.7716 14.1 16.7716 15.5C16.7716 16.9 15.9616 17.8 14.5916 17.8Z"
        fill="black"
      />
      <path
        d="M23.9836 13.2V12H19.6836V19H21.1836V16.11H23.5836V14.91H21.1836V13.2H23.9836Z"
        fill="black"
      />
    </svg>
  )
}

export default file_pdf_medium
