/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function folder(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M15 5.27273C15 4.67023 14.5178 4.18182 13.9231 4.18182H6.92308L5.63077 2.43636V2.43636C5.42739 2.16167 5.1082 2 4.76923 2H2.07692V2C1.48215 2 1 2.48842 1 3.09091V12.9091V12.9091C1 13.5116 1.48215 14 2.07692 14H13.9231V14C14.5178 14 15 13.5116 15 12.9091V5.27273Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default folder
