/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function fullscreen_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g
        clipPath="url(#clip-e3bd68)"
        fillRule="evenodd"
        clipRule="evenodd"
        fill="#000"
      >
        <path d="M9.28 15.78a.75.75 0 10-1.06-1.06L1.5 21.44v-3.19a.75.75 0 00-1.5 0v5a.748.748 0 00.75.75h5a.75.75 0 000-1.5H2.56l6.72-6.72zM23.25 0h-5a.75.75 0 000 1.5h3.19l-6.72 6.72a.75.75 0 001.06 1.06l6.72-6.72v3.19a.75.75 0 001.5 0v-5a.747.747 0 00-.75-.75zM.057.463A.748.748 0 000 .75v5a.75.75 0 001.5 0V2.56l6.72 6.72a.75.75 0 001.06-1.06L2.56 1.5h3.19a.75.75 0 000-1.5h-5a.748.748 0 00-.693.463zM15.78 14.72a.75.75 0 10-1.06 1.06l6.72 6.72h-3.19a.75.75 0 000 1.5h5a.747.747 0 00.75-.75v-5a.75.75 0 00-1.5 0v3.19l-6.72-6.72z" />
      </g>
    </svg>
  )
}

export default fullscreen_medium
