/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg viewBox="0 0 24 24" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M.375 1.125a.75.75 0 0 1 .75-.75H6.09a.75.75 0 0 1 0 1.5H2.935L9 7.939A.75.75 0 1 1 7.94 9L1.874 2.936V6.09a.75.75 0 1 1-1.5 0V1.125zM16.06 9l6.064-6.064v3.155a.75.75 0 0 0 1.5 0V1.126a.75.75 0 0 0-.75-.75H17.91a.75.75 0 0 0 0 1.5h3.154l-6.063 6.063A.75.75 0 0 0 16.06 9zM9 15.001a.75.75 0 0 1 0 1.06l-6.064 6.064h3.155a.75.75 0 0 1 0 1.5H1.126a.75.75 0 0 1-.75-.75V17.91a.75.75 0 0 1 1.5 0v3.154l6.063-6.063a.75.75 0 0 1 1.06 0zm6 0a.75.75 0 0 1 1.061 0l6.064 6.064V17.91a.75.75 0 0 1 1.5 0v4.965a.75.75 0 0 1-.75.75H17.91a.75.75 0 0 1 0-1.5h3.154l-6.063-6.063A.75.75 0 0 1 15 15z"
    />
  </svg>
)

export default SvgComponent
