/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const group_essential_alert_alarm_bell = props => (
  <svg viewBox="0 0 14 16" {...props}>
    <path
      d="M5.417 14.25a1.391 1.391 0 0 0 2.67 0M6.75 2V.75"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      clipRule="evenodd"
      d="M6.75 2a5 5 0 0 1 5 5c0 4.698 1 5.5 1 5.5h-12s1-1.277 1-5.5a5 5 0 0 1 5-5z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default group_essential_alert_alarm_bell
