/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg viewBox="0 0 24 24" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M0 3.188a.75.75 0 0 1 .75-.75h22.5a.75.75 0 0 1 0 1.5H.75a.75.75 0 0 1-.75-.75zm0 9.187a.75.75 0 0 1 .75-.75h22.5a.75.75 0 0 1 0 1.5H.75a.75.75 0 0 1-.75-.75zm.75 8.438a.75.75 0 0 0 0 1.5h22.5a.75.75 0 0 0 0-1.5H.75z"
    />
  </svg>
)

export default SvgComponent
