/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function hamburger(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g clipPath="url(#clip-140d3e)">
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M.75 1.25a.75.75 0 000 1.5h14.5a.75.75 0 000-1.5H.75zM0 8a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H.75A.75.75 0 010 8zm0 6a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H.75A.75.75 0 010 14z"
          fill="#000"
        />
      </g>
    </svg>
  )
}

export default hamburger
