/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const hamburger = props => (
  <svg viewBox="0 0 16 16" fill="none" {...props}>
    <g clipPath="url(#clip1136)">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 1.875a.75.75 0 0 1 .75-.75h14.5a.75.75 0 0 1 0 1.5H.75a.75.75 0 0 1-.75-.75zM0 8a.75.75 0 0 1 .75-.75h14.5a.75.75 0 0 1 0 1.5H.75A.75.75 0 0 1 0 8zm.75 5.375a.75.75 0 0 0 0 1.5h14.5a.75.75 0 0 0 0-1.5H.75z"
        fill="#000"
      />
    </g>
    <defs>
      <clipPath id="clip1136">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
)

export default hamburger
