/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function home_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M8.5 19.464v-5.489a.999.999 0 011-.998h5a1 1 0 011 .998v5.489m-12 2.994h17c1.105 0 2-.894 2-1.996v-10.45c0-.644-.312-1.249-.837-1.623l-8.5-6.06a2.003 2.003 0 00-2.325 0l-8.5 6.06c-.526.374-.838.98-.838 1.624v10.449c0 1.102.895 1.996 2 1.996z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default home_medium
