/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function house_value_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M3.75 14.879v4.75c0 .817.683 1.5 1.5 1.5h13.5c.817 0 1.5-.683 1.5-1.5v-4.75m-19.5-1.5l10.189-10.19a1.5 1.5 0 012.122 0L23.25 13.38m-6-6V5.13h3v5.25"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.646 12.879h-1.209l-1.424 2.007v-2.007H8v5h1.013v-1.522l.21-.278 1.147 1.8h1.276l-1.823-2.593 1.823-2.407zm3.179 5H16l-1.006-2.029c.6-.2.938-.7.938-1.436 0-.971-.594-1.535-1.613-1.535h-1.884v5h1.013V15.95h.506l.871 1.929zm-1.377-4.143h.709c.513 0 .75.214.75.678 0 .465-.237.679-.75.679h-.71v-1.357z"
        fill="#000"
      />
    </svg>
  )
}

export default house_value_medium
