/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function house_2_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M3.75 18v3.75c0 .817.683 1.5 1.5 1.5h3.5a1 1 0 001-1v-3c0-.817.683-1.5 1.5-1.5h1.5c.817 0 1.5.683 1.5 1.5v3a1 1 0 001 1h3.5c.817 0 1.5-.683 1.5-1.5V18M.75 16.5L10.939 6.311a1.5 1.5 0 012.122 0L23.25 16.5M16.5 9.75v-1.5h3.75v5.25M17.122.75l-.407.543a1.045 1.045 0 00.16 1.436 1.045 1.045 0 01.16 1.436l-.407.543M20.872.75l-.407.543a1.045 1.045 0 00.16 1.436 1.045 1.045 0 01.16 1.436l-.407.543"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default house_2_medium
