/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function house_1_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 25 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M3.754 13.923v8.42h6v-6.17a1.5 1.5 0 011.5-1.5h1.5a1.5 1.5 0 011.5 1.5v6.17h6v-8.42m-19.5-1.5l10.19-10.189a1.5 1.5 0 012.121 0l10.189 10.19m-6.75-6.75V3.78h3.75v5.642"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default house_1_medium
