/** This file is auto generated by convertSvgToJsx.js */

import add from './add.js'
import add_medium from './add_medium.js'
import arrow_down from './arrow_down.js'
import arrow_down_medium from './arrow_down_medium.js'
import arrow_left from './arrow_left.js'
import arrow_left_medium from './arrow_left_medium.js'
import arrow_right from './arrow_right.js'
import arrow_right_medium from './arrow_right_medium.js'
import arrow_up from './arrow_up.js'
import arrow_up_medium from './arrow_up_medium.js'
import attachment from './attachment.js'
import attachment_medium from './attachment_medium.js'
import bell from './bell.js'
import bell_medium from './bell_medium.js'
import bubble from './bubble.js'
import bubble_medium from './bubble_medium.js'
import calendar from './calendar.js'
import calendar_medium from './calendar_medium.js'
import check from './check.js'
import check_alt_01 from './check_alt_01.js'
import check_alt_01_medium from './check_alt_01_medium.js'
import check_medium from './check_medium.js'
import chevron_down from './chevron_down.js'
import chevron_down_medium from './chevron_down_medium.js'
import chevron_left from './chevron_left.js'
import chevron_left_medium from './chevron_left_medium.js'
import chevron_right from './chevron_right.js'
import chevron_right_medium from './chevron_right_medium.js'
import chevron_up from './chevron_up.js'
import chevron_up_medium from './chevron_up_medium.js'
import close from './close.js'
import close_medium from './close_medium.js'
import download from './download.js'
import download_medium from './download_medium.js'
import exclamation from './exclamation.js'
import exclamation_medium from './exclamation_medium.js'
import file from './file.js'
import file_add from './file_add.js'
import file_add_medium from './file_add_medium.js'
import file_medium from './file_medium.js'
import fullscreen from './fullscreen.js'
import fullscreen_medium from './fullscreen_medium.js'
import hamburger from './hamburger.js'
import hamburger_medium from './hamburger_medium.js'
import home from './home.js'
import home_medium from './home_medium.js'
import information from './information.js'
import information_medium from './information_medium.js'
import link_out from './link_out.js'
import link_out_medium from './link_out_medium.js'
import list from './list.js'
import list_medium from './list_medium.js'
import logout from './logout.js'
import logout_medium from './logout_medium.js'
import more from './more.js'
import more_medium from './more_medium.js'
import pencil from './pencil.js'
import pencil_medium from './pencil_medium.js'
import print from './print.js'
import print_medium from './print_medium.js'
import question from './question.js'
import question_medium from './question_medium.js'
import redo from './redo.js'
import redo_medium from './redo_medium.js'
import refresh from './refresh.js'
import refresh_medium from './refresh_medium.js'
import reset from './reset.js'
import reset_medium from './reset_medium.js'
import save from './save.js'
import save_medium from './save_medium.js'
import search from './search.js'
import search_medium from './search_medium.js'
import send from './send.js'
import send_medium from './send_medium.js'
import settings from './settings.js'
import settings_medium from './settings_medium.js'
import subtract from './subtract.js'
import subtract_medium from './subtract_medium.js'
import trash from './trash.js'
import trash_medium from './trash_medium.js'
import undo from './undo.js'
import undo_medium from './undo_medium.js'
import upload from './upload.js'
import upload_medium from './upload_medium.js'
import view from './view.js'
import view_medium from './view_medium.js'
import view_off from './view_off.js'
import view_off_medium from './view_off_medium.js'

export {
  add,
  add_medium,
  arrow_down,
  arrow_down_medium,
  arrow_left,
  arrow_left_medium,
  arrow_right,
  arrow_right_medium,
  arrow_up,
  arrow_up_medium,
  attachment,
  attachment_medium,
  bell,
  bell_medium,
  bubble,
  bubble_medium,
  calendar,
  calendar_medium,
  check,
  check_alt_01,
  check_alt_01_medium,
  check_medium,
  chevron_down,
  chevron_down_medium,
  chevron_left,
  chevron_left_medium,
  chevron_right,
  chevron_right_medium,
  chevron_up,
  chevron_up_medium,
  close,
  close_medium,
  download,
  download_medium,
  exclamation,
  exclamation_medium,
  file,
  file_add,
  file_add_medium,
  file_medium,
  fullscreen,
  fullscreen_medium,
  hamburger,
  hamburger_medium,
  home,
  home_medium,
  information,
  information_medium,
  link_out,
  link_out_medium,
  list,
  list_medium,
  logout,
  logout_medium,
  more,
  more_medium,
  pencil,
  pencil_medium,
  print,
  print_medium,
  question,
  question_medium,
  redo,
  redo_medium,
  refresh,
  refresh_medium,
  reset,
  reset_medium,
  save,
  save_medium,
  search,
  search_medium,
  send,
  send_medium,
  settings,
  settings_medium,
  subtract,
  subtract_medium,
  trash,
  trash_medium,
  undo,
  undo_medium,
  upload,
  upload_medium,
  view,
  view_medium,
  view_off,
  view_off_medium
}
