/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function kid_number_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2 2.25A1.75 1.75 0 00.25 4v16c0 .966.784 1.75 1.75 1.75h20A1.75 1.75 0 0023.75 20V4A1.75 1.75 0 0022 2.25H2zM1.75 4A.25.25 0 012 3.75h20a.25.25 0 01.25.25v16a.25.25 0 01-.25.25H2a.25.25 0 01-.25-.25V4zm5.49 7.733L9.67 15H7.969l-1.53-2.268-.279.351V15H4.81V8.7h1.35v2.529L8.059 8.7H9.67l-2.43 3.033zM11.149 15V8.7h1.35V15h-1.35zm6.773-5.904c-.48-.264-1.044-.396-1.692-.396h-1.665V15h1.665c.648 0 1.212-.129 1.692-.387a2.776 2.776 0 001.125-1.107c.264-.474.396-1.026.396-1.656 0-.63-.132-1.182-.396-1.656a2.718 2.718 0 00-1.125-1.098zm-.378 4.266c-.348.372-.828.558-1.44.558h-.189V9.78h.19c.611 0 1.091.186 1.44.558.347.372.521.876.521 1.512s-.174 1.14-.522 1.512z"
        fill="#000"
      />
    </svg>
  )
}

export default kid_number_medium
