/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function launch_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M9.143 4H4v16h16v-5.143m-7.429-3.428L20 4m0 0h-5.714M20 4v5.714"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default launch_medium
