/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function launch(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M5.85714 2H2V14H14V10.1429M8.42857 7.57143L14 2M14 2H9.71429M14 2V6.28571"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default launch
