/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function list_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 25"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3 0a3 3 0 100 6 3 3 0 000-6zM1.5 3a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM3 9a3 3 0 100 6 3 3 0 000-6zm-1.5 3a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM0 21a3 3 0 116 0 3 3 0 01-6 0zm3-1.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3zM8.25 2.252a.75.75 0 000 1.5h15a.75.75 0 000-1.5h-15zm-.75 9.75a.75.75 0 01.75-.75h15a.75.75 0 010 1.5h-15a.75.75 0 01-.75-.75zm.75 8.25a.75.75 0 000 1.5h15a.75.75 0 000-1.5h-15z"
        fill="#000"
      />
    </svg>
  )
}

export default list_medium
