/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function log_in_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M6.933 5.4V3.933A1.467 1.467 0 018.4 2.466h1.4m0 17.6H8.4A1.466 1.466 0 016.933 18.6v-1.466m9.1-4.767a.367.367 0 10-.339-.222.364.364 0 00.34.226m-9.9 1.83l2.933-2.933m0 0H1m8.067 0L6.133 8.334m7.437-7.327l8.8 1.258a.732.732 0 01.63.725v17.104a.733.733 0 01-.58.718l-8.8 2.172a.734.734 0 01-.887-.718V1.733a.731.731 0 01.837-.726z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default log_in_medium
