/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function login(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M4.776 13.134a.933.933 0 00.933.933m0-11.2a.933.933 0 00-.933.933m6.457 3.967a.233.233 0 11-.233.23.232.232 0 01.233-.232M3.633 6.6L5.5 8.466m0 0l-1.867 1.867M5.5 8.466H1m8 6.53l5.6-.8a.466.466 0 00.4-.463V2.85a.466.466 0 00-.369-.457l-5.6-1.382a.467.467 0 00-.564.457v13.067a.467.467 0 00.532.461z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default login
