/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function mastercard_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M10.48 8.943A6.72 6.72 0 009.75 12a6.71 6.71 0 00.702 3M12 6.969a6.75 6.75 0 110 10.062M12 6.97a6.75 6.75 0 100 10.062M12 6.97A6.733 6.733 0 0114.25 12c0 2-.87 3.795-2.25 5.031"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
      />
    </svg>
  )
}

export default mastercard_medium
