/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function move(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M15 6.75H8.833A2.333 2.333 0 006.5 9.083M15 6.75l-1.867-1.867M15 6.75l-1.867 1.867m-1.866-4.934a.933.933 0 00-.934-.933h-8.4A.933.933 0 001 3.683v8.634a.933.933 0 00.933.933h8.4a.933.933 0 00.934-.933V9.75"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default move
