/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function phone_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M10.5 3.75a.75.75 0 000 1.5v-1.5zm3 1.5a.75.75 0 000-1.5v1.5zm-7-3.5h11V.25h-11v1.5zM17.75 2v20h1.5V2h-1.5zm-.25 20.25h-11v1.5h11v-1.5zM6.25 22V2h-1.5v20h1.5zM10.5 5.25h3v-1.5h-3v1.5zm-4 17a.25.25 0 01-.25-.25h-1.5c0 .966.784 1.75 1.75 1.75v-1.5zM17.75 22a.25.25 0 01-.25.25v1.5A1.75 1.75 0 0019.25 22h-1.5zM17.5 1.75a.25.25 0 01.25.25h1.5A1.75 1.75 0 0017.5.25v1.5zM6.5.25A1.75 1.75 0 004.75 2h1.5a.25.25 0 01.25-.25V.25zm6 18.75a.5.5 0 01-.5.5V21a2 2 0 002-2h-1.5zm-.5.5a.5.5 0 01-.5-.5H10a2 2 0 002 2v-1.5zm-.5-.5a.5.5 0 01.5-.5V17a2 2 0 00-2 2h1.5zm.5-.5a.5.5 0 01.5.5H14a2 2 0 00-2-2v1.5z"
        fill="#000"
      />
    </svg>
  )
}

export default phone_medium
