/** This file is auto generated by convertSvgToJsx.js */
import exclamation from './exclamation.js'
import check from './check.js'
import more from './more.js'
import bell from './bell.js'
import search from './search.js'
import question from './question.js'
import calender from './calender.js'
import subtract from './subtract.js'
import add from './add.js'
import save from './save.js'
import close from './close.js'
import chevron_left from './chevron_left.js'
import chevron_right from './chevron_right.js'
import chevron_down from './chevron_down.js'
export default {
  exclamation,
  check,
  more,
  bell,
  search,
  question,
  calender,
  subtract,
  add,
  save,
  close,
  chevron_left,
  chevron_right,
  chevron_down
}
