/** This file is auto generated by convertSvgToJsx.js */

import add from './add.js'
import bell from './bell.js'
import calendar from './calendar.js'
import check from './check.js'
import chevron_down from './chevron_down.js'
import chevron_left from './chevron_left.js'
import chevron_right from './chevron_right.js'
import chevron_up from './chevron_up.js'
import close from './close.js'
import exclamation from './exclamation.js'
import information from './information.js'
import more from './more.js'
import question from './question.js'
import save from './save.js'
import search from './search.js'
import subtract from './subtract.js'

export {
  add,
  bell,
  calendar,
  check,
  chevron_down,
  chevron_left,
  chevron_right,
  chevron_up,
  close,
  exclamation,
  information,
  more,
  question,
  save,
  search,
  subtract
}
