/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function profile_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M3.203 5.23C6.42 8.26 10.78 9.97 15.333 9.99c2.312-.001 4.6-.447 6.723-1.31m-6.928 7.858c-1.866 1.755-4.89 1.755-6.756 0m10.98-12.39c4.197 4.199 4.197 11.005 0 15.203-4.199 4.198-11.005 4.198-15.203 0C-.05 15.153-.05 8.347 4.149 4.15 8.347-.05 15.153-.05 19.35 4.149z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default profile_medium
