/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function progress_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1M15 7.49999L9.00001 16.5M11 9C11 9.82843 10.3284 10.5 9.5 10.5C8.67157 10.5 8 9.82843 8 9C8 8.17157 8.67157 7.5 9.5 7.5C10.3284 7.5 11 8.17157 11 9ZM16 15C16 15.8284 15.3284 16.5 14.5 16.5C13.6716 16.5 13 15.8284 13 15C13 14.1716 13.6716 13.5 14.5 13.5C15.3284 13.5 16 14.1716 16 15Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
      />
    </svg>
  )
}

export default progress_medium
