/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function question_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.153 7.65c0-3.283 2.492-5.775 5.776-5.775s5.775 2.492 5.775 5.776c0 3.283-2.492 5.775-5.775 5.775a.75.75 0 00-.75.75v3.998a.75.75 0 101.5 0v-3.283c3.74-.359 6.525-3.382 6.525-7.24 0-4.112-3.163-7.276-7.275-7.276S4.653 3.539 4.653 7.651a.75.75 0 101.5 0zm5.776 16.347c.987 0 1.645-.658 1.645-1.645s-.658-1.645-1.645-1.645-1.645.658-1.645 1.645.658 1.645 1.645 1.645z"
        fill="#000"
      />
    </svg>
  )
}

export default question_medium
