/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function ref_number_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2 2.25A1.75 1.75 0 00.25 4v16c0 .966.784 1.75 1.75 1.75h20A1.75 1.75 0 0023.75 20V4A1.75 1.75 0 0022 2.25H2zM1.75 4A.25.25 0 012 3.75h20a.25.25 0 01.25.25v16a.25.25 0 01-.25.25H2a.25.25 0 01-.25-.25V4zm5.636 11h1.566l-1.341-2.556c.801-.252 1.251-.882 1.251-1.809 0-1.224-.792-1.935-2.151-1.935H4.2V15h1.35v-2.43h.675L7.386 15zM5.55 9.78h.945c.684 0 .999.27.999.855s-.315.855-.999.855H5.55V9.78zm8.667 0V8.7h-3.87V15h3.87v-1.08h-2.52v-1.521h2.16v-1.08h-2.16V9.78h2.52zm5.559-1.08v1.08h-2.52v1.539h2.16v1.08h-2.16V15h-1.35V8.7h3.87z"
        fill="#000"
      />
    </svg>
  )
}

export default ref_number_medium
