/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function ref_number(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2.25 1.75A1.75 1.75 0 00.5 3.5v9.045c0 .966.784 1.75 1.75 1.75h11.499a1.75 1.75 0 001.75-1.75V3.5a1.75 1.75 0 00-1.75-1.75H2.25zM2 3.5a.25.25 0 01.25-.25h11.499a.25.25 0 01.25.25v9.045a.25.25 0 01-.25.25H2.25a.25.25 0 01-.25-.25V3.5zm3.296 6.774H6.33l-.885-1.686c.528-.166.825-.582.825-1.194 0-.807-.522-1.276-1.42-1.276H3.195v4.156h.89V8.671h.446l.766 1.604zM4.085 6.83h.623c.452 0 .66.178.66.564 0 .386-.208.564-.66.564h-.623V6.83zm5.362 0v-.712H6.894v4.156h2.553v-.712H7.785V8.558H9.21v-.712H7.785V6.83h1.662zm3.312-.712v.712h-1.663v1.016h1.425v.712h-1.425v1.716h-.89V6.119h2.553z"
        fill="#000"
      />
    </svg>
  )
}

export default ref_number
