/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function reply(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M3.28 5.75A7.447 7.447 0 0115 11.872a4.667 4.667 0 00-4.667-4.667A4.613 4.613 0 006.617 9.09l1.987 1.986a.467.467 0 01-.33.797h-6.34A.933.933 0 011 10.939V4.597a.467.467 0 01.796-.33L3.28 5.75z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default reply
