/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function return_1(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M3.8 14.133l-2.8-2.8m0 0l2.8-2.8m-2.8 2.8h9.333a4.667 4.667 0 100-9.333H6.6"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default return_1
