/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const SvgComponent = props => (
  <svg viewBox="0 0 16 16" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M7.25 1v6a.75.75 0 0 0 1.5 0V1a.75.75 0 0 0-1.5 0zm.22 11.53l-5-5a.75.75 0 0 1 1.06-1.06L8 10.94l4.47-4.47a.75.75 0 1 1 1.06 1.06l-5 5a.75.75 0 0 1-1.06 0zM14 14.75a.75.75 0 0 1-.75.75H2.75a.75.75 0 0 1 0-1.5h10.5a.75.75 0 0 1 .75.75z"
    />
  </svg>
)

export default SvgComponent
