/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function search(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 17 17"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g
        clipPath="url(#clip-06a943)"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M9.055 11.937a5.445 5.445 0 10-4.26-10.023 5.445 5.445 0 004.26 10.023zm1.72-1.162L15 14.999" />
      </g>
    </svg>
  )
}

export default search
