/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const search_medium = props => (
  <svg viewBox="0 0 24 24" fill="none" {...props}>
    <g
      clipPath="url(#clip-3b29c8)"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M13.357 18.152a9.063 9.063 0 1 0-7.089-16.68 9.063 9.063 0 0 0 7.09 16.68zM16.22 16.22l7.029 7.029" />
    </g>
    <defs>
      <clipPath id="clip-3b29c8">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </svg>
)

export default search_medium
