/** This file is auto generated by convertSvgToJsx.js */
import hamburger_medium from './hamburger_medium.js'
import fullscreen_medium from './fullscreen_medium.js'
export default { hamburger_medium, fullscreen_medium }
