/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function send(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M7.422 10.323l3.345 4.464a1.068 1.068 0 001.903-.443l2.311-12.307A1.067 1.067 0 0013.366.933L1.502 8.349a1.068 1.068 0 00.566 1.974h5.354zm0 0H5.818v3.32a1.068 1.068 0 001.668.881l2.04-1.39-2.104-2.811zm0 0L14.534.958"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default send
