/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function settings(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        clipRule="evenodd"
        d="M7.062 1.837a1.262 1.262 0 001.875 0l.61-.67a1.263 1.263 0 012.198.911l-.045.903a1.262 1.262 0 001.322 1.324l.902-.045a1.263 1.263 0 01.91 2.198l-.672.606a1.264 1.264 0 000 1.876l.672.606a1.263 1.263 0 01-.911 2.198l-.903-.046a1.262 1.262 0 00-1.326 1.326l.046.903a1.263 1.263 0 01-2.193.909l-.607-.671a1.263 1.263 0 00-1.875 0l-.609.67a1.263 1.263 0 01-2.196-.907l.046-.903A1.262 1.262 0 002.981 11.7l-.903.046a1.262 1.262 0 01-.913-2.197l.671-.606a1.264 1.264 0 000-1.876l-.67-.609a1.262 1.262 0 01.908-2.196l.902.046A1.262 1.262 0 004.303 2.98l-.043-.904a1.263 1.263 0 012.196-.909l.606.67z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        clipRule="evenodd"
        d="M8 10.903a2.901 2.901 0 100-5.802 2.901 2.901 0 000 5.802z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default settings
