/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function share_ios(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M11.4 5.667h.933a.933.933 0 01.934.933v7.467a.933.933 0 01-.934.933h-8.4A.933.933 0 013 14.067V6.6a.933.933 0 01.933-.933h.934M8.133 1v6.533m0-6.533L5.8 3.333M8.133 1l2.334 2.333"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default share_ios
