/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function split_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M20.25 14.998L23.25 17.998M23.25 17.998L20.25 20.998M23.25 17.998L18 18C14.25 18 11.25 12 11.25 12M20.25 2.99805L23.25 5.99805M23.25 5.99805L20.25 8.99805M23.25 5.99805L18 6.00005C14.25 6.00005 11.25 12 11.25 12M11.25 12L0.75 11.998"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default split_medium
