/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function split(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M13.1333 9.86669L15 11.7334M15 11.7334L13.1333 13.6M15 11.7334L11.7333 11.7346C9.4 11.7346 7.53333 8.00127 7.53333 8.00127M13.1333 2.40002L15 4.26669M15 4.26669L13.1333 6.13336M15 4.26669L11.7333 4.26794C9.4 4.26794 7.53333 8.00127 7.53333 8.00127M7.53333 8.00127L1 8.00002"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default split
