/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function star(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M8.452 1.277l2.082 4.125 4.007.397a.501.501 0 01.31.855l-3.297 3.269 1.223 4.441a.506.506 0 01-.716.582l-4.063-2.012-4.056 2.01a.506.506 0 01-.716-.582L4.448 9.92l-3.3-3.268a.5.5 0 01.311-.855L5.466 5.4l2.079-4.123a.51.51 0 01.907 0v0z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default star
