/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function stop_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M19.7782 4.22183C17.7876 2.23122 15.0376 1 12 1C5.92487 1 1 5.92487 1 12C1 15.0376 2.23122 17.7876 4.22183 19.7782M19.7782 4.22183C21.7688 6.21243 23 8.96243 23 12C23 18.0751 18.0751 23 12 23C8.96243 23 6.21243 21.7688 4.22183 19.7782M19.7782 4.22183L4.22183 19.7782"
        stroke="black"
        strokeWidth={1.5}
      />
    </svg>
  )
}

export default stop_medium
