/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const subtract_medium = props => (
  <svg viewBox="0 0 24 24" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 12.375a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75z"
    />
  </svg>
)

export default subtract_medium
