/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function subtract_medium(props) {
  return (
    <svg width={24} height={24} viewBox="0 0 24 24" fill="none" {...props}>
      <line
        x1={20.249}
        y1={12}
        x2={3.74902}
        y2={12}
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
      />
    </svg>
  )
}

export default subtract_medium
