/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function transfer(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M7.045 10.182H15m-2.227 2.227L15 10.182m0 0l-2.227-2.227M8.955 5.727H1m2.227 2.228L1 5.727m0 0L3.227 3.5"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default transfer
