/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const trash = props => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" {...props}>
    <g
      clipPath="url(#clip-306390)"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M1.002 3.25h14" />
      <path
        clipRule="evenodd"
        d="M9.502.75h-3a1 1 0 00-1 1v1.5h5v-1.5a1 1 0 00-1-1z"
      />
      <path d="M6.502 11.75v-5m3 5v-5" />
      <path
        clipRule="evenodd"
        d="M12.58 14.333a1 1 0 01-.998.917H4.423a1 1 0 01-.997-.917L2.502 3.25h11l-.923 11.083z"
      />
    </g>
    <defs>
      <clipPath id="clip-306390">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
)

export default trash
