/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function undo(props) {
  return (
    <svg width={16} height={16} viewBox="0 0 16 16" fill="none" {...props}>
      <path
        d="M1 1.00171V5.66802H5.66631"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M7.99935 15C11.5594 15.0021 14.554 12.3316 14.9578 8.79445C15.3616 5.25733 13.046 1.9806 9.57705 1.18023C6.10809 0.379871 2.59099 2.31089 1.4043 5.66737"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default undo
