/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function undo_medium(props) {
  return (
    <svg width={25} height={25} viewBox="0 0 25 25" fill="none" {...props}>
      <path
        d="M0.781006 0.782913V8.59297H8.59107"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12.496 24.2131C18.4546 24.2166 23.4665 19.7469 24.1424 13.8268C24.8182 7.90668 20.9426 2.42237 15.1366 1.08279C9.33057 -0.256783 3.44396 2.97518 1.45778 8.59296"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default undo_medium
