/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function widget_ios(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M15 7.614a.933.933 0 01-.273.66l-6.454 6.453a.933.933 0 01-1.32 0l-5.68-5.679a.934.934 0 010-1.32l2.06-2.06a2.333 2.333 0 112.334-2.334l2.06-2.06a.933.933 0 011.32 0l1.31 1.313a2.334 2.334 0 103.056 3.057l1.314 1.31a.933.933 0 01.273.66z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default widget_ios
