/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function without_bankid(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3.5.25A2.75 2.75 0 00.75 3v10a2.75 2.75 0 002.75 2.75H8A2.75 2.75 0 0010.75 13v-3a.75.75 0 00-1.5 0v3c0 .69-.56 1.25-1.25 1.25H3.5c-.69 0-1.25-.56-1.25-1.25V3c0-.69.56-1.25 1.25-1.25H8c.69 0 1.25.56 1.25 1.25v.5a.75.75 0 001.5 0V3A2.75 2.75 0 008 .25H3.5zm2.25 12.625a.625.625 0 100-1.25.625.625 0 000 1.25zM6 6.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm2.25.75a.75.75 0 100-1.5.75.75 0 000 1.5zM12 6.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm2.25.75a.75.75 0 100-1.5.75.75 0 000 1.5z"
        fill="#333"
      />
    </svg>
  )
}

export default without_bankid
