/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function without_bankid_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.25.75A2.75 2.75 0 001.5 3.5v17a2.75 2.75 0 002.75 2.75H13a2.75 2.75 0 002.75-2.75V15a.75.75 0 00-1.5 0v5.5c0 .69-.56 1.25-1.25 1.25H4.25c-.69 0-1.25-.56-1.25-1.25v-17c0-.69.56-1.25 1.25-1.25H13c.69 0 1.25.56 1.25 1.25v1.75a.75.75 0 001.5 0V3.5A2.75 2.75 0 0013 .75H4.25zm4.375 18.563a.937.937 0 100-1.875.937.937 0 000 1.875zM9 10.124a1.125 1.125 0 11-2.25 0 1.125 1.125 0 012.25 0zm3.375 1.125a1.125 1.125 0 100-2.25 1.125 1.125 0 000 2.25zM18 10.125a1.125 1.125 0 11-2.25 0 1.125 1.125 0 012.25 0zm3.375 1.125a1.125 1.125 0 100-2.25 1.125 1.125 0 000 2.25z"
        fill="#333"
      />
    </svg>
  )
}

export default without_bankid_medium
