/**
 * Client-side entry point for the Eufemia portal (dev + prod).
 *
 * Used by both the Vite dev server and the production build's client
 * bundle. Sets up React Router, providers, layout, and theme handling.
 */

import React, { Suspense, useCallback, useContext, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import {
  createBrowserRouter,
  RouterProvider,
  Outlet,
  useLocation,
} from 'react-router-dom'
import { CacheProvider } from '@emotion/react'
import createEmotionCache from '@emotion/cache'
import { Provider, Context, Theme } from '@dnb/eufemia/src/shared'
import IsolatedStyleScope from '@dnb/eufemia/src/shared/IsolatedStyleScope'
import { applyPageFocus } from '@dnb/eufemia/src/shared/helpers'
import { scrollToHash } from '@dnb/eufemia/src/components/Anchor'
import { MDXProvider } from '@mdx-js/react'
import { routes } from 'virtual:portal-pages'
import { usePrefetchOnHover } from 'virtual:prefetch-on-hover'
import { useCatchLinks } from 'virtual:catch-links'
import { useScrollPosition } from 'virtual:scroll-position'
import {
  getLang,
  getSkeletonEnabled,
  loadTranslations,
} from '../../src/core/PortalProviders'
import tags from '../../src/shared/tags'
import { useThemeHandler } from 'gatsby-plugin-eufemia-theme-handler'
import { useNavigateSetup } from 'portal-query'
import PortalLayout from '../../src/core/PortalLayout'

// Import all Eufemia theme styles (core + all themes)
// This virtual module is generated by vite-plugin-eufemia-theme
import 'virtual:eufemia-theme-styles'

// When ?data-visual-test is in the URL, set globalThis.IS_TEST and
// mark the document so visual-test CSS overrides and test-specific
// component behaviour are activated — mirrors gatsby-browser.tsx.
if (
  typeof window !== 'undefined' &&
  window.location.href.includes('data-visual-test')
) {
  globalThis.IS_TEST = true
  document.documentElement.setAttribute('data-visual-test', 'true')
}

const emotionCache = createEmotionCache({ key: 'css' })

function RootLayout() {
  const { setTheme, colorScheme, ...theme } = useThemeHandler()

  const translationsLoader = useCallback(async (locale: string) => {
    try {
      return await loadTranslations(locale)
    } catch {
      return null
    }
  }, [])

  return (
    <CacheProvider value={emotionCache}>
      <Provider
        skeleton={getSkeletonEnabled()}
        locale={getLang()}
        translationsLoader={translationsLoader}
      >
        <IsolatedStyleScope
          disableCoreStyleWrapper
          scopeHash="eufemia-scope--portal"
        >
          <SkeletonEnabled>
            <Theme colorScheme={colorScheme || 'auto'} {...theme}>
              <MDXProvider components={tags}>
                <PageWrapper />
              </MDXProvider>
            </Theme>
          </SkeletonEnabled>
        </IsolatedStyleScope>
      </Provider>
    </CacheProvider>
  )
}

/**
 * Enables skeleton mode when ?skeleton is in the URL.
 * Matches Gatsby's SkeletonEnabled wrapper from PortalProviders.
 */
function SkeletonEnabled({ children }: { children: React.ReactNode }) {
  const { skeleton, update } = useContext(Context)

  useEffect(() => {
    if (window.location.search.includes('skeleton') && !skeleton) {
      update({ skeleton: true })
    }
  }, [skeleton, update])

  return <>{children}</>
}

function PageWrapper() {
  const location = useLocation()
  useNavigateSetup()
  useCatchLinks()
  usePrefetchOnHover()
  useScrollPosition()

  // Handle page focus and hash scrolling on route changes
  useEffect(() => {
    applyPageFocus('content')

    if (location.hash) {
      scrollToHash(location.hash)
    }
  }, [location.pathname])

  return (
    <PortalLayout
      location={location as unknown as Location}
      pageContext={{ frontmatter: {} }}
    >
      <Suspense fallback={<div>Loading...</div>}>
        <Outlet />
      </Suspense>
    </PortalLayout>
  )
}

const router = createBrowserRouter([
  {
    path: '/',
    element: <RootLayout />,
    children: routes,
  },
])

// Enforce trailing slashes: redirect /path to /path/
// Equivalent to Gatsby's trailingSlash: 'always'
router.subscribe(({ location }) => {
  const { pathname } = location
  if (
    pathname !== '/' &&
    !pathname.endsWith('/') &&
    !pathname.includes('.')
  ) {
    router.navigate(pathname + '/' + location.search + location.hash, {
      replace: true,
    })
  }
})

const container = document.getElementById('root')

// Pre-resolve the current route's lazy component before mounting React.
// Without this, createRoot replaces the prerendered SSR HTML immediately,
// and the user sees the bare layout shell (sidebar + "Loading...") until
// the route's JS chunk finishes loading. By resolving the lazy import
// first, React can render the full page on its very first paint —
// the prerendered HTML stays visible until then.
async function mountApp() {
  const pathname = window.location.pathname

  for (const route of routes) {
    if (route.lazy && route.path) {
      const routePath = route.path.replace(/\/+$/, '') || '/'
      const currentPath = pathname.replace(/\/+$/, '') || '/'

      if (routePath === currentPath) {
        try {
          const resolved = await route.lazy()
          Object.assign(route, resolved)
          route.lazy = undefined
        } catch {
          // If pre-resolution fails, React Router will handle it
        }
        break
      }
    }
  }

  createRoot(container).render(<RouterProvider router={router} />)
}

mountApp()
