import {
  Suspense,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
} from 'react'
import {
  createBrowserRouter,
  RouterProvider,
  Outlet,
  useLocation,
  type RouteObject,
} from 'react-router-dom'
import { CacheProvider } from '@emotion/react'
import createEmotionCache from '@emotion/cache'
import { Provider, Context, Theme } from '@dnb/eufemia/src/shared'
import IsolatedStyleScope from '@dnb/eufemia/src/shared/IsolatedStyleScope'
import { applyRouteFocus } from './route-focus'
import { MDXProvider } from '@mdx-js/react'
import { usePrefetchOnHover } from 'virtual:prefetch-on-hover'
import { useCatchLinks } from 'virtual:catch-links'
import { useScrollPosition } from 'virtual:scroll-position'
import {
  getLang,
  getSkeletonEnabled,
  loadTranslations,
} from '../../src/core/portalRuntimeUtils'
import tags from '../../src/shared/tags'
import { useThemeHandler } from './shims/theme-handler'
import { useNavigateSetup } from 'portal-query'
import PortalLayout from '../../src/core/PortalLayout'
import { FocusModeCodeProvider } from '../../src/core/FocusModeCodeContext'
import BranchBanner from '../../src/shared/menu/BranchBanner'
import ErrorBoundary from '../../src/core/ErrorBoundary'

// Import all Eufemia theme styles (core + all themes)
// This virtual module is generated by vite-plugin-eufemia-theme
import 'virtual:eufemia-theme-styles'

const emotionCache = createEmotionCache({ key: 'css' })

function RootLayout() {
  const { setTheme, colorScheme, ...theme } = useThemeHandler()

  const translationsLoader = useCallback(async (locale: string) => {
    try {
      return await loadTranslations(locale)
    } catch {
      return null
    }
  }, [])

  return (
    <CacheProvider value={emotionCache}>
      <FocusModeCodeProvider>
        <Provider
          skeleton={getSkeletonEnabled()}
          locale={getLang()}
          translationsLoader={translationsLoader}
        >
          <IsolatedStyleScope
            disableCoreStyleWrapper
            scopeHash="eufemia-scope--portal"
          >
            <SkeletonEnabled>
              <Theme colorScheme={colorScheme || 'auto'} {...theme}>
                <ErrorBoundary>
                  <MDXProvider components={tags}>
                    <PageWrapper />
                  </MDXProvider>
                  <BranchBanner />
                </ErrorBoundary>
              </Theme>
            </SkeletonEnabled>
          </IsolatedStyleScope>
        </Provider>
      </FocusModeCodeProvider>
    </CacheProvider>
  )
}

function SkeletonEnabled({ children }: { children: React.ReactNode }) {
  const { skeleton, update } = useContext(Context)

  useEffect(() => {
    if (window.location.search.includes('skeleton') && !skeleton) {
      update({ skeleton: true })
    }
  }, [skeleton, update])

  return <>{children}</>
}

function PageWrapper() {
  const location = useLocation()
  useNavigateSetup()
  useCatchLinks()
  usePrefetchOnHover()
  useScrollPosition()

  return (
    <PortalLayout
      location={location as unknown as Location}
      pageContext={{ frontmatter: {} }}
    >
      <Suspense fallback={<div>Loading...</div>}>
        <Outlet />
        <RouteFocusEffect />
      </Suspense>
    </PortalLayout>
  )
}

/**
 * Placed inside the Suspense boundary so its effect only fires once the
 * lazy MDX content has rendered and the hash target element exists in
 * the DOM.
 */
function RouteFocusEffect() {
  const location = useLocation()
  const initialRouteRef = useRef<string | null>(null)
  const hasLeftInitialRouteRef = useRef(false)

  if (initialRouteRef.current === null && typeof window !== 'undefined') {
    initialRouteRef.current =
      window.location.pathname +
      window.location.search +
      window.location.hash
  }

  useEffect(() => {
    const hash =
      typeof window !== 'undefined' ? window.location.hash : location.hash
    const currentRoute =
      typeof window !== 'undefined'
        ? window.location.pathname +
          window.location.search +
          window.location.hash
        : location.pathname + location.hash

    if (
      !hasLeftInitialRouteRef.current &&
      currentRoute === initialRouteRef.current
    ) {
      if (hash) {
        applyRouteFocus(hash)
      }
    } else {
      hasLeftInitialRouteRef.current = true
      applyRouteFocus(hash)
    }

    document.documentElement.setAttribute('data-portal-ready', 'true')
  }, [location.hash, location.pathname, location.search])

  return null
}

type PortalAppProps = {
  routes: RouteObject[]
}

function createPortalRouter(routes: RouteObject[]) {
  return createBrowserRouter([
    {
      path: '/',
      element: <RootLayout />,
      children: routes,
    },
  ])
}

export default function PortalApp({ routes }: PortalAppProps) {
  const router = useMemo(() => createPortalRouter(routes), [routes])

  return <RouterProvider router={router} />
}
