import {
  Suspense,
  useCallback,
  useContext,
  useEffect,
  useMemo,
} from 'react'
import {
  createBrowserRouter,
  RouterProvider,
  Outlet,
  useLocation,
  type RouteObject,
} from 'react-router-dom'
import { CacheProvider } from '@emotion/react'
import createEmotionCache from '@emotion/cache'
import { Provider, Context, Theme } from '@dnb/eufemia/src/shared'
import IsolatedStyleScope from '@dnb/eufemia/src/shared/IsolatedStyleScope'
import { applyPageFocus } from '@dnb/eufemia/src/shared/helpers'
import { scrollToHash } from '@dnb/eufemia/src/components/Anchor'
import { MDXProvider } from '@mdx-js/react'
import { usePrefetchOnHover } from 'virtual:prefetch-on-hover'
import { useCatchLinks } from 'virtual:catch-links'
import { useScrollPosition } from 'virtual:scroll-position'
import {
  getLang,
  getSkeletonEnabled,
  loadTranslations,
} from '../../src/core/portalRuntimeUtils'
import tags from '../../src/shared/tags'
import { useThemeHandler } from './shims/theme-handler'
import { useNavigateSetup } from 'portal-query'
import PortalLayout from '../../src/core/PortalLayout'

// Import all Eufemia theme styles (core + all themes)
// This virtual module is generated by vite-plugin-eufemia-theme
import 'virtual:eufemia-theme-styles'

const emotionCache = createEmotionCache({ key: 'css' })

function RootLayout() {
  const { setTheme, colorScheme, ...theme } = useThemeHandler()

  const translationsLoader = useCallback(async (locale: string) => {
    try {
      return await loadTranslations(locale)
    } catch {
      return null
    }
  }, [])

  return (
    <CacheProvider value={emotionCache}>
      <Provider
        skeleton={getSkeletonEnabled()}
        locale={getLang()}
        translationsLoader={translationsLoader}
      >
        <IsolatedStyleScope
          disableCoreStyleWrapper
          scopeHash="eufemia-scope--portal"
        >
          <SkeletonEnabled>
            <Theme colorScheme={colorScheme || 'auto'} {...theme}>
              <MDXProvider components={tags}>
                <PageWrapper />
              </MDXProvider>
            </Theme>
          </SkeletonEnabled>
        </IsolatedStyleScope>
      </Provider>
    </CacheProvider>
  )
}

function SkeletonEnabled({ children }: { children: React.ReactNode }) {
  const { skeleton, update } = useContext(Context)

  useEffect(() => {
    if (window.location.search.includes('skeleton') && !skeleton) {
      update({ skeleton: true })
    }
  }, [skeleton, update])

  return <>{children}</>
}

function PageWrapper() {
  const location = useLocation()
  useNavigateSetup()
  useCatchLinks()
  usePrefetchOnHover()
  useScrollPosition()

  useEffect(() => {
    applyPageFocus('content')

    if (location.hash) {
      scrollToHash(location.hash)
    }

    document.documentElement.setAttribute('data-portal-ready', 'true')
  }, [location.hash, location.pathname])

  return (
    <PortalLayout
      location={location as unknown as Location}
      pageContext={{ frontmatter: {} }}
    >
      <Suspense fallback={<div>Loading...</div>}>
        <Outlet />
      </Suspense>
    </PortalLayout>
  )
}

type PortalAppProps = {
  routes: RouteObject[]
}

function createPortalRouter(routes: RouteObject[]) {
  return createBrowserRouter([
    {
      path: '/',
      element: <RootLayout />,
      children: routes,
    },
  ])
}

export default function PortalApp({ routes }: PortalAppProps) {
  const router = useMemo(() => createPortalRouter(routes), [routes])

  return <RouterProvider router={router} />
}
