/**
 * Scripts test
 *
 */

import path from 'path'
import * as globby from 'globby'
import * as fs from 'fs-extra'
import { runFactory } from '../themeFactory'

vi.mock('globby', async () => {
  return {
    ...(await vi.importActual<typeof import('globby')>('globby')),
    default: vi.fn(),
  }
})
vi.mock('fs-extra', async () => {
  const orig = await vi.importActual<typeof import('fs-extra')>('fs-extra')
  const actualFs = ('default' in orig ? orig.default : orig) as typeof fs
  const mockedFs = {
    ...actualFs,
    readFile: vi.fn(async (source, encoding) => {
      if (source.endsWith('theme-components.scss')) {
        const { editAdvice, insertBelowAdvice } =
          await vi.importActual<typeof import('../themeFactory')>(
            '../themeFactory'
          )
        return `${editAdvice.replace(
          '<file>',
          'components'
        )}${insertBelowAdvice}`
      }

      return await orig.readFile(source, encoding)
    }),
    writeFile: vi.fn(),
    mkdir: vi.fn(),
    existsSync: vi.fn((file) => actualFs.existsSync(file)),
  }

  return {
    ...orig,
    ...mockedFs,
    default: mockedFs,
  }
})

describe('runFactory', () => {
  it('has to find all related "ui" theme files', async () => {
    vi.spyOn(globby, 'default').mockResolvedValue([
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/badge/style/themes/dnb-badge-theme-ui.scss',
    ])

    const result = await getThemeContent({ name: 'ui' })
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @use '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @use './src/components/badge/style/themes/dnb-badge-theme-ui.scss';
      @use './src/components/button/style/themes/dnb-button-theme-ui.scss';
      "
    `)
  })

  it('has to find all related "ui" and "sbanken" theme files', async () => {
    vi.spyOn(globby, 'default').mockResolvedValue([
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/badge/style/themes/dnb-badge-theme-sbanken.scss',
    ])

    const result = await getThemeContent({ name: 'sbanken' })
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @use '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @use './src/components/badge/style/themes/dnb-badge-theme-sbanken.scss';
      @use './src/components/button/style/themes/dnb-button-theme-ui.scss';
      "
    `)
  })

  it('has to fallback replacement', async () => {
    vi.spyOn(globby, 'default').mockResolvedValue([
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/button/style/themes/dnb-button-theme-sbanken.scss',
      './src/components/badge/style/themes/dnb-badge-theme-ui.scss',
    ])

    const result = await getThemeContent({ name: 'sbanken' })
    expect(fs.mkdir).toHaveBeenCalledTimes(0)
    expect(fs.writeFile).toHaveBeenCalledTimes(0)
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @use '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @use './src/components/button/style/themes/dnb-button-theme-sbanken.scss';
      @use './src/components/badge/style/themes/dnb-badge-theme-ui.scss';
      "
    `)
  })

  it('has to write new theme file if it not exists', async () => {
    vi.spyOn(globby, 'default').mockResolvedValueOnce([
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/button/style/themes/dnb-button-theme-sbanken.scss',
      './src/components/new-file/style/themes/dnb-new-file-theme-ui.scss',
    ])
    vi.spyOn(globby, 'default').mockResolvedValueOnce([
      './src/style/themes/ui/ui-theme-components.scss',
      './src/style/themes/sbanken/sbanken-theme-components.scss',
    ])
    vi.mocked(fs.existsSync).mockImplementation((file) => {
      return ![
        './sbanken',
        './ui',
        './sbanken/sbanken-theme-components.scss',
        './ui/ui-theme-components.scss',
      ].includes(String(file))
    })

    const result = await getThemeContent({
      name: 'sbanken',
      scssOutputPath: '.',
    })
    expect(fs.mkdir).toHaveBeenCalledTimes(2)
    expect(fs.writeFile).toHaveBeenCalledTimes(2)
    expect(fs.mkdir).toHaveBeenNthCalledWith(1, './sbanken')
    expect(fs.mkdir).toHaveBeenNthCalledWith(2, './ui')
    expect(fs.writeFile).toHaveBeenNthCalledWith(
      1,
      './sbanken/sbanken-theme-components.scss',
      expect.any(String)
    )
    expect(fs.writeFile).toHaveBeenNthCalledWith(
      2,
      './ui/ui-theme-components.scss',
      expect.any(String)
    )
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @use '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @use './src/components/button/style/themes/dnb-button-theme-sbanken.scss';
      @use './src/components/new-file/style/themes/dnb-new-file-theme-ui.scss';
      "
    `)
  })
})

type FactoryResult = Record<string, string>

const make = async ({ scssOutputPath, targetFile }) => {
  return (await runFactory({
    targetFile,
    scssOutputPath,
    filesToFindGlob: [
      path.resolve(
        __dirname,
        '../../../../src/{components,fragments}/**/style/themes/**/*-theme-*.scss'
      ),
    ],
    returnResult: true,
  })) as FactoryResult
}

const getThemeContent = async ({
  name,
  targetFile = 'components',
  scssOutputPath = path.resolve(__dirname, '../../../../src/style/themes'),
  factoryResult = null,
}) => {
  if (!factoryResult) {
    factoryResult = await make({ scssOutputPath, targetFile })
  }
  return Object.entries(factoryResult).find(([file]) => {
    return file.includes(name)
  })[1][0]
}
