/**
 * Scripts test
 *
 */

import path from 'path'
import * as fsPromises from 'node:fs/promises'
import * as fs from 'fs-extra'
import { runFactory } from '../themeFactory'

jest.mock('node:fs/promises', () => {
  const mockGlob = jest.fn()
  return {
    ...jest.requireActual('node:fs/promises'),
    glob: mockGlob,
  }
})

jest.mock('fs-extra', () => {
  const orig = jest.requireActual('fs-extra')
  const mockFileStore = new Map<string, string>()
  
  return {
    ...orig,
    existsSync: jest.fn(() => false), // Pretend files don't exist so they get created
    readFile: jest.fn(async (source, encoding) => {
      // Check if it was "written" to our mock store
      if (mockFileStore.has(source)) {
        return mockFileStore.get(source)
      }
      
      if (source.endsWith('theme-components.scss')) {
        const { editAdvice, insertBelowAdvice } =
          jest.requireActual('../themeFactory')
        return `${editAdvice.replace(
          '<file>',
          'components'
        )}${insertBelowAdvice}`
      }

      return await orig.readFile(source, encoding)
    }),
    writeFile: jest.fn(async (filePath, content) => {
      // Store the written content so readFile can return it
      mockFileStore.set(filePath, content)
    }),
    mkdir: jest.fn(),
  }
})

describe('runFactory', () => {
  // Get the mocked glob function
  const mockGlob = (fsPromises as any).glob as jest.Mock

  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('has to find all related "ui" theme files', async () => {
    const mockFiles = [
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/badge/style/themes/dnb-badge-theme-ui.scss',
    ]
    // Mock glob to return a new generator each time it's called
    mockGlob.mockImplementation(() => {
      return (async function* () {
        for (const file of mockFiles) {
          yield file
        }
      })()
    })

    const result = await getThemeContent({ name: 'ui' })
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @import '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @import './src/components/badge/style/themes/dnb-badge-theme-ui.scss';
      @import './src/components/button/style/themes/dnb-button-theme-ui.scss';
      "
    `)
  })

  it('has to find all related "ui" and "sbanken" theme files', async () => {
    const mockFiles = [
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/badge/style/themes/dnb-badge-theme-sbanken.scss',
    ]
    mockGlob.mockImplementation(() => {
      return (async function* () {
        for (const file of mockFiles) {
          yield file
        }
      })()
    })

    const result = await getThemeContent({ name: 'sbanken' })
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @import '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @import './src/components/badge/style/themes/dnb-badge-theme-sbanken.scss';
      @import './src/components/button/style/themes/dnb-button-theme-ui.scss';
      "
    `)
  })

  it('has to fallback replacement', async () => {
    const mockFiles = [
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/button/style/themes/dnb-button-theme-sbanken.scss',
      './src/components/badge/style/themes/dnb-badge-theme-ui.scss',
    ]
    mockGlob.mockImplementation(() => {
      return (async function* () {
        for (const file of mockFiles) {
          yield file
        }
      })()
    })

    const result = await getThemeContent({ name: 'sbanken' })
    expect(fs.mkdir).toHaveBeenCalledTimes(0)
    expect(fs.writeFile).toHaveBeenCalledTimes(0)
    expect(result).toMatchInlineSnapshot(`
      "
      /**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @import '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      @import './src/components/button/style/themes/dnb-button-theme-sbanken.scss';
      @import './src/components/badge/style/themes/dnb-badge-theme-ui.scss';
      "
    `)
  })

  it('has to write new theme file if it not exists', async () => {
    const mockFiles1 = [
      './src/components/button/style/themes/dnb-button-theme-ui.scss',
      './src/components/button/style/themes/dnb-button-theme-sbanken.scss',
      './src/components/new-file/style/themes/dnb-new-file-theme-ui.scss',
    ]
    const mockFiles2 = [
      './src/style/themes/theme-ui/ui-theme-components.scss',
      './src/style/themes/theme-sbanken/sbanken-theme-components.scss',
    ]

    let callCount = 0
    mockGlob.mockImplementation(() => {
      const files = callCount === 0 ? mockFiles1 : mockFiles2
      callCount++
      return (async function* () {
        for (const file of files) {
          yield file
        }
      })()
    })

    const result = await getThemeContent({
      name: 'sbanken',
      scssOutputPath: '.',
    })
    expect(fs.mkdir).toHaveBeenCalledTimes(2)
    expect(fs.writeFile).toHaveBeenCalledTimes(2)
    // Note: The order may be ui first then sbanken due to theme processing order
    expect(fs.mkdir).toHaveBeenCalledWith('./theme-sbanken')
    expect(fs.mkdir).toHaveBeenCalledWith('./theme-ui')
    expect(fs.writeFile).toHaveBeenCalledWith(
      './theme-sbanken/sbanken-theme-components.scss',
      expect.any(String)
    )
    expect(fs.writeFile).toHaveBeenCalledWith(
      './theme-ui/ui-theme-components.scss',
      expect.any(String)
    )
    expect(result).toMatchInlineSnapshot(`
      "/**
       * ATTENTION: This file is auto generated by using "themeFactory".
       * But you still can change the content of this file on the very top.
       */

      // Add "ui" themes, if file don't exists
      $THEME_FALLBACK: 'ui';

      // Import shared styles
      @import '../../dnb-ui-components.scss';

      /**
       * NB: The content below is auto generated by the "themeFactory".
       * You may want to update it by running "yarn build" locally.
       */


      "
    `)
  })
})

type FactoryResult = Record<string, string>

const make = async ({ scssOutputPath, targetFile }) => {
  return (await runFactory({
    targetFile,
    scssOutputPath,
    filesToFindGlob: [
      path.resolve(
        __dirname,
        '../../../../src/{components,fragments}/**/style/themes/**/*-theme-*.scss'
      ),
    ],
    returnResult: true,
  })) as FactoryResult
}

const getThemeContent = async ({
  name,
  targetFile = 'components',
  scssOutputPath = path.resolve(__dirname, '../../../../src/style/themes'),
  factoryResult = null,
}) => {
  if (!factoryResult) {
    factoryResult = await make({ scssOutputPath, targetFile })
  }
  const result = Object.entries(factoryResult).find(([file]) => {
    return file.includes(name)
  })
  if (!result) {
    throw new Error(
      `No theme found for name: ${name}. Available: ${Object.keys(
        factoryResult
      ).join(', ')}`
    )
  }
  return result[1][0]
}
