# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
root:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

eufemia:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/packages/dnb-eufemia" # Location of package manifests
    schedule:
      interval: "monthly"

portal:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/packages/dnb-design-system-portal" # Location of package manifests
    schedule:
      interval: "monthly"
