kind: pipeline
name: default

trigger:
  event:
    - push
    - pull-request

steps:
  # - name: setup
  #   image: tujoworker/docker-node-puppeteer:next
  #   commands:
  #     - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  #     - export PATH="$HOME/.yarn/bin:$PATH"

  - name: install dependencies
    image: tujoworker/docker-node-puppeteer:next
    commands:
      - CYPRESS_INSTALL_BINARY=0 yarn install

  - name: dependencies audit
    image: tujoworker/docker-node-puppeteer:next
    commands:
      - yarn audit-ci
    when:
      branch:
        exclude:
          - fix/*
          - ftr/*
          - rc/*

  - name: run integration tests
    image: tujoworker/docker-node-puppeteer:next
    commands:
      - yarn lint-ci
      - yarn test-ci

  - name: prebuild
    image: tujoworker/docker-node-puppeteer:next
    environment:
      FIGMA_MAIN_FILE:
        from_secret: FIGMA_MAIN_FILE
      FIGMA_TOKEN:
        from_secret: FIGMA_TOKEN
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - yarn prebuild-ci
    when:
      branch:
        include:
          - release
          - portal
          - beta
          - alpha
          - next
          - develop
          - ftr/*
          - fix/*
          - rc/*

  - name: make build of portal
    image: tujoworker/docker-node-puppeteer:next
    environment:
      FIGMA_MAIN_FILE:
        from_secret: FIGMA_MAIN_FILE
      FIGMA_TOKEN:
        from_secret: FIGMA_TOKEN
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
      ALGOLIA_APP_ID:
        from_secret: ALGOLIA_APP_ID
      ALGOLIA_INDEX_NAME:
        from_secret: ALGOLIA_INDEX_NAME
      ALGOLIA_SEARCH_KEY:
        from_secret: ALGOLIA_SEARCH_KEY
      ALGOLIA_API_KEY:
        from_secret: ALGOLIA_API_KEY
    commands:
      - yarn build-portal-ci
    when:
      branch:
        include:
          - release
          - portal
          - beta
          - alpha
          - next
          - develop
          - ftr/*
          - fix/*
          - rc/*

  - name: run screenshot tests
    image: tujoworker/docker-node-puppeteer:next
    environment:
      FIGMA_MAIN_FILE:
        from_secret: FIGMA_MAIN_FILE
      FIGMA_TOKEN:
        from_secret: FIGMA_TOKEN
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - yarn test-ci-screenshots
    when:
      branch:
        include:
          - release
          - portal
          - beta
          - alpha
          - next
          - develop
          - ftr/*
          - fix/*
          - rc/*

  - name: deploy portal
    image: tujoworker/docker-node-puppeteer:next
    environment:
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      ALGOLIA_APP_ID:
        from_secret: ALGOLIA_APP_ID
      ALGOLIA_INDEX_NAME:
        from_secret: ALGOLIA_INDEX_NAME
      ALGOLIA_SEARCH_KEY:
        from_secret: ALGOLIA_SEARCH_KEY
      ALGOLIA_API_KEY:
        from_secret: ALGOLIA_API_KEY
    commands:
      - yarn deploy-ci
    when:
      event:
        - push
      branch:
        include:
          - release
          - portal

  - name: publish release
    image: tujoworker/docker-node-puppeteer:next
    environment:
      GH_EMAIL:
        from_secret: GH_EMAIL
      GH_NAME:
        from_secret: GH_NAME
      GH_TOKEN:
        from_secret: GH_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - yarn publish-ci
    when:
      event:
        - push
      branch:
        include:
          - release
          - beta
          - alpha
          - next

  # - name: test release
  #   image: cypress/browsers:node10.16.0-chrome77
  #   commands:
  #     - yarn test-ci-release
  #   when:
  #     event:
  #       - push
  #     branch:
  #       include:
  #         - ftr/*
  #         # - portal
  #         # - release

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_TUJO
      channel: eufemia
      link_names: true
      template: >
        {{#success build.status}}
          <@tujoworker> success on *{{build.branch}}* <{{build.link}}> by {{build.author}}
        {{else}}
          <@tujoworker> failure on *{{build.branch}}* <{{build.link}}> by {{build.author}}
        {{/success}}
      username: DroneCI
    when:
      status: [success, failure]
