compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  jest-playwright-preset@*:
    peerDependenciesMeta:
      jest-circus:
        optional: true
      jest-environment-node:
        optional: true
      jest-runner:
        optional: true
  css-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  sass-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  style-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  raw-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  gatsby-plugin-gatsby-cloud@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  webpack-assets-manifest@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  prism-react-renderer@*:
    peerDependenciesMeta:
      react:
        optional: true

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.6.0.cjs
