defaultSemverRangePrefix: ""

enableGlobalCache: false

packageExtensions:
  "@dnb/eufemia@*":
    dependencies:
      "@emotion/react": "*"
  date-fns@*:
    dependencies:
      eslint-import-resolver-node: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eufemia@*:
    dependencies:
      "@emotion/react": "*"
      "@mdx-js/react": "*"
  figma-js@*:
    dependencies:
      eslint-import-resolver-node: "*"
  jest-screenshot@*:
    dependencies:
      rimraf: "*"
  jest-tobetype@*:
    dependencies:
      eslint-import-resolver-node: "*"
  stylelint@*:
    dependencies:
      postcss-scss: "*"
  gatsby@*:
    dependencies:
      history: "*"
      process: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
