compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.16.0.cjs
