defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

pnpMode: loose

packageExtensions:
  "@dnb/eufemia@*":
    dependencies:
      "@emotion/react": "*"
  date-fns@*:
    dependencies:
      eslint-import-resolver-node: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eufemia@*:
    dependencies:
      "@emotion/react": "*"
      "@mdx-js/react": "*"
  figma-js@*:
    dependencies:
      eslint-import-resolver-node: "*"
  jest-screenshot@*:
    dependencies:
      rimraf: "*"
  jest-tobetype@*:
    dependencies:
      eslint-import-resolver-node: "*"
  stylelint@*:
    dependencies:
      postcss-scss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/plugin-ignore-install-options.cjs
    spec: .yarn/unplugged/yarn-plugin-ignore-install-options-npm-1.0.2-e13e094f36/node_modules/yarn-plugin-ignore-install-options/ignore-install-options-1.0.2.js

yarnPath: .yarn/releases/yarn-3.1.0.cjs
