defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/plugin-ignore-install-options.cjs
    spec: packages/dnb-design-system-portal/node_modules/yarn-plugin-ignore-install-options/ignore-install-options-1.0.2.js

yarnPath: .yarn/releases/yarn-3.1.0-rc.5.cjs
