defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  eufemia@*:
    dependencies:
      "@emotion/react": "*" # somehow, the template points to the root
      "@mdx-js/react": "*" # somehow, the template points to the root
  "@dnb/eufemia@*":
    dependencies:
      "@emotion/react": "*" # somehow, the template points to the root

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/plugin-ignore-install-options.cjs
    spec: .yarn/unplugged/yarn-plugin-ignore-install-options-npm-1.0.2-e13e094f36/node_modules/yarn-plugin-ignore-install-options/ignore-install-options-1.0.2.js

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.0.cjs
