approvedGitRepositories:
  - "**"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.16.0.cjs
