compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  babel-plugin-lodash@*:
    dependencies:
      "@babel/types": 7.22.5

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.0.1.cjs
