nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/plugin-ignore-install-options.cjs
    spec: packages/yarn-plugin-ignore-install-options/index.js

yarnPath: .yarn/releases/yarn-3.0.2.cjs
