/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Library Index template to autogenerate all the fragments and patterns
 * Used by "prepareTemplates"
 */

import { registerElement } from '../shared/component-helper'

// import all the aviable fragments
import DrawerList from './drawer-list/DrawerList'

// define / export all the aviable fragments
export { DrawerList }

export const getFragments = () => {
  return { DrawerList }
}

let webFragmentsAreEnabled = false
export const enableWebFragments = () => {
  if (webFragmentsAreEnabled) return false
  webFragmentsAreEnabled = true
  const fragments = getFragments()
  // register this fragment to work with custom element
  for (const c in fragments) {
    if (fragments[c] && fragments[c].tagName) {
      registerElement(
        fragments[c].tagName,
        fragments[c],
        fragments[c].defaultProps
      )
    }
  }
}

export default {
  enableWebFragments
}
