import React from 'react';
import type { InputMaskedProps } from '../../../../components/InputMasked';
import type { InputAlign, InputSize } from '../../../../components/Input';
import type { FieldBlockWidth } from '../../FieldBlock';
import type { FieldProps } from '../../types';
export type Props = FieldProps<number, undefined | number> & {
    ref?: React.RefObject<HTMLInputElement>;
    inputClassName?: string;
    currency?: InputMaskedProps['asCurrency'];
    currencyDisplay?: 'code' | 'symbol' | 'narrowSymbol' | 'name' | false;
    percent?: InputMaskedProps['asPercent'];
    mask?: InputMaskedProps['mask'];
    step?: number;
    startWith?: number;
    decimalLimit?: number;
    allowNegative?: boolean;
    disallowLeadingZeroes?: boolean;
    prefix?: string | ((value: number) => string);
    suffix?: string | ((value: number) => string);
    minimum?: number;
    maximum?: number;
    exclusiveMinimum?: number;
    exclusiveMaximum?: number;
    multipleOf?: number;
    size?: InputSize;
    width?: FieldBlockWidth;
    align?: InputAlign;
    showStepControls?: boolean;
};
declare function NumberComponent(props: Props): import("react/jsx-runtime").JSX.Element;
export default NumberComponent;
