/** This file is auto generated by convertSvgToJsx.ts */

const accounting = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M4.733 15h6.534M1 7.533l2.47-2.47a.467.467 0 0 1 .66 0L5.337 6.27a.467.467 0 0 0 .66 0l2.47-2.47M9.4 7.572v1.4m3.733-1.4v1.4m-1.866-2.8v2.8M9.867 15H6.133l.467-2.8h2.8l.467 2.8ZM3.8 12.2h8.4c1.546 0 2.8-1.306 2.8-2.917V3.917C15 2.306 13.746 1 12.2 1H3.8C2.254 1 1 2.306 1 3.917v5.366C1 10.894 2.254 12.2 3.8 12.2Z"
    />
  </svg>
)
export default accounting
