/** This file is auto generated by convertSvgToJsx.ts */

const account_out_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M8.25 7.5H15m2 4.418a16.438 16.438 0 0 0-2.378-2.168H8.628c-2.371 1.77-4.878 4.67-4.878 7.5 0 3.918 1.945 6 7.875 6 3.143 0 5.167-.585 6.375-1.719M15.5 16.5H23M20.5 19l2.5-2.5m0 0L20.5 14M16.5.75l-9 1.5s1.5.818 1.5 3h4.875c0-2.182 2.625-4.5 2.625-4.5Z"
    />
    <path
      fill="#000"
      d="M10.799 19.5h1.575l-1.944-2.511L12.239 15h-1.611l-1.314 1.638V13.2H8v6.3h1.314v-1.287l.324-.36 1.161 1.647Zm2.158 0h1.314v-.54c-.983-.43-1.286-1.122-1.314-1.413V19.5Z"
    />
  </svg>
)
export default account_out_medium
