/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const add_circled = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeMiterlimit={10}
      strokeWidth={1.5}
      d="M8 11.111V4.89M11.111 8H4.89M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
    />
  </svg>
)
export default add_circled
