/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const animal_print = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M10.333 9.828c0-1.317-.965-2.613-2.333-2.613S5.667 8.51 5.667 9.828c-1.094 0-1.867 1.037-1.867 2.09 0 1.628 1.646 2.617 3.043 1.775a2.3 2.3 0 0 1 2.314 0c1.354.816 3.043-.09 3.043-1.774 0-1.054-.773-2.091-1.867-2.091M2.4 9.269c.773 0 1.4-.778 1.4-1.738s-.627-1.739-1.4-1.739S1 6.571 1 7.531s.627 1.738 1.4 1.738m3.267-3.793c.773 0 1.4-.778 1.4-1.738S6.44 2 5.667 2c-.774 0-1.4.778-1.4 1.738s.626 1.738 1.4 1.738m4.666 0c.774 0 1.4-.778 1.4-1.738S11.107 2 10.333 2s-1.4.778-1.4 1.738.627 1.738 1.4 1.738M13.6 9.269c.773 0 1.4-.778 1.4-1.738s-.627-1.739-1.4-1.739-1.4.779-1.4 1.739.627 1.738 1.4 1.738"
    />
  </svg>
)
export default animal_print
