/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const bankid_qr = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M1 8.778h6.222v1.555m3.111 0V15H15v-4.667h-1.556m-6.222 3.111V15m0-14v4.667h1.556m3.11 1.555H15M1 1h3.111v3.111H1zm0 10.889h3.111V15H1zM11.889 1H15v3.111h-3.111z"
    />
  </svg>
)
export default bankid_qr
