/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const bicycle_medium = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m19.5 15.696-2.307-6.085-1.051-2.772c-.181-.48.183-1.032.7-1.033h3.408c.817 0 1.5.692 1.5 1.521s-.683 1.522-1.5 1.522M5.351 4.5l2.144.544 3.005.762m-6 9.89 6.04-2.896m0 0L7.495 5.043M10.54 12.8l6.653-3.189M8.25 15.696c0 2.1-1.679 3.804-3.75 3.804-2.071 0-3.75-1.703-3.75-3.804 0-2.1 1.679-3.804 3.75-3.804 2.071 0 3.75 1.703 3.75 3.804Zm15 0c0 2.1-1.679 3.804-3.75 3.804-2.071 0-3.75-1.703-3.75-3.804 0-2.1 1.679-3.804 3.75-3.804 2.071 0 3.75 1.703 3.75 3.804Z"
    />
  </svg>
)
export default bicycle_medium
