/** This file is auto generated by convertSvgToJsx.ts */
declare const building_construction_medium: (props: any) => import("react/jsx-runtime").JSX.Element;
export default building_construction_medium;
