/** This file is auto generated by convertSvgToJsx.ts */

const calculator = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <g clipPath="url(#calculator_svg__a)">
      <path
        stroke="#000"
        strokeLinecap="round"
        strokeWidth={1.5}
        d="M5.033 3.642v3m-1.5-1.5h3m3.467 0h2m-2 6.853h2m-2-2h2m-8.005 0 2 2m-2 0 2-2M3 15a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H3Z"
      />
    </g>
    <defs>
      <clipPath id="calculator_svg__a">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
)
export default calculator
