/** This file is auto generated by convertSvgToJsx.ts */

const calendar_cancel_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="m19.813 15.69-4.125 4.125m0-4.125 4.124 4.125M6.5 1v2.5m0 0V6m0-2.5h11m-11 0h-4a1 1 0 0 0-1 1v5m16-8.5v2.5m0 0V6m0-2.5h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-20m8.587 13H2.5a1 1 0 0 1-1-1v-12m16.25 13.753a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z"
    />
  </svg>
)
export default calendar_cancel_medium
