/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const camper_trailer = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M6.6 12.154C6.6 13.174 5.764 14 4.733 14a1.857 1.857 0 0 1-1.866-1.846m3.733 0c0-1.02-.836-1.846-1.867-1.846-1.03 0-1.866.826-1.866 1.846m3.733 0h5.6m-9.333 0h-.934A.937.937 0 0 1 1 11.23V2.923C1 2.42 1.425 2 1.933 2h6.534C10.5 2 12.2 3.681 12.2 5.692v6.462m0 0H15M3.873 7a.619.619 0 0 1-.622-.615V4.846c0-.34.279-.615.623-.615h2.355c.344 0 .622.275.622.615v1.539c0 .34-.278.615-.622.615H3.873Z"
    />
  </svg>
)
export default camper_trailer
