/** This file is auto generated by convertSvgToJsx.ts */

const candle_stick = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="M4 6.5h1.5A.5.5 0 0 1 6 7v4a.5.5 0 0 1-.5.5H4m0-5H2.5A.5.5 0 0 0 2 7v4a.5.5 0 0 0 .5.5H4m0-5V4m0 7.5V14m8-9.5h1.5a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5H12m0-7h-1.5a.5.5 0 0 0-.5.5v6a.5.5 0 0 0 .5.5H12m0-7V2m0 9.5V14"
    />
  </svg>
)
export default candle_stick
