/** This file is auto generated by convertSvgToJsx.ts */

const candle_stick_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="M4 11.5h1.5a.5.5 0 0 1 .5.5v4.5a.5.5 0 0 1-.5.5H4m0-5.5H2.5a.5.5 0 0 0-.5.5v4.5a.5.5 0 0 0 .5.5H4m0-5.5V9m0 8v2.5m8-15h1.5a.5.5 0 0 1 .5.5v10.5a.5.5 0 0 1-.5.5H12m0-11.5h-1.5a.5.5 0 0 0-.5.5v10.5a.5.5 0 0 0 .5.5H12m0-11.5V2m0 14v2.5m8-7.5h1.5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5H20m0-8h-1.5a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5H20m0-8V8.5M20 19v2.5"
    />
  </svg>
)
export default candle_stick_medium
