/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const coins_1_medium = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M1 4.5v14.939M1 4.5C1 5.88 4.358 7 8.5 7S16 5.88 16 4.5m-15 0C1 3.12 4.358 2 8.5 2S16 3.12 16 4.5m-15 0v4.939m0 10C1 20.853 4.358 22 8.5 22h1.054M1 19.439v-5M16 4.5v7.47m0-7.47v4.939m-15 5c0 1.324 2.944 2.414 6.718 2.547H8M1 14.44v-5m0 0C1 10.853 4.358 12 8.5 12S16 10.853 16 9.439m0 0v2.53m0 0v1.287M8 15.75c0-1.38 3.358-2.5 7.5-2.5q.252 0 .5.005M8 15.75c0 1.414 3.358 2.561 7.5 2.561S23 17.164 23 15.75m-15 0v1.236m15-1.236v4.689C23 21.853 19.642 23 15.5 23c-2.421 0-4.575-.392-5.946-1M23 15.75c0-1.325-3.091-2.409-7-2.495m-8 3.731v3.453c0 .587.58 1.129 1.554 1.561"
    />
  </svg>
)
export default coins_1_medium
