/** This file is auto generated by convertSvgToJsx.ts */

const digital_advise_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m23.25 20.985-1.49-2.235V13.5c0-2-3.8-4.14-5.25-5.25m1.93 6.543-3.648-2.923a1.303 1.303 0 1 0-1.843 1.843l3.533 3.987v2.5c0 1.18 1.688 3.045 1.688 3.045m-4.66-1.495H2.134A1.375 1.375 0 0 1 .76 20.375V2.124C.76 1.365 1.375.75 2.134.75h13a1.375 1.375 0 0 1 1.376 1.374v11.123M9.76 3.75h3m0 0v3m0-3-9 8.25m1.49 3.75v3m3-5.25v5.25"
    />
  </svg>
)
export default digital_advise_medium
