/** This file is auto generated by convertSvgToJsx.ts */

import React from 'react'
const digipass_corporate = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="M3.054 6.036C2.75 10.423 3.614 15 8.52 15c4.905 0 5.749-4.577 5.416-8.964m-10.882 0c.058-.842.186-2.776.316-3.84a.766.766 0 0 1 .576-.647C4.863 1.309 6.534 1 8.52 1c1.982 0 3.613.308 4.502.548a.762.762 0 0 1 .565.636c.135 1.031.277 2.897.343 3.777l.006.075m-10.882 0c.727.176 2.926.53 5.522.53s4.655-.354 5.36-.53M6.3 3.8h4.4"
    />
  </svg>
)
export default digipass_corporate
