/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const document_pdf_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13 23H2.5C1.94772 23 1.5 22.5523 1.5 22V2C1.5 1.44772 1.94772 1 2.5 1H12.5362C12.8304 1 13.1096 1.12951 13.2996 1.35406L18.2634 7.22036C18.4162 7.40092 18.5 7.62979 18.5 7.86631V9"
      stroke="black"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M8.72167 12H6.21167V19H7.71167V16.3H8.72167C10.2317 16.3 11.1117 15.51 11.1117 14.15C11.1117 12.79 10.2317 12 8.72167 12ZM8.48167 15.1H7.71167V13.2H8.48167C9.24167 13.2 9.59167 13.5 9.59167 14.15C9.59167 14.8 9.24167 15.1 8.48167 15.1Z"
      fill="black"
    />
    <path
      d="M14.2578 12H12.4078V19H14.2578C16.2278 19 17.4078 17.73 17.4078 15.5C17.4078 13.27 16.2278 12 14.2578 12ZM14.1178 17.8H13.9078V13.2H14.1178C15.2678 13.2 15.8778 13.95 15.8778 15.5C15.8778 17.05 15.2678 17.8 14.1178 17.8Z"
      fill="black"
    />
    <path
      d="M23.2139 13.2V12H18.8039V19H20.3039V16.11H22.8139V14.91H20.3039V13.2H23.2139Z"
      fill="black"
    />
  </svg>
)
export default document_pdf_medium
