/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const file_signing_medium = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m22.2 15.3.43-.43a2.115 2.115 0 0 0-.008-3 2.113 2.113 0 0 0-2.992 0l-.43.43-7.2 7.2-.75 3.75L15 22.5l7.2-7.2Zm-3-3 3 3M5 5h5.5M5 8h8.5M5 19h3.5m10-10V7.866a1 1 0 0 0-.237-.646L13.3 1.354A1 1 0 0 0 12.536 1H2.5a1 1 0 0 0-1 1v20a1 1 0 0 0 1 1H8"
    />
  </svg>
)
export default file_signing_medium
