/** This file is auto generated by convertSvgToJsx.ts */

const file_signing = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M11.62 8.627 7.607 12.64 7.135 15l2.36-.472 4.012-4.013M11.62 8.627l1.887 1.888M11.62 8.627l.788-.787a1.331 1.331 0 0 1 2.176.436 1.33 1.33 0 0 1-.289 1.451l-.788.788M11.29 4.5 8.62 1.353A1 1 0 0 0 7.857 1H2a1 1 0 0 0-1 1v11.843a1 1 0 0 0 1 1h2"
    />
  </svg>
)
export default file_signing
