/** This file is auto generated by convertSvgToJsx.ts */

const file_loupe = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="m9.59 2.5-.97-1.146A1 1 0 0 0 7.856 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h3m10 0-1.555-1.555m-.49-3.968a3.477 3.477 0 1 1-6.955 0 3.477 3.477 0 0 1 6.954 0Z"
    />
  </svg>
)
export default file_loupe
