/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const file_ppt_medium = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M13 23H2.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h10.036a1 1 0 0 1 .764.354l4.963 5.866a1 1 0 0 1 .237.646V9"
    />
    <path
      fill="#000"
      d="M8.716 12h-2.51v7h1.5v-2.7h1.01c1.51 0 2.39-.79 2.39-2.15S10.226 12 8.716 12m-.24 3.1h-.77v-1.9h.77c.76 0 1.11.3 1.11.95s-.35.95-1.11.95m6.436-3.1h-2.51v7h1.5v-2.7h1.01c1.51 0 2.39-.79 2.39-2.15s-.88-2.15-2.39-2.15m-.24 3.1h-.77v-1.9h.77c.76 0 1.11.3 1.11.95s-.35.95-1.11.95m8.976-3.1h-5.3v1.2h1.9V19h1.5v-5.8h1.9z"
    />
  </svg>
)
export default file_ppt_medium
