/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const football_medium = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={26}
    height={26}
    fill="none"
    viewBox="0 0 26 26"
    {...props}
  >
    <path
      stroke="#000"
      strokeWidth={1.5}
      d="M13 .765C6.243.765.765 6.243.765 13S6.243 25.235 13 25.235 25.235 19.757 25.235 13 19.757.765 13 .765Zm0 0V7.68m0 0-5.586 3.724M13 7.68l5.32 3.724m-8.778 6.384-3.68 5.151m3.68-5.151h6.916m-6.916 0-2.128-6.384m9.044 6.384 3.552 5.242m-3.552-5.242 1.862-6.384m0 0 6.22-2.482M7.413 11.404 1.395 9.113"
    />
  </svg>
)
export default football_medium
