/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const football = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 17 17"
    {...props}
  >
    <path
      stroke="#000"
      strokeWidth={1.5}
      d="M8.5.94v4.2m0 0L4.972 7.492M8.5 5.14l3.36 2.352m-5.544 4.032-2.184 3.023m2.184-3.023h4.368m-4.368 0L4.972 7.492m5.712 4.032 2.016 3.023m-2.016-3.023 1.176-4.032m0 0 3.695-1.344M4.972 7.492 1.445 6.148M16.227 8.5a7.727 7.727 0 1 1-15.454 0 7.727 7.727 0 0 1 15.454 0Z"
    />
  </svg>
)
export default football
