/** This file is auto generated by convertSvgToJsx.ts */

const fortune_ball = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M3.906 12.084A5.149 5.149 0 0 1 2.52 9.473a5.243 5.243 0 0 1 .264-2.963 5.077 5.077 0 0 1 1.824-2.308 4.859 4.859 0 0 1 2.765-.869 4.86 4.86 0 0 1 2.765.866 5.076 5.076 0 0 1 1.826 2.306c.373.939.466 1.97.267 2.963a5.149 5.149 0 0 1-1.383 2.612M1.874 1v1.75M1 1.875h1.75M8.292 6v1.75m-.875-.875h1.75m4.125-5.292v1.75m-.875-.875h1.75m-3.225 9.625H3.807l-.687 1.125a.836.836 0 0 0-.036.798c.06.123.151.227.262.3a.67.67 0 0 0 .366.11h7.325a.67.67 0 0 0 .366-.11.755.755 0 0 0 .263-.3.835.835 0 0 0-.036-.798l-.688-1.124Z"
    />
  </svg>
)
export default fortune_ball
