/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const heart = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M8 14.133 2.034 7.97a3.47 3.47 0 0 1-.66-4.037c.25-.495.615-.924 1.065-1.253a3.55 3.55 0 0 1 3.175-.51 3.5 3.5 0 0 1 1.412.855L8 3.99l.974-.965a3.56 3.56 0 0 1 4.587-.345c.45.329.816.758 1.067 1.254v0a3.47 3.47 0 0 1-.662 4.036z"
    />
  </svg>
)
export default heart
