/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const information_bubble = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M9 10.667h-.5a1 1 0 0 1-1-1v-2.5a.5.5 0 0 0-.5-.5h-.5m.664-2.41h.022M7.523.75a6.75 6.75 0 0 1 5.91 3.472 6.76 6.76 0 0 1-.168 6.855l1.985 4.173-4.169-1.987A6.757 6.757 0 0 1 1.008 9.37a6.77 6.77 0 0 1 3.497-7.913A6.76 6.76 0 0 1 7.523.75"
    />
  </svg>
)
export default information_bubble
