/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const insurance_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M12 2.25A11.25 11.25 0 0 1 23.25 13.5l-.811-.676a4.707 4.707 0 0 0-6.689.676A5.3 5.3 0 0 0 12 11.945m0-9.695A11.25 11.25 0 0 0 .75 13.5l.811-.676a4.706 4.706 0 0 1 6.689.676A5.3 5.3 0 0 1 12 11.945m0-9.695V.75m0 11.195v9.802a1.5 1.5 0 1 1-3 0"
    />
  </svg>
)
export default insurance_medium
