/** This file is auto generated by convertSvgToJsx.ts */

const loan_in_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M23.25 20.25h-1.5m-21 0h1.5m8.25-11.5h3a.75.75 0 0 1 .75.75v10.75m-12 0h4.5m-4.5 0V16m4.5 4.25h3m-3 0V19m3 1.25h4.5m-4.5 0V16m4.5 4.25h3m0 0V13.5a.75.75 0 0 1 .75-.75h3a.75.75 0 0 1 .75.75v6.75m-4.5 0h4.5M2.25 9V5.5A.75.75 0 0 1 3 4.75h3a.75.75 0 0 1 .75.75V6M1 12.5h7.5M6 15l2.5-2.5m0 0L6 10"
    />
  </svg>
)
export default loan_in_medium
