/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const mastercard_card = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="M7.925 3.482A3.855 3.855 0 1 0 4.5 10.115m3.425-6.633a3.857 3.857 0 0 1 6.254 1.735M7.925 3.481c.515.46.905 1.058 1.114 1.734m-2.375.71c.016-.145.04-.288.072-.428m.732 5.214V12a1 1 0 0 0 1 1H14a1 1 0 0 0 1-1v-1.288m-7.532 0v-1.96a1 1 0 0 1 1-1H14a1 1 0 0 1 1 1v1.96m-7.532 0H15"
    />
  </svg>
)
export default mastercard_card
