/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const plant_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M7.653 5.984s4.5 2.25 5.25 9.75c1.5-4.5 3.75-6 3.75-6m-6-.75s-1.53 2.62-3.75 2.25c-4.5-.75-3.75-6.75-5.25-9a9.947 9.947 0 0 1 9 .75c2.247 1.5 2.247 3.75 0 6Zm4.922 2.198S16.638 13 18.18 12.745c3.125-.521 2.6-4.688 3.646-6.251a6.913 6.913 0 0 0-6.251.52c-1.562 1.043-1.562 2.606 0 4.168Zm.463 12.052h-6.27a.75.75 0 0 1-.735-.6l-1.2-6a.75.75 0 0 1 .735-.9h8.67a.75.75 0 0 1 .736.9l-1.2 6a.75.75 0 0 1-.736.6Z"
    />
  </svg>
)
export default plant_medium
