/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const sea_transport = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M12 7.51V3.996c0-.529-.21-1.036-.586-1.41A2.002 2.002 0 0 0 10 2H6a1.993 1.993 0 0 0-2 1.995v3.516m11 1.197L8.371 6.062a1.002 1.002 0 0 0-.742 0L1 8.708m1.239-.495 1.06 3.166m4.701-.4V5.991m5.761 2.222-1.108 3.31m.26-.777L8 9.496l-4.913 1.25M1 14c.5 0 .594-.015 1.113-.188a3.676 3.676 0 0 0 1.387-.837 3.033 3.033 0 0 0 4.5 0 3.033 3.033 0 0 0 4.5 0c.394.378.868.664 1.387.837.519.173.613.188 1.113.188M7 2h2"
    />
  </svg>
)
export default sea_transport
