/** This file is auto generated by convertSvgToJsx.ts */

import type { IconSVGProps } from '../../components/icon/Icon'
const vintage_car_medium = (props?: IconSVGProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M20.25 15v-3.75m-2.599 5.25A2.999 2.999 0 0 1 23.25 18a3 3 0 0 1-3 3c-2.28 0-3.717-2.567-2.599-4.5Zm2.599-5.25V7.5m0 3.75c0-.817-.683-1.5-1.5-1.5h-4.5m0 0V3m0 6.75h-6m0-6.75h6l2.25.75m-8.25 6V3m0 6.75h-6m8.25 3H9M8.25 3h-4.5c-.817 0-1.5.683-1.5 1.5v5.25m15.401 6.75H6.35m-4.1-1.099A2.999 2.999 0 0 0 3.75 21c2.28 0 3.717-2.567 2.599-4.5-.82-1.416-2.691-1.913-4.099-1.099Zm0 0V9.75"
    />
  </svg>
)
export default vintage_car_medium
