/** 
  ATTENTION: This file is auto generated by using "makeDemosFactory".
  Do not change the content!
     */

import Button from './Button'
import Dropdown from './Dropdown'
import FormLabel from './FormLabel'
import Icon from './Icon'
import Input from './Input'
import InputMasked from './InputMasked'
import LineTitle from './LineTitle'
import Logo from './Logo'
import Modal from './Modal'
import Notification from './Notification'
import Slider from './Slider'
import Switch from './Switch'
import Tabs from './Tabs'

export default [
  Button,
  Dropdown,
  FormLabel,
  Icon,
  Input,
  InputMasked,
  LineTitle,
  Logo,
  Modal,
  Notification,
  Slider,
  Switch,
  Tabs
]
