import { AccordionProps, GroupProps } from './Accordion'

export const accordionDefaultProps: AccordionProps & GroupProps = {
  title: null,
  expanded: null,
  no_animation: null,
  expanded_ssr: null,
  prerender: null,
  prevent_rerender: null,
  prevent_rerender_conditional: null,
  remember_state: null,
  contentRef: null,
  flush_remembered_state: null,
  single_container: null,
  variant: 'outlined',
  left_component: null,
  allow_close_all: null,
  disabled: null,
  skeleton: null,
  id: null,
  group: null,
  element: null,
  heading: null,
  heading_level: null,
  icon: null,
  icon_position: null,
  icon_size: 'medium',
  attributes: null,
  class: null,

  className: null,
  children: null,

  on_change: null,
  on_state_update: null,
} as const
