/**
 * Prepublish Task
 *
 */

import gulp from 'gulp'
import rename from 'gulp-rename'
import transform from 'gulp-transform'
import prettier from 'prettier'
import stylelint from 'stylelint'
import packpath from 'packpath'
import { log } from '../../lib'
import { transformSass } from './transformUtils'
import { convertVariablesToTailwindFormat } from './tailwindTransform'
import { promises as fs } from 'fs'
import figmaColors from '../../../src/style/themes/figma-colors'

const ROOT_DIR = packpath.self()

export default async function makePropertiesFile() {
  await runFactory()
  await runFigmaFactory()

  log.succeed(
    '> PrePublish: "makePropertiesFile" creating properties file done'
  )
}

const transformModulesContent = async (content) => {
  const variables = content
    .split('\n')
    .map((s) => s.trim())
    .filter((s) => s.startsWith('--'))
    .map((s) => s.split(':').map((s) => s.trim()))
    .reduce((acc, [k, v]) => {
      acc[k] = v
        .split(';')[0]
        .replace(/\/\* .* \*\//g, '')
        .trim()
      return acc
    }, {})

  return (
    String(
      await prettier.format(
        `/** This file is auto generated by makePropertiesFile.js */

export default ${JSON.stringify(variables, null, 2)}`,
        {
          filepath: 'file.js',
          semi: true,
          trailingComma: 'none',
          singleQuote: true,
        }
      )
    ).trim() + ' // prettier-ignore\n' // so manual changes not removes the semi
  )
}

const transformModulesContentCSS = async (content) => {
  const variables = content
    .split('\n')
    .map((s) => s.trim())
    .filter((s) => s.startsWith('--'))
    .map((s) => s.split(':').map((s) => s.trim()))
    .reduce((acc, [k, v]) => {
      acc[k] = v
        .split(';')[0]
        .replace(/\/\* .* \*\//g, '')
        .trim()
      return acc
    }, {})

  // Convert --sb-* variables to Tailwind-compatible format
  const convertedVariables = convertVariablesToTailwindFormat(variables)

  const cssContent = Object.entries(convertedVariables)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n')

  return (
    String(
      await prettier.format(
        `/* This file is auto generated by makePropertiesFile.js */

/* stylelint-disable-next-line scss/at-rule-no-unknown */
@theme {
${cssContent}
}`,
        {
          filepath: 'file.css',
          parser: 'css',
          singleQuote: true,
          tabWidth: 2,
          useTabs: false,
        }
      )
    ).trim() + '\n'
  )
}

export const runFactory = ({
  returnResult = false,
  glob = './src/style/themes/*/properties-js.scss',
} = {}) =>
  new Promise((resolve, reject) => {
    log.start('> PrePublish: transforming style modules')
    try {
      // Generate JS files
      gulp
        .src([glob], {
          cwd: ROOT_DIR,
        })
        .pipe(transform('utf8', transformSass()))
        .pipe(transform('utf8', transformModulesContent))
        .pipe(
          rename({
            basename: 'properties',
            extname: '.js',
          })
        )
        .pipe(
          returnResult
            ? transform('utf8', (result) => resolve(result))
            : gulp.dest('./src/style/themes/', {
                overwrite: true,
                cwd: ROOT_DIR,
              })
        )
        .on('end', () => {
          // Generate CSS files
          gulp
            .src([glob], {
              cwd: ROOT_DIR,
            })
            .pipe(transform('utf8', transformSass()))
            .pipe(transform('utf8', transformModulesContentCSS))
            .pipe(
              rename({
                basename: 'properties-tailwind',
                extname: '.css',
              })
            )
            .pipe(
              returnResult
                ? transform('utf8', (result) => resolve(result))
                : gulp.dest('./src/style/themes/', {
                    overwrite: true,
                    cwd: ROOT_DIR,
                  })
            )
            .on('end', resolve)
            .on('error', reject)
        })
        .on('error', reject)
    } catch (e) {
      reject(e)
    }
  })

const recur = (prefix, value) => {
  if (typeof value == 'string' || typeof value === 'number') {
    return ''
  }
  if (Object.hasOwn(value, '$type')) {
    const alpha = value['$value']['alpha']
    const hex = value['$value']['hex']
    const val = alpha === 1 ? hex : `rgba(${hex}, ${alpha.toPrecision(2)})`

    return `${prefix}: ${val};\n`
  } else {
    let result = ''
    for (const [key, val] of Object.entries(value)) {
      result += recur(`${prefix}${key === '$root' ? '' : `-${key}`}`, val)
    }
    return result
  }
}

const makeFigmaSCSS = async () => {
  let scssContent =
    '/* This file is auto generated by makePropertiesFile.js */\n\n:root {\n'
  scssContent += recur('  -', figmaColors)

  scssContent += '}\n'

  const prettierResult = String(
    await prettier.format(scssContent, {
      filepath: 'file.scss',
      parser: 'scss',
      singleQuote: true,
      tabWidth: 2,
      useTabs: false,
    })
  )

  const stylelintResult = await stylelint.lint({
    code: prettierResult,
    fix: true,
  })
  return stylelintResult.output
}

export const runFigmaFactory = async () => {
  log.start('> PrePublish: transforming figma variables to SCSS')

  await fs.writeFile(
    './src/style/themes/figma-colors.scss',
    await makeFigmaSCSS()
  )
}
