/**
 * Prepublish Task
 *
 */

import gulp from 'gulp'
import rename from 'gulp-rename'
import transform from 'gulp-transform'
import prettier from 'prettier'
import stylelint from 'stylelint'
import packpath from 'packpath'
import { log } from '../../lib'
import { transformSass } from './transformUtils'
import { convertVariablesToTailwindFormat } from './tailwindTransform'
import fs, { promises } from 'fs'
import path from 'path'

const prettierrc = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '../../../.prettierrc'), 'utf-8')
)

const TOKEN_GROUP_SEPARATOR = '-'
const TOKEN_CHAR_REPLACEMENT = '_'
const TOKEN_CSS_PREFIX = '--'

const ROOT_DIR = packpath.self()

export default async function makePropertiesFile() {
  await runFactory()
  await runFigmaFactory()

  log.succeed(
    '> PrePublish: "makePropertiesFile" creating properties file done'
  )
}

const transformModulesContent = async (content: string) => {
  const variables = content
    .split('\n')
    .map((s) => s.trim())
    .filter((s) => s.startsWith('--'))
    .map((s) => s.split(':').map((s) => s.trim()))
    .reduce((acc, [k, v]) => {
      acc[k] = v
        .split(';')[0]
        .replace(/\/\* .* \*\//g, '')
        .trim()
      return acc
    }, {})

  return (
    String(
      await prettier.format(
        `/** This file is auto generated by makePropertiesFile.ts */

export default ${JSON.stringify(variables, null, 2)}`,
        {
          filepath: 'file.js',
          semi: true,
          trailingComma: 'none',
          singleQuote: true,
        }
      )
    ).trim() + ' // prettier-ignore\n' // so manual changes not removes the semi
  )
}

const transformModulesContentCSS = async (content: string) => {
  const variables = content
    .split('\n')
    .map((s) => s.trim())
    .filter((s) => s.startsWith('--'))
    .map((s) => s.split(':').map((s) => s.trim()))
    .reduce((acc, [k, v]) => {
      acc[k] = v
        .split(';')[0]
        .replace(/\/\* .* \*\//g, '')
        .trim()
      return acc
    }, {})

  // Convert --sb-* variables to Tailwind-compatible format
  const convertedVariables = convertVariablesToTailwindFormat(variables)

  const cssContent = Object.entries(convertedVariables)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n')

  return (
    String(
      await prettier.format(
        `/* This file is auto generated by makePropertiesFile.ts */

/* stylelint-disable-next-line scss/at-rule-no-unknown */
@theme {
${cssContent}
}`,
        {
          filepath: 'file.css',
          parser: 'css',
          singleQuote: true,
          tabWidth: 2,
          useTabs: false,
        }
      )
    ).trim() + '\n'
  )
}

type RunFactoryOptions = {
  returnResult?: boolean
  glob?: string
}

export const runFactory = ({
  returnResult = false,
  glob = './src/style/themes/*/properties-js.scss',
}: RunFactoryOptions = {}) =>
  new Promise<string | undefined>((resolve, reject) => {
    log.start('> PrePublish: transforming style modules')
    try {
      const gulpTransform = transform as any
      // Generate JS files
      gulp
        .src([glob], {
          cwd: ROOT_DIR,
        })
        .pipe(gulpTransform('utf8', transformSass()))
        .pipe(gulpTransform('utf8', transformModulesContent))
        .pipe(
          rename({
            basename: 'properties',
            extname: '.js',
          })
        )
        .pipe(
          returnResult
            ? gulpTransform('utf8', (result: string) => resolve(result))
            : gulp.dest('./src/style/themes/', {
                overwrite: true,
                cwd: ROOT_DIR,
              })
        )
        .on('end', () => {
          // Generate CSS files
          gulp
            .src([glob], {
              cwd: ROOT_DIR,
            })
            .pipe(gulpTransform('utf8', transformSass()))
            .pipe(gulpTransform('utf8', transformModulesContentCSS))
            .pipe(
              rename({
                basename: 'properties-tailwind',
                extname: '.css',
              })
            )
            .pipe(
              returnResult
                ? gulpTransform('utf8', (result: string) =>
                    resolve(result)
                  )
                : gulp.dest('./src/style/themes/', {
                    overwrite: true,
                    cwd: ROOT_DIR,
                  })
            )
            .on('end', () => resolve(undefined))
            .on('error', reject)
        })
        .on('error', reject)
    } catch (e) {
      reject(e)
    }
  })

export const transformFigmaAlias = (alias: Record<string, any>) => {
  const figmaVariableName = alias.targetVariableName
  // const figmaVariableSetId = alias.targetVariableSetId
  // TODO: use is to verify the correct supported sets are used instead of name.
  // Need to figure out if set ID works as expected.
  //  "VariableCollectionId:e5cc40ef8bbcdb0b7df7793463523846b0a81d09/2155:222"
  const figmaVariableSetName = alias.targetVariableSetName

  if (figmaVariableSetName === 'Colors') {
    const path = figmaVariableName.split('/')
    return `var(${transformNamespace()}${transformFigmaPath(path)})` // Including transform namespace as we might want to be able to apply that in the future
  } else {
    log.warn(
      `Unsupported variable set: ${figmaVariableSetName} for variable ${figmaVariableName}`
    )
  }
}

export const transformFigmaValue = (value: Record<string, any>) => {
  if (value['$type'] === 'number' || value['$type'] === 'string') {
    return undefined // Exclude numbers, font-family and font weight
  }

  const alias = value?.$extensions?.['com.figma.aliasData']

  if (alias) {
    return transformFigmaAlias(alias)
  }

  if (value['$type'] === 'color') {
    const alpha = value['$value']['alpha']
    const hex = value['$value']['hex']

    try {
      return alpha === 1 ? hex : `rgba(${hex}, ${alpha.toPrecision(2)})`
    } catch (e) {
      console.log(value)
      throw e
    }
  } else {
    throw new Error(`Unsupported $type: ${value['$type']}`)
  }
}

export const transformFigmaKey = (
  key: string,
  replaceCallback: (s: string) => void = () => {}
) => {
  const replaceChar = (s) => {
    replaceCallback(s)
    return TOKEN_CHAR_REPLACEMENT
  }

  const transformedKey = key
    .replaceAll(/[^a-zA-Z-0-9]/g, replaceChar)
    .toLowerCase()

  return transformedKey
}

export const transformFigmaPath = (path: string[]) => {
  const replacedCaracters = []
  const logReplace = (s) => {
    replacedCaracters.push(s)
  }
  const filteredPath = path.filter(Boolean)
  const transformedPath = filteredPath
    .map((s) => transformFigmaKey(s, logReplace))
    .join(TOKEN_GROUP_SEPARATOR)

  if (replacedCaracters.length > 0) {
    log.warn(`  ┌ Unsupported characters "${replacedCaracters.join(
      '", "'
    )}" replaced with "${TOKEN_CHAR_REPLACEMENT}":
    └ Variable: "${filteredPath.join('/')}"`)
  }
  return transformedPath
}

export const transformNamespace = (namespace?: string) =>
  TOKEN_CSS_PREFIX + (namespace ? namespace + TOKEN_GROUP_SEPARATOR : '')

/** Recursively generates CSS variables from a Figma export json */
export const generateCSSVariablesFromFigmaExport = (
  value: Record<string, any> | string | number,
  /** string placed first in the css variable: `--namespace-color-blue-500` */
  namespace?: string,
  path: string[] = []
) => {
  if (typeof value == 'string' || typeof value === 'number') {
    return ''
  }
  if (Object.hasOwn(value, '$type')) {
    const val = transformFigmaValue(value)
    return val
      ? `${transformNamespace(namespace)}${transformFigmaPath(
          path
        )}: ${val};\n`
      : ''
  } else {
    let result = ''
    for (const [key, val] of Object.entries(value)) {
      const newPath = key === '$root' ? path : [...path, key]
      result += generateCSSVariablesFromFigmaExport(
        val,
        namespace,
        newPath
      )
    }
    return result
  }
}

const makeFigmaSCSS = async (
  /** Root path to Figma JSON export file */
  inputPath: string,
  /** Root path for the generated SCSS file */
  outputPath: string,
  /** prefix that is added to the start of the css variable name */
  namespace: string
) => {
  const json = JSON.parse(
    fs.readFileSync(path.resolve(inputPath), 'utf-8')
  )
  log.info(`  Generating SCSS file: ${outputPath}`)

  let scssContent =
    '/* This file is auto generated by makePropertiesFile.ts */\n\n:root {\n'
  scssContent += generateCSSVariablesFromFigmaExport(json, namespace)

  scssContent += '}\n'

  const prettierResult = String(
    await prettier.format(scssContent, {
      filepath: '*.scss',
      ...prettierrc,
    })
  )

  const stylelintResult = await stylelint.lint({
    code: prettierResult,
    fix: true,
  })

  await promises.writeFile(outputPath, stylelintResult.output)
}

export const runFigmaFactory = async () => {
  log.start('> PrePublish: transforming figma variables to SCSS')

  const files = [
    {
      in: './src/style/themes/figma/Mode 1.tokens 5.json',
      out: './src/style/themes/all-foundation.scss',
      prefix: undefined,
    },
    {
      in: './src/style/themes/figma/DNB Light.tokens.json',
      out: './src/style/themes/ui/tokens.scss',
      prefix: 'token',
    },

    {
      in: './src/style/themes/figma/Sbanken Light.tokens.json',
      out: './src/style/themes/sbanken/tokens.scss',
      prefix: 'token',
    },
    {
      in: './src/style/themes/figma/DNB Carnegie Light.tokens.json',
      out: './src/style/themes/carnegie/tokens.scss',
      prefix: 'token',
    },
  ]

  log.info(
    `> PrePublish: "makePropertiesFile" Generating Figma sass files:`
  )

  files.forEach(async (file) => {
    await makeFigmaSCSS(file.in, file.out, file.prefix)
  })
}
