/**
 * Insert all the component styles into the main styles lib file
 *
 */

import fs from 'fs-extra'
import globby from 'globby'
import path, { basename } from 'path'
import prettier from 'prettier'
import { ErrorHandler, log } from '../../lib'

const prettierrc = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '../../../.prettierrc'), 'utf-8')
)

const fallbackPrefix = 'dnb'

const runStyleFactory = async () => {
  log.start('> PrePublish: Starting the style factory ...')

  const processToNamesIgnoreList = [
    '!**/__tests__/',
    '!**/stories/',
    '!**/style/',
    '!**/helper-classes/',
    '!**/*_not_in_use/',
  ]

  // components
  await runFactory({
    scssOutputFile: path.resolve(
      __dirname,
      `../../../src/style/${fallbackPrefix}-ui-components.scss`
    ),
    customContent: `
@import './core/utilities.scss';
@import './${fallbackPrefix}-ui-fragments.scss';
`,
    scssTemplateToFill: `@import '../components/{name}/style/${fallbackPrefix}-{name}.scss';`,
    filesToFindGlob: [
      path.resolve(__dirname, '../../../src/components/*'),
    ].concat(processToNamesIgnoreList),
    processOnlyList: [
      path.resolve(__dirname, '../../../src/components/**/style/*.scss'),
    ],
  }).then(() => {
    if (require.main === module) {
      log.succeed(
        '> PrePublish: "styleFactory" Created the style file with all the components'
      )
    }
  })

  // elements
  await runFactory({
    scssOutputFile: path.resolve(
      __dirname,
      `../../../src/style/${fallbackPrefix}-ui-elements.scss`
    ),
    customContent: `
@import './core/utilities.scss';`,
    scssTemplateToFill: `@import '../elements/{name}/style/${fallbackPrefix}-{name}.scss';`,
    filesToFindGlob: [
      path.resolve(__dirname, '../../../src/elements/*'),
    ].concat(processToNamesIgnoreList),
    processOnlyList: [
      path.resolve(__dirname, '../../../src/elements/**/style/*.scss'),
    ],
  }).then(() => {
    if (require.main === module) {
      log.succeed(
        '> PrePublish: "styleFactory" Created the style file with all the elements'
      )
    }
  })

  // fragments
  await runFactory({
    scssOutputFile: path.resolve(
      __dirname,
      `../../../src/style/${fallbackPrefix}-ui-fragments.scss`
    ),
    customContent: `
@import './core/utilities.scss';
`,
    scssTemplateToFill: `@import '../fragments/{name}/style/${fallbackPrefix}-{name}.scss';`,
    filesToFindGlob: [
      path.resolve(__dirname, '../../../src/fragments/*'),
    ].concat(processToNamesIgnoreList),
    processOnlyList: [
      path.resolve(__dirname, '../../../src/fragments/**/style/*.scss'),
    ],
  }).then(() => {
    if (require.main === module) {
      log.succeed(
        '> PrePublish: "styleFactory" Created the style file with all the fragments'
      )
    }
  })

  // extensions
  await runFactory({
    scssOutputFile: path.resolve(
      __dirname,
      `../../../src/style/${fallbackPrefix}-ui-extensions.scss`
    ),
    customContent: `
@import './core/utilities.scss';
`,
    scssTemplateToFill: `@import '../extensions/{name}/style/${fallbackPrefix}-{name}.scss';`,
    filesToFindGlob: [
      path.resolve(__dirname, '../../../src/extensions/*'),
    ].concat(processToNamesIgnoreList),
    processOnlyList: [
      path.resolve(__dirname, '../../../src/extensions/**/style/*.scss'),
    ],
  }).then(() => {
    if (require.main === module) {
      log.info('> Created the style file with all the extensions')
    }
  })
}

const autoAdvice =
  '/**\n * ATTENTION: This file is auto generated by using "styleFactory".\n * Do not change the content!\n *\n */\n\n'

const runFactory = async ({
  scssOutputFile,
  scssTemplateToFill,
  filesToFindGlob,
  processOnlyList = null,
  customContent = '',
  onlyDirectories = true,
}) => {
  try {
    filesToFindGlob = await globby(filesToFindGlob, {
      onlyDirectories,
    })
    filesToFindGlob.sort()
    if (processOnlyList) {
      const processedList = await globby(processOnlyList)
      filesToFindGlob = filesToFindGlob.filter((source) =>
        processedList.some((file) => file.indexOf(source) !== -1)
      )
    }
  } catch (e) {
    log.fail(e)
  }

  filesToFindGlob = filesToFindGlob.map((source) => ({
    source,
    name: basename(source),
  }))

  const content = filesToFindGlob
    .reduce((acc, { name }) => {
      acc.push(scssTemplateToFill.replace(new RegExp('{name}', 'g'), name))
      return acc
    }, [])
    .join('\n')

  try {
    // make sure we have newline at the end - because of StyleLint "no-missing-end-of-source-newline"
    await fs.writeFile(
      scssOutputFile,
      await prettier.format(`${autoAdvice}${customContent}${content}\n`, {
        ...prettierrc,
        filepath: scssOutputFile,
      })
    )
  } catch (e) {
    log.fail(`There was an error on creating ${scssOutputFile}!`)
    ErrorHandler(e)
  }
}

if (require.main === module && process.env.NODE_ENV !== 'test') {
  log.start()
  runStyleFactory().then(() => {
    log.succeed()
  })
}

export { runStyleFactory }
