const base = require('./.dependency-cruiser.js')

/**
 * Orphan (unused-file) detection.
 *
 * This runs as a SEPARATE cruise from `.dependency-cruiser.js` on purpose:
 * orphan detection needs `tsPreCompilationDeps: true` so that files which are
 * only reached through `import type { ... }` are not reported as false
 * orphans, but enabling that option globally would make the `no-circular`
 * rule report ~1700 harmless type-only cycles (component -> shared/Context ->
 * generated barrel). Keeping the two cruises apart lets each use the settings
 * it needs.
 */
module.exports = {
  forbidden: [
    {
      name: 'no-orphans',
      comment:
        'This file is not imported by anything and imports nothing (an ' +
        'orphan). It is most likely dead code. If it is intentional (a new ' +
        'entry point, a file consumed only by tooling/docs, etc.), add it to ' +
        'the "pathNot" list in .dependency-cruiser.orphans.cjs.',
      severity: 'error',
      from: {
        orphan: true,
        pathNot: [
          // Ambient / companion type declarations are picked up automatically
          // by the compiler, never imported explicitly.
          '\\.d\\.ts$',

          // Test files and Playwright e2e specs are entry points for the test
          // runners, not imported by application code.
          '(^|/)__tests__/',
          '\\.(test|spec)\\.(js|ts|tsx)$',
          '\\.e2e\\.',

          // Code-generation templates are read as strings by
          // scripts/prebuild/tasks/prepareTemplates.ts.
          '(^|/)core/templates/',

          // Test/build infrastructure wired up through vitest config
          // (setupFiles + resolve.alias mocks), not via imports.
          '(^|/)core/(test-utils|vitest)/',

          // Files generated by the build (regenerated on every build and
          // guarded by verify:generated-entries:ci).
          '(^|/)shared/build-info/BuildInfoData\\.ts$',
          '(^|/)style/themes/[^/]+/properties\\.ts$',

          // Published style entry points and build inputs that are consumed
          // cross-package (portal), by prebuild scripts, or by end users via
          // package subpaths — none of which this src-only cruise can see.
          '(^|/)style/isolated\\.ts$',
          '(^|/)style/themes/figma/tokenValueUtils\\.ts$',
          '(^|/)style/themes/ui/prism/dnb-prism-theme\\.ts$',
          '(^|/)components/icon/filledIconSet\\.ts$',
        ],
      },
      to: {},
    },
  ],
  options: {
    ...base.options,
    // See the file-level comment: required so type-only imports count as
    // real usage and don't produce false orphans.
    tsPreCompilationDeps: true,
  },
}
