import {
  defaultDesign,
  pluss,
  young,
  myFirst,
  youth,
  gold,
  saga,
  sagaPlatinum,
  privateBanking,
  mcBlack,
  businessNoVisa,
  businessWithVisa,
  sbankenVisa,
  sbankenMastercard,
} from './CardDesigns'

import { PaymentCardType } from '../types'

const cardData: PaymentCardType[] = [
  {
    productCode: 'NK1',
    displayName: 'DNB Kortet',
    ...defaultDesign,
  },
  {
    productCode: 'NK4',
    displayName: 'DNB Kortet',
    ...defaultDesign,
  },
  {
    productCode: 'NK5',
    displayName: 'DNB Kortet',
    ...defaultDesign,
  },
  {
    productCode: 'VE1',
    displayName: 'DNB Electron',
    ...defaultDesign,
    paymentType: null,
  },
  {
    productCode: 'VE2',
    // productName: 'DNB Electron u/leg',
    displayName: 'DNB Electron',
    ...defaultDesign,
    paymentType: null,
  },
  {
    productCode: 'VG1',
    // productName: 'SAGA Gull Visa',
    displayName: 'SAGA Gull',
    productType: { type: 'SagaGold' },
    ...saga,
    cardProvider: { type: 'Visa', color: saga.cardProvider.color },
  },
  {
    productCode: 'VG4',
    // productName: 'SAGA Gull Visa u/leg',
    displayName: 'SAGA Gull',
    productType: { type: 'SagaGold' },
    ...saga,
    cardProvider: { type: 'Visa', color: saga.cardProvider.color },
  },
  {
    productCode: '053',
    // productName: 'SAGA Gull Mastercard',
    displayName: 'SAGA Gull',
    productType: { type: 'SagaGold' },
    ...saga,
  },
  {
    productCode: 'VK2',
    displayName: 'DNB Visa',
    ...defaultDesign,
  },
  {
    productCode: 'VK4',
    displayName: 'DNB Visa',
    ...defaultDesign,
  },
  {
    productCode: '084',
    // productName: 'Pluss Mastercard(leve)',
    displayName: 'Pluss Mastercard',
    productType: { type: 'Pluss' },
    ...pluss,
    paymentType: null,
    cardProvider: { type: 'Mastercard' },
  },
  {
    productCode: 'VL1',
    // productName: 'Sølv Visa',
    displayName: 'Pluss Visa',
    productType: { type: 'Pluss' },
    ...pluss,
  },
  {
    productCode: 'VL2',
    displayName: 'Hvitt kort',
    ...young,
    cardProvider: { type: 'Visa' },
  },
  {
    productCode: 'VL3',
    // productName: 'Sølv Visa',
    displayName: 'Pluss Visa',
    productType: { type: 'Pluss' },
    ...pluss,
  },
  {
    productCode: 'VL4',
    // productName: 'DNB Visa u/leg',
    displayName: 'DNB Visa',
    ...defaultDesign,
  },
  {
    productCode: 'VL6',
    // productName: 'Hvitt Visa u/leg',
    displayName: 'Hvitt kort',
    ...young,
    cardProvider: { type: 'Visa' },
  },
  {
    productCode: '085',
    // productName: 'Ung Mastercard(student)',
    displayName: 'Ung Mastercard',
    ...young,
  },
  {
    productCode: 'VO1',
    displayName: 'DNB Visa Online',
    ...defaultDesign,
  },
  {
    productCode: 'VP2',
    // productName: 'SAGA Platinum Visa',
    displayName: 'SAGA Platinum',
    productType: { type: 'SagaPlatinum' },
    ...sagaPlatinum,
    cardProvider: { type: 'MastercardDark' },
  },
  {
    productCode: 'VP3',
    // productName: 'Private Banking Visa',
    displayName: 'Private Banking',
    productType: { type: 'PrivateBanking' },
    ...privateBanking,
  },
  {
    productCode: 'VP4',
    // productName: 'SAGA Platinum Visa u/leg',
    displayName: 'SAGA Platinum',
    productType: { type: 'SagaPlatinum' },
    ...sagaPlatinum,
    cardProvider: { type: 'VisaPlatinum' },
  },
  {
    productCode: '069',
    // productName: 'SAGA Platinum Mastercard',
    displayName: 'SAGA Platinum',
    productType: { type: 'SagaPlatinum' },
    ...sagaPlatinum,
  },
  {
    productCode: 'VP5',
    // productName: 'Private Banking Visa u/leg',
    displayName: 'Private Banking',
    productType: { type: 'PrivateBanking' },
    ...privateBanking,
  },
  {
    productCode: '080',
    // productName: 'Private Banking Mastercard',
    displayName: 'Private Banking',
    productType: { type: 'PrivateBanking' },
    ...privateBanking,
    cardProvider: { type: 'MastercardDark' },
  },
  {
    productCode: 'VX1',
    displayName: 'Mitt første kort',
    ...myFirst,
  },
  {
    productCode: 'VX3',
    displayName: 'Ungdomskort',
    ...youth,
  },
  {
    productCode: 'VX4',
    // productName: 'Mitt første kort u/leg',
    displayName: 'Mitt første kort',
    productType: { type: 'Intro' },
    ...myFirst,
  },
  {
    productCode: 'VX5',
    // productName: 'Ungdomskortet u/leg',
    displayName: 'Ungdomskort',
    productType: { type: 'Intro' },
    ...youth,
  },
  {
    productCode: '096',
    displayName: 'DNB Mastercard',
    ...gold,
    cardProvider: { type: 'Mastercard' },
  },
  {
    productCode: '044',
    // productName: 'Hvitt Mastercard',
    displayName: 'Student',
    ...young,
    paymentType: null,
  },
  {
    productCode: '043',
    displayName: 'Pluss Mastercard',
    productType: { type: 'Pluss' },
    ...pluss,
    cardProvider: { type: 'Mastercard' },
  },
  {
    productCode: '098',
    // productName: 'SAGA Gull Mastercard',
    displayName: 'SAGA Gull',
    productType: { type: 'SagaGold' },
    ...saga,
  },
  {
    productCode: '074',
    // productName: 'SAGA Platinum Mastercard',
    displayName: 'SAGA Platinum',
    productType: { type: 'SagaPlatinum' },
    ...sagaPlatinum,
    paymentType: null,
  },
  {
    productCode: '062',
    // productName: 'Private Banking Mastercard',
    displayName: 'Private Banking',
    productType: { type: 'PrivateBanking' },
    ...privateBanking,
    paymentType: null,
  },
  {
    productCode: 'BK1',
    displayName: 'Bedriftskort (småkjøpskort)',
    productType: { type: 'Bedrift' },
    ...businessNoVisa,
    cardProvider: null,
  },
  {
    productCode: 'BP1',
    displayName: 'Bedriftskort (småkjøpskort)',
    productType: { type: 'Bedrift' },
    ...businessNoVisa,
    cardProvider: null,
  },
  {
    productCode: 'VB1',
    displayName: 'Bedriftskort med Visa',
    ...businessWithVisa,
  },
  {
    productCode: 'VB2',
    displayName: 'Visa Business',
    ...businessWithVisa,
  },
  {
    productCode: 'VB5',
    displayName: 'Bedriftskort med Visa',
    productType: { type: 'Bedrift' },
    ...businessWithVisa,
    paymentType: null,
  },
  {
    productCode: 'P101',
    // productName: '?',
    displayName: 'Black Mastercard',
    ...mcBlack,
    paymentType: null,
  },
  {
    productCode: 'VO3',
    displayName: 'SBanken Visa',
    ...sbankenVisa,
  },
  {
    productCode: 'VS8',
    displayName: 'SBanken et Konsept fra DNB',
    ...sbankenVisa,
  },
  {
    productCode: 'P103',
    displayName: 'SBanken et konsept fra DNB',
    ...sbankenMastercard,
  },
]

export default cardData
