import {
  BankAxeptOrCreditType,
  CardProduct,
  CardType,
  ProductType,
} from '../types'
import {
  defaultDesign,
  pluss,
  young,
  myFirst,
  youth,
  gold,
  saga,
  sagaPlatinum,
  privateBanking,
  mcBlack,
  businessNoVisa,
  businessWithVisa,
  sbankenMastercard,
  sbankenVisa,
} from './CardDesigns'

const cardData: CardProduct[] = [
  {
    productCode: 'NK1',
    productName: 'DNB Kortet',
    displayName: 'DNB Kortet',
    cardDesign: defaultDesign,
    cardType: CardType.None,
    productType: ProductType.None,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'NK4',
    productName: 'DNB Kortet',
    displayName: 'DNB Kortet',
    cardDesign: defaultDesign,
    cardType: CardType.None,
    productType: ProductType.None,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'NK5',
    productName: 'DNB Kortet',
    displayName: 'DNB Kortet',
    cardDesign: defaultDesign,
    cardType: CardType.None,
    productType: ProductType.None,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VE1',
    productName: 'DNB Electron',
    displayName: 'DNB Electron',
    cardDesign: defaultDesign,
    cardType: CardType.Visa,
    productType: ProductType.None,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VE2',
    productName: 'DNB Electron u/leg',
    displayName: 'DNB Electron',
    cardDesign: defaultDesign,
    cardType: CardType.Visa,
    productType: ProductType.None,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VG1',
    productName: 'SAGA Gull Visa',
    displayName: 'SAGA Gull',
    cardDesign: saga,
    cardType: CardType.Visa,
    productType: ProductType.Saga,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VG4',
    productName: 'SAGA Gull Visa u/leg',
    displayName: 'SAGA Gull',
    cardDesign: saga,
    cardType: CardType.Visa,
    productType: ProductType.Saga,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: '053',
    productName: 'SAGA Gull Mastercard',
    displayName: 'SAGA Gull',
    cardDesign: saga,
    cardType: CardType.Mastercard,
    productType: ProductType.Saga,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VK2',
    productName: 'DNB Visa',
    displayName: 'DNB Visa',
    cardDesign: defaultDesign,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VK4',
    productName: 'DNB Visa',
    displayName: 'DNB Visa',
    cardDesign: defaultDesign,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: '084',
    productName: 'Pluss Mastercard(leve)',
    displayName: 'Pluss Mastercard',
    cardDesign: pluss,
    productType: ProductType.Pluss,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VL1',
    productName: 'Sølv Visa',
    displayName: 'Pluss Visa',
    cardDesign: pluss,
    productType: ProductType.Pluss,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VL2',
    productName: 'Hvitt Visa',
    displayName: 'Hvitt kort',
    cardDesign: young,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VL3',
    productName: 'Sølv Visa',
    displayName: 'Pluss Visa',
    cardDesign: pluss,
    productType: ProductType.Pluss,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VL4',
    productName: 'DNB Visa u/leg',
    displayName: 'DNB Visa',
    cardDesign: defaultDesign,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VL6',
    productName: 'Hvitt Visa u/leg',
    displayName: 'Hvitt kort',
    cardDesign: young,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: '085',
    productName: 'Ung Mastercard(student)',
    displayName: 'Ung Mastercard',
    cardDesign: young,
    productType: ProductType.None,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VO1',
    productName: 'DNB Visa Online',
    displayName: 'DNB Visa Online',
    cardDesign: defaultDesign,
    cardType: CardType.Visa,
    productType: ProductType.None,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VP2',
    productName: 'SAGA Platinum Visa',
    displayName: 'SAGA Platinum',
    cardDesign: sagaPlatinum,
    productType: ProductType.Saga,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VP3',
    productName: 'Private Banking Visa',
    displayName: 'Private Banking',
    cardDesign: privateBanking,
    productType: ProductType.PrivateBanking,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VP4',
    productName: 'SAGA Platinum Visa u/leg',
    displayName: 'SAGA Platinum',
    cardDesign: sagaPlatinum,
    productType: ProductType.Saga,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: '069',
    productName: 'SAGA Platinum Mastercard',
    displayName: 'SAGA Platinum',
    cardDesign: sagaPlatinum,
    productType: ProductType.Saga,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VP5',
    productName: 'Private Banking Visa u/leg',
    displayName: 'Private Banking',
    cardDesign: privateBanking,
    productType: ProductType.PrivateBanking,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: '080',
    productName: 'Private Banking Mastercard',
    displayName: 'Private Banking',
    cardDesign: privateBanking,
    productType: ProductType.PrivateBanking,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VX1',
    productName: 'Mitt første kort',
    displayName: 'Mitt første kort',
    cardDesign: myFirst,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'VX3',
    productName: 'Ungdomskortet',
    displayName: 'Ungdomskort',
    cardDesign: youth,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VX4',
    productName: 'Mitt første kort u/leg',
    displayName: 'Mitt første kort',
    cardDesign: myFirst,
    productType: ProductType.Intro,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VX5',
    productName: 'Ungdomskortet u/leg',
    displayName: 'Ungdomskort',
    cardDesign: youth,
    productType: ProductType.Intro,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: '096',
    productName: 'DNB Mastercard',
    displayName: 'DNB Mastercard',
    cardDesign: gold,
    productType: ProductType.None,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: '044',
    productName: 'Hvitt Mastercard',
    displayName: 'Student',
    cardDesign: young,
    productType: ProductType.None,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: '043',
    productName: 'Sølv MasterCard',
    displayName: 'Pluss Mastercard',
    cardDesign: pluss,
    productType: ProductType.Pluss,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: '098',
    productName: 'SAGA Gull Mastercard',
    displayName: 'SAGA Gull',
    cardDesign: saga,
    productType: ProductType.Saga,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: '074',
    productName: 'SAGA Platinum Mastercard',
    displayName: 'SAGA Platinum',
    cardDesign: sagaPlatinum,
    productType: ProductType.Saga,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: '062',
    productName: 'Private Banking Mastercard',
    displayName: 'Private Banking',
    cardDesign: privateBanking,
    productType: ProductType.PrivateBanking,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'BK1',
    productName: 'Bedriftskort (småkjøpskort)',
    displayName: 'Bedriftskort (småkjøpskort)',
    cardDesign: businessNoVisa,
    productType: ProductType.Bedrift,
    cardType: CardType.None,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'BP1',
    productName: 'Bedriftskort (småkjøpskort)',
    displayName: 'Bedriftskort (småkjøpskort)',
    cardDesign: businessNoVisa,
    productType: ProductType.Bedrift,
    cardType: CardType.None,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VB1',
    productName: 'Bedriftskort med Visa',
    displayName: 'Bedriftskort med Visa',
    cardDesign: businessWithVisa,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VB2',
    productName: 'Visa Business',
    displayName: 'Visa Business',
    cardDesign: businessWithVisa,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VB5',
    productName: 'Bedriftskort med Visa',
    displayName: 'Bedriftskort med Visa',
    cardDesign: businessWithVisa,
    productType: ProductType.Business,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.None,
  },
  {
    productCode: 'P101',
    productName: '?',
    displayName: 'Black Mastercard',
    cardDesign: mcBlack,
    productType: ProductType.None,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.None,
  },

  {
    productCode: 'V03',
    productName: 'SBanken Visa',
    displayName: 'SBanken Visa',
    cardDesign: sbankenVisa,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'VS8',
    productName: 'SBanken et konsept fra DNB',
    displayName: 'SBanken et Konsept fra DNB',
    cardDesign: sbankenVisa,
    productType: ProductType.None,
    cardType: CardType.Visa,
    bankAxept: BankAxeptOrCreditType.BankAxept,
  },
  {
    productCode: 'P103',
    productName: 'SBanken et konsept fra DNB',
    displayName: 'SBanken et konsept fra DNB',
    cardDesign: sbankenMastercard,
    productType: ProductType.None,
    cardType: CardType.Mastercard,
    bankAxept: BankAxeptOrCreditType.Credit,
  },
]

export default cardData
