/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Library Index layout to autogenerate all the components and extensions
 * Used by "prepareLayouts"
 */

import Layout from './layout/Layout'
export * from './layout/Layout'
export default Layout
