/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */
/**
 * Library Index template to autogenerate all the components and extensions
 * Used by "prepareTemplates"
 */
import Accordion from './accordion/Accordion';
import Anchor from './anchor/Anchor';
import AriaLive from './aria-live/AriaLive';
import Autocomplete from './autocomplete/Autocomplete';
import Avatar from './avatar/Avatar';
import Badge from './badge/Badge';
import Breadcrumb from './breadcrumb/Breadcrumb';
import Button from './button/Button';
import Card from './card/Card';
import Checkbox from './checkbox/Checkbox';
import CopyOnClick from './copy-on-click/CopyOnClick';
import CountryFlag from './country-flag/CountryFlag';
import DateFormat from './date-format/DateFormat';
import DatePicker from './date-picker/DatePicker';
import Dialog from './dialog/Dialog';
import Drawer from './drawer/Drawer';
import Dropdown from './dropdown/Dropdown';
import Flex from './flex/Flex';
import FormLabel from './form-label/FormLabel';
import FormStatus from './form-status/FormStatus';
import GlobalError from './global-error/GlobalError';
import GlobalStatus from './global-status/GlobalStatus';
import Grid from './grid/Grid';
import Heading from './heading/Heading';
import HeightAnimation from './height-animation/HeightAnimation';
import HelpButton from './help-button/HelpButton';
import Icon from './icon/Icon';
import IconPrimary from './icon-primary/IconPrimary';
import InfoCard from './info-card/InfoCard';
import Input from './input/Input';
import InputMasked from './input-masked/InputMasked';
import List from './list/List';
import ListFormat from './list-format/ListFormat';
import Logo from './logo/Logo';
import Modal from './modal/Modal';
import NumberFormat from './number-format/NumberFormat';
import Pagination from './pagination/Pagination';
import Popover from './popover/Popover';
import PortalRoot from './portal-root/PortalRoot';
import ProgressIndicator from './progress-indicator/ProgressIndicator';
import Radio from './radio/Radio';
import Section from './section/Section';
import Skeleton from './skeleton/Skeleton';
import SkipContent from './skip-content/SkipContent';
import Slider from './slider/Slider';
import Space from './space/Space';
import StepIndicator from './step-indicator/StepIndicator';
import Switch from './switch/Switch';
import Table from './table/Table';
import Tabs from './tabs/Tabs';
import Tag from './tag/Tag';
import TermDefinition from './term-definition/TermDefinition';
import Textarea from './textarea/Textarea';
import Timeline from './timeline/Timeline';
import ToggleButton from './toggle-button/ToggleButton';
import Tooltip from './tooltip/Tooltip';
import Upload from './upload/Upload';
import VisuallyHidden from './visually-hidden/VisuallyHidden';
export { Accordion, Anchor, AriaLive, Autocomplete, Avatar, Badge, Breadcrumb, Button, Card, Checkbox, CopyOnClick, CountryFlag, DateFormat, DatePicker, Dialog, Drawer, Dropdown, Flex, FormLabel, FormStatus, GlobalError, GlobalStatus, Grid, Heading, HeightAnimation, HelpButton, Icon, IconPrimary, InfoCard, Input, InputMasked, List, ListFormat, Logo, Modal, NumberFormat, Pagination, Popover, PortalRoot, ProgressIndicator, Radio, Section, Skeleton, SkipContent, Slider, Space, StepIndicator, Switch, Table, Tabs, Tag, TermDefinition, Textarea, Timeline, ToggleButton, Tooltip, Upload, VisuallyHidden, };
export declare const getComponents: () => {
    Accordion: typeof Accordion;
    Anchor: typeof Anchor;
    AriaLive: typeof AriaLive;
    Autocomplete: typeof Autocomplete;
    Avatar: {
        (localProps: import("./avatar/Avatar").AvatarProps & import("./space/types").SpacingProps): import("react/jsx-runtime").JSX.Element;
        Group: (localProps: import("./avatar/AvatarGroup").AvatarGroupProps & import("./space/types").SpacingProps) => import("react/jsx-runtime").JSX.Element;
    };
    Badge: typeof Badge;
    Breadcrumb: {
        (localProps: import("./breadcrumb/Breadcrumb").BreadcrumbProps & import("./space/types").SpacingProps): import("react/jsx-runtime").JSX.Element;
        Item: (localProps: import("./breadcrumb/BreadcrumbItem").BreadcrumbItemProps) => import("react/jsx-runtime").JSX.Element;
    };
    Button: typeof Button;
    Card: typeof Card;
    Checkbox: typeof Checkbox;
    CopyOnClick: ({ children, className, disabled, showCursor, copyContent, tooltipContent, ...props }: import("./copy-on-click/types").CopyOnClickAllProps) => import("react/jsx-runtime").JSX.Element;
    CountryFlag: (props: {
        iso?: string;
        size?: "auto" | "xx-small" | "x-small" | "small" | "medium" | "large" | "x-large";
        shape?: "round" | "square";
    } & Omit<import("./space/Space").SpaceAllProps, "size">) => import("react/jsx-runtime").JSX.Element;
    DateFormat: typeof DateFormat;
    DatePicker: typeof DatePicker;
    Dialog: typeof Dialog;
    Drawer: typeof Drawer;
    Dropdown: typeof Dropdown;
    Flex: typeof Flex;
    FormLabel: typeof FormLabel;
    FormStatus: typeof FormStatus;
    GlobalError: typeof GlobalError;
    GlobalStatus: typeof GlobalStatus;
    Grid: typeof Grid;
    Heading: typeof Heading;
    HeightAnimation: typeof HeightAnimation;
    HelpButton: typeof HelpButton;
    Icon: typeof Icon;
    IconPrimary: typeof IconPrimary;
    InfoCard: (localProps: import("./info-card/InfoCard").InfoCardAllProps) => import("react/jsx-runtime").JSX.Element;
    Input: ((props: import("./input/Input").InputProps) => React.JSX.Element) & {
        getValue: (props: import("./input/Input").InputProps) => any;
        hasValue: (value: string | number | null | undefined) => boolean;
    } & import("../shared/helpers/withComponentMarkers").ComponentMarkers;
    InputMasked: typeof InputMasked;
    List: typeof List;
    ListFormat: typeof ListFormat;
    Logo: typeof Logo;
    Modal: typeof Modal;
    NumberFormat: typeof NumberFormat;
    Pagination: import("./pagination/Pagination").PaginationComponent;
    Popover: typeof Popover;
    PortalRoot: typeof PortalRoot;
    ProgressIndicator: typeof ProgressIndicator;
    Radio: (({ ref, ...props }: import("./radio/Radio").RadioProps) => import("react/jsx-runtime").JSX.Element) & {
        Group: typeof import("./radio/RadioGroup").default;
        parseChecked: (state: string | boolean | null | undefined) => boolean;
    } & import("../shared/helpers/withComponentMarkers").ComponentMarkers;
    Section: typeof Section;
    Skeleton: typeof Skeleton;
    SkipContent: {
        (localProps: import("./skip-content/SkipContent").SkipContentAllProps): import("react/jsx-runtime").JSX.Element;
        Return: (localProps: import("./skip-content/SkipContent").SkipContentReturnProps) => import("react/jsx-runtime").JSX.Element;
    };
    Slider: typeof Slider;
    Space: typeof Space;
    StepIndicator: typeof StepIndicator;
    Switch: typeof Switch;
    Table: {
        (componentProps: import("./table/Table").TableAllProps): import("react/jsx-runtime").JSX.Element;
        ScrollView: typeof import("./table/TableScrollView").default;
    };
    Tabs: typeof Tabs;
    Tag: {
        (localProps: import("./tag/Tag").TagProps & import("./space/types").SpacingProps & Omit<React.HTMLProps<HTMLElement>, "onClick">): import("react/jsx-runtime").JSX.Element;
        Group: (localProps: import("./tag/TagGroup").TagGroupProps & import("./space/types").SpacingProps & Omit<React.HTMLProps<HTMLElement>, "label">) => import("react/jsx-runtime").JSX.Element;
    };
    TermDefinition: typeof TermDefinition;
    Textarea: (({ ref, ...props }: import("./textarea/Textarea").TextareaProps) => import("react/jsx-runtime").JSX.Element) & import("./textarea/Textarea").TextareaStaticProperties;
    Timeline: {
        (localProps: import("./timeline/Timeline").TimelineAllProps): import("react/jsx-runtime").JSX.Element;
        Item: (localProps: import("./timeline/TimelineItem").TimelineItemAllProps) => import("react/jsx-runtime").JSX.Element;
    };
    ToggleButton: import("./toggle-button/ToggleButton").ToggleButtonComponent;
    Tooltip: typeof Tooltip;
    Upload: {
        (localProps: import("./upload/types").UploadAllProps): import("react/jsx-runtime").JSX.Element;
        useUpload: typeof import("./upload/useUpload").default;
    };
    VisuallyHidden: (localProps: import("./visually-hidden/VisuallyHidden").VisuallyHiddenAllProps) => import("react/jsx-runtime").JSX.Element;
};
