/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Library Index line-title to autogenerate all the components and extensions
 * Used by "prepareLineTitles"
 */

import LineTitle from './line-title/LineTitle'
export * from './line-title/LineTitle'
export default LineTitle
