/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Library Index notification to autogenerate all the components and extensions
 * Used by "prepareNotifications"
 */

import Notification from './notification/Notification'
export * from './notification/Notification'
export default Notification
