/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Library Index toaster to autogenerate all the components and extensions
 * Used by "prepareToasters"
 */

import Toaster from './toaster/Toaster'
export * from './toaster/Toaster'
export { Toaster }
export { useToaster, toasterManager } from './toaster/Toaster'
export default Toaster
