import type { PropertiesTableProps } from '../../shared/types'

export const AiResponseProperties: PropertiesTableProps = {
  children: {
    doc: 'The markdown to render. Can be updated while the response is streaming.',
    type: 'string',
    status: 'optional',
  },
  parseIncompleteMarkdown: {
    doc: 'Close unfinished markdown (like `**bold` or an open code span) and hide unfinished links and images in the last block while streaming.',
    type: 'boolean',
    defaultValue: 'true',
    status: 'optional',
  },
  components: {
    doc: 'Override how a markdown element is rendered, keyed by its HTML tag name, e.g. `{ a: MyLink }`. Code blocks render `code` inside `pre` with a `language-*` class, and `pre` receives `code` and `language`.',
    type: 'object',
    status: 'optional',
  },
  allowedLinkPrefixes: {
    doc: 'URL prefixes allowed for links. Use `*` to allow any http(s), mailto and tel URL. Links that are not allowed are rendered as text.',
    type: 'Array<string>',
    defaultValue: "['*']",
    status: 'optional',
  },
  allowedImagePrefixes: {
    doc: 'URL prefixes allowed for images. Use `*` to allow any http(s) URL. Images that are not allowed are rendered as their alt text.',
    type: 'Array<string>',
    defaultValue: "['*']",
    status: 'optional',
  },
  defaultOrigin: {
    doc: 'Origin used to resolve relative link and image URLs before they are checked.',
    type: 'string',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiMessageProperties: PropertiesTableProps = {
  from: {
    doc: 'Who wrote the message. User messages are placed on the right. Defaults to the role of `message`, or `assistant`.',
    type: ['"user"', '"assistant"'],
    status: 'optional',
  },
  variant: {
    doc: 'Show the content in a bubble, or as plain content without background.',
    type: ['"bubble"', '"plain"'],
    defaultValue: '"bubble"',
    status: 'optional',
  },
  name: {
    doc: 'Name shown in the header, e.g. `You` or the name of the assistant.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  timestamp: {
    doc: 'Time shown in the header after the name, e.g. `15:23`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  avatar: {
    doc: 'Avatar shown in the header, e.g. an [Avatar](/uilib/components/avatar/) with `hasLabel`. It is hidden from screen readers, as the name is shown.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  aiGenerated: {
    doc: 'Show a tag telling that the content is generated by AI.',
    type: 'boolean',
    status: 'optional',
  },
  message: {
    doc: 'A message from the AI SDK (`UIMessage`). Its text parts are rendered, user text as written and assistant text as markdown. Reasoning parts are rendered as `Ai.Reasoning`, tool parts as `Ai.Tool`, and `source-url` parts as `Ai.Sources`. Used instead of `children`.',
    type: 'UIMessage',
    status: 'optional',
  },
  actions: {
    doc: 'Content shown below the message, e.g. `Ai.Actions`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  children: {
    doc: 'The content of the message.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiLoaderProperties: PropertiesTableProps = {
  label: {
    doc: 'Text for screen readers while waiting for the reply. Defaults to a translated text.',
    type: 'string',
    status: 'optional',
  },
  variant: AiMessageProperties.variant,
  name: AiMessageProperties.name,
  avatar: AiMessageProperties.avatar,
  timestamp: AiMessageProperties.timestamp,
}

export const AiActionsProperties: PropertiesTableProps = {
  children: {
    doc: 'One or more `Ai.Action`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiActionProperties: PropertiesTableProps = {
  label: {
    doc: 'Label used for the tooltip and for screen readers.',
    type: 'string',
    status: 'required',
  },
  icon: {
    doc: 'The icon to show.',
    type: 'React.ReactNode',
    status: 'required',
  },
  '[Button](/uilib/components/button/properties)': {
    doc: 'Other Button properties like `onClick` or `disabled` are supported.',
    type: 'Various',
    status: 'optional',
  },
}

export const AiPromptInputProperties: PropertiesTableProps = {
  variant: {
    doc: 'Use `default` for a multiline card with the send button below the text, or `compact` for a single line with round buttons.',
    type: ['"default"', '"compact"'],
    status: 'optional',
  },
  value: {
    doc: 'The text value. Use it together with `onChange` to control the value. Without it, the text is cleared after submit.',
    type: 'string',
    status: 'optional',
  },
  placeholder: {
    doc: 'Placeholder text. Defaults to a translated text.',
    type: 'string',
    status: 'optional',
  },
  label: {
    doc: 'Label for screen readers. Defaults to a translated text.',
    type: 'string',
    status: 'optional',
  },
  status: {
    doc: 'The status of the chat, e.g. `status` from `useChat`. While `submitted` or `streaming`, the send button becomes a stop button when `onStop` is given.',
    type: ['"ready"', '"submitted"', '"streaming"', '"error"'],
    status: 'optional',
  },
  characterCounter: {
    doc: 'Show a character counter with the given maximum number of characters. Text that is longer is not sent.',
    type: 'number',
    status: 'optional',
  },
  disabled: {
    doc: 'Disable the input and its buttons.',
    type: 'boolean',
    status: 'optional',
  },
  textareaProps: {
    doc: 'Properties forwarded to the [Textarea](/uilib/components/textarea/properties), e.g. `status` for an error message.',
    type: 'TextareaProps',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiPromptInputEvents: PropertiesTableProps = {
  onChange: {
    doc: 'Called when the text changes. Receives `{ value }`.',
    type: 'function',
    status: 'optional',
  },
  onSubmit: {
    doc: 'Called with the text when the user presses Enter or the send button. Receives `{ value, event }`. Empty text is not submitted. Shift+Enter adds a new line.',
    type: 'function',
    status: 'optional',
  },
  onStop: {
    doc: 'Called when the user presses the stop button.',
    type: 'function',
    status: 'optional',
  },
  onAttachmentClick: {
    doc: 'Called when the user presses the attachment button. The button is only shown when this is given.',
    type: 'function',
    status: 'optional',
  },
  onMicrophoneClick: {
    doc: 'Called when the user presses the microphone button. The button is only shown when this is given.',
    type: 'function',
    status: 'optional',
  },
}

export const AiSuggestionProperties: PropertiesTableProps = {
  suggestion: {
    doc: 'The suggested prompt. It is shown as the text, unless `children` is given, and is sent to `onClick`.',
    type: 'string',
    status: 'required',
  },
  variant: {
    doc: 'Use `chip` for a small round button, or `card` for a larger button with the icon above the text.',
    type: ['"chip"', '"card"'],
    defaultValue: '"chip"',
    status: 'optional',
  },
  icon: {
    doc: 'Icon shown before the text.',
    type: 'IconIcon',
    defaultValue: 'ai',
    status: 'optional',
  },
  children: {
    doc: 'Content shown instead of `suggestion`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiSuggestionEvents: PropertiesTableProps = {
  onClick: {
    doc: 'Called when the user presses the suggestion. Receives `{ suggestion, event }`.',
    type: 'function',
    status: 'optional',
  },
}

export const AiWelcomeProperties: PropertiesTableProps = {
  title: {
    doc: 'The heading, e.g. `Hello, Peter`.',
    type: 'React.ReactNode',
    status: 'required',
  },
  level: {
    doc: 'The heading level.',
    type: 'number',
    defaultValue: '2',
    status: 'optional',
  },
  children: {
    doc: 'Content shown below the heading, e.g. `Ai.Suggestions`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiConversationProperties: PropertiesTableProps = {
  label: {
    doc: 'Label of the conversation for screen readers. Defaults to a translated text.',
    type: 'string',
    status: 'optional',
  },
  children: {
    doc: 'The messages of the conversation.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiDateMarkerProperties: PropertiesTableProps = {
  date: {
    doc: 'The date, shown with the weekday, e.g. `mandag 2. februar 2026`.',
    type: ['Date', 'string', 'number'],
    status: 'optional',
  },
  children: {
    doc: 'Content shown instead of the formatted `date`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiDisclaimerProperties: PropertiesTableProps = {
  children: {
    doc: 'The disclaimer text.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiSourcesProperties: PropertiesTableProps = {
  sources: {
    doc: 'The sources to list, as `{ url, title }`.',
    type: 'Array<AiSource>',
    status: 'optional',
  },
  message: {
    doc: 'A message from the AI SDK (`UIMessage`). Its `source-url` parts are listed. Used instead of `sources`.',
    type: 'UIMessage',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiToolProperties: PropertiesTableProps = {
  part: {
    doc: 'A tool part from a `UIMessage` of the AI SDK. Its title, state and error are shown.',
    type: ['ToolUIPart', 'DynamicToolUIPart'],
    status: 'optional',
  },
  title: {
    doc: 'What the tool does, e.g. `Looking up your transactions`. Defaults to the `title` of `part`, or its tool name.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  state: {
    doc: 'The state of the tool call, like `input-available` or `output-available`. Defaults to the state of `part`.',
    type: [
      '"input-streaming"',
      '"input-available"',
      '"approval-requested"',
      '"approval-responded"',
      '"output-available"',
      '"output-error"',
      '"output-denied"',
    ],
    status: 'optional',
  },
  errorText: {
    doc: 'Error shown when the state is `output-error`. Defaults to the `errorText` of `part`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  children: {
    doc: 'Content shown below the status, e.g. the result of the tool.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiShimmerProperties: PropertiesTableProps = {
  children: {
    doc: 'The text to show with the shimmer, e.g. `Thinking …`.',
    type: 'React.ReactNode',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}

export const AiReasoningProperties: PropertiesTableProps = {
  part: {
    doc: 'A reasoning part from a `UIMessage` of the AI SDK. Its text and state are shown.',
    type: 'ReasoningUIPart',
    status: 'optional',
  },
  isStreaming: {
    doc: 'Whether the reasoning is still streaming. It is open while streaming and closes when done, unless the user has opened or closed it. Defaults to the state of `part`.',
    type: 'boolean',
    status: 'optional',
  },
  children: {
    doc: 'The reasoning, rendered as markdown. Defaults to the text of `part`.',
    type: 'string',
    status: 'optional',
  },
  '[Space](/uilib/layout/space/properties)': {
    doc: 'Spacing properties like `top` or `bottom` are supported.',
    type: ['string', 'object'],
    status: 'optional',
  },
}
