import type {
  ButtonHTMLAttributes,
  ElementType,
  FormEvent,
  HTMLAttributes,
  KeyboardEvent,
  MouseEvent,
  ReactNode,
} from 'react'
import type {
  ButtonClickEvent,
  ButtonProps,
} from '../../components/button/types'
import type { TextareaProps } from '../../components/textarea/types'
import type { IconIcon } from '../../components/icon/types'
import type { SpacingProps } from '../../shared/types'

export type AiResponseElement =
  | 'p'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'ul'
  | 'ol'
  | 'li'
  | 'blockquote'
  | 'hr'
  | 'pre'
  | 'code'
  | 'table'
  | 'thead'
  | 'tbody'
  | 'tr'
  | 'th'
  | 'td'
  | 'a'
  | 'img'
  | 'strong'
  | 'em'
  | 'del'
  | 'br'
  | 'input'

export type AiResponseComponents = Partial<
  Record<AiResponseElement, ElementType>
>

export type AiResponseProps = {
  /** The markdown to render. Can be updated while the response is streaming. */
  children?: string
  /**
   * Close unfinished markdown (like `**bold` or an open code span) and hide unfinished links and images in the last block while streaming.
   * Default: `true`
   */
  parseIncompleteMarkdown?: boolean
  /**
   * Override how a markdown element is rendered, keyed by its HTML tag name, e.g. `{ a: MyLink }`. Code blocks render `code` inside `pre` with a `language-*` class, and `pre` receives `code` and `language`.
   */
  components?: AiResponseComponents
  /**
   * URL prefixes allowed for links. Use `*` to allow any http(s), mailto and tel URL. Links that are not allowed are rendered as text.
   * Default: `['*']`
   */
  allowedLinkPrefixes?: Array<string>
  /**
   * URL prefixes allowed for images. Use `*` to allow any http(s) URL. Images that are not allowed are rendered as their alt text.
   * Default: `['*']`
   */
  allowedImagePrefixes?: Array<string>
  /** Origin used to resolve relative link and image URLs before they are checked. */
  defaultOrigin?: string
} & SpacingProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'children'>

export type AiMessageFrom = 'user' | 'assistant'

export type AiMessageProps = {
  /** Who wrote the message. User messages are placed on the right. Defaults to `assistant`. */
  from?: AiMessageFrom
  /** Unique DOM id used by the conversation scrolling and visibility hooks. */
  id?: string
  /**
   * Show the content in a bubble, or as plain content without background.
   * Default: `"bubble"`
   */
  variant?: 'bubble' | 'plain'
  /** Name shown in the header, e.g. `You` or the name of the assistant. */
  name?: ReactNode
  /** Time shown in the header after the name, e.g. `15:23`. */
  timestamp?: ReactNode
  /**
   * Avatar shown in the header, e.g. an [Avatar](/uilib/components/avatar/) with `hasLabel`. It is hidden from screen readers, as the name is shown.
   */
  avatar?: ReactNode
  /** Show a tag telling that the content is generated by AI. */
  aiGenerated?: boolean
  /**
   * Content shown below the message, e.g. `Ai.Actions`.
   */
  actions?: ReactNode
  /** The content of the message. */
  children?: ReactNode
} & SpacingProps &
  HTMLAttributes<HTMLDivElement>

export type AiLoaderProps = {
  /** Text for screen readers while waiting for the reply. Defaults to a translated text. */
  label?: string
} & Omit<AiMessageProps, 'from' | 'children' | 'aiGenerated' | 'actions'>

export type AiActionsProps = SpacingProps & HTMLAttributes<HTMLDivElement>

export type AiActionProps = {
  /** Label used for the tooltip and for screen readers. */
  label: string
} & Omit<ButtonProps, 'text' | 'children' | 'title' | 'tooltip'>

export type AiPromptInputSubmitEvent = {
  value: string
  event: FormEvent<HTMLFormElement> | KeyboardEvent<HTMLTextAreaElement>
}

export type AiPromptInputProps = {
  /**
   * Use `default` for a multiline card with the send button below the text, or `compact` for a single line with round buttons.
   */
  variant?: 'default' | 'compact'
  /** The text value. Use it together with `onChange` to control the value. Without it, the text is cleared after submit. */
  value?: string
  /** Placeholder text. Defaults to a translated text. */
  placeholder?: string
  /** Label for screen readers. Defaults to a translated text. */
  label?: string
  /**
   * Prevent submitting while a reply is pending or streaming. Shows a stop button when `onStop` is given.
   * Default: `false`
   */
  isBusy?: boolean
  /** Show a character counter with the given maximum number of characters. Text that is longer is not sent. */
  characterCounter?: number
  /** Disable the input and its buttons. */
  disabled?: boolean
  /** Properties forwarded to the [Textarea](/uilib/components/textarea/properties), e.g. `status` for an error message. */
  textareaProps?: Partial<TextareaProps>
  /**
   * Called when the text changes. Receives `{ value }`.
   */
  onChange?: (event: { value: string }) => void
  /**
   * Called with the text when the user presses Enter or the send button. Receives `{ value, event }`. Empty text is not submitted. Shift+Enter adds a new line.
   */
  onSubmit?: (event: AiPromptInputSubmitEvent) => void
  /** Called when the user presses the stop button. */
  onStop?: () => void
  /** Called when the user presses the attachment button. The button is only shown when this is given. */
  onAttachmentClick?: (args: ButtonClickEvent) => void
  /** Called when the user presses the microphone button. The button is only shown when this is given. */
  onMicrophoneClick?: (args: ButtonClickEvent) => void
} & SpacingProps &
  Omit<
    HTMLAttributes<HTMLFormElement>,
    'onChange' | 'onSubmit' | 'children' | 'placeholder'
  >

export type AiSuggestionsProps = SpacingProps &
  HTMLAttributes<HTMLDivElement>

export type AiSuggestionClickEvent = {
  suggestion: string
  event: MouseEvent<HTMLButtonElement | HTMLAnchorElement>
}

export type AiSuggestionProps = {
  /** The suggested prompt. It is shown as the text, unless `children` is given, and is sent to `onClick`. */
  suggestion: string
  /**
   * Use `chip` for a small round button, or `card` for a larger button with the icon above the text.
   * Default: `"chip"`
   */
  variant?: 'chip' | 'card'
  /**
   * Icon shown before the text.
   * Default: `ai`
   */
  icon?: IconIcon
  /** Content shown instead of `suggestion`. */
  children?: ReactNode
  /**
   * Called when the user presses the suggestion. Receives `{ suggestion, event }`.
   */
  onClick?: (event: AiSuggestionClickEvent) => void
} & SpacingProps &
  Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onClick' | 'children'>

export type AiWelcomeProps = {
  /** The heading, e.g. `Hello, Peter`. */
  title: ReactNode
  /**
   * The heading level.
   * Default: `2`
   */
  level?: 1 | 2 | 3 | 4 | 5 | 6
  /** Content shown below the heading, e.g. `Ai.Suggestions`. */
  children?: ReactNode
} & SpacingProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'title'>

export type AiConversationProps = {
  /** Label of the conversation for screen readers. Defaults to a translated text. */
  label?: string
  /**
   * Use `turn` to scroll a new message from the user near the top, and let the reply stream in below it. Use `end` to follow the end of the conversation while the reply streams in.
   * Default: `"turn"`
   */
  scrollBehavior?: 'turn' | 'end'
  /** Identifier used to scroll the conversation from elsewhere with `Ai.useConversation(id)`. */
  id?: string
  /** The messages of the conversation. */
  children?: ReactNode
} & SpacingProps &
  HTMLAttributes<HTMLDivElement>

export type AiDateMarkerProps = {
  /** The date, shown with the weekday, e.g. `mandag 2. februar 2026`. */
  date?: Date | string | number
  /** Content shown instead of the formatted `date`. */
  children?: ReactNode
} & SpacingProps &
  HTMLAttributes<HTMLDivElement>

export type AiDisclaimerProps = {
  /** The disclaimer text. */
  children?: ReactNode
} & SpacingProps &
  HTMLAttributes<HTMLDivElement>

export type AiSource = {
  url: string
  title?: string
}

export type AiSourcesProps = {
  /** The sources to list, as `{ url, title }`. */
  sources?: Array<AiSource>
} & SpacingProps &
  HTMLAttributes<HTMLDivElement>

export type AiToolStatus =
  | 'running'
  | 'awaiting'
  | 'done'
  | 'error'
  | 'canceled'

export type AiToolProps = {
  /** What the tool does, e.g. `Looking up your transactions`. */
  title?: ReactNode
  /** Display status of the tool. Defaults to `running`. */
  status?: AiToolStatus
  /** Error shown when the status is `error`. */
  errorText?: ReactNode
  /** Content shown below the status, e.g. the result of the tool. */
  children?: ReactNode
} & SpacingProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'title' | 'part'>

export type AiShimmerProps = {
  /** The text to show with the shimmer, e.g. `Thinking …`. */
  children?: ReactNode
} & SpacingProps &
  HTMLAttributes<HTMLSpanElement>

export type AiReasoningProps = {
  /** Whether the reasoning is still streaming. It is open while streaming and closes when done, unless the user has opened or closed it. */
  isStreaming?: boolean
  /** The reasoning, rendered as markdown. */
  children?: string
} & SpacingProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'part'>

export type AiConversationControls = {
  /** Scroll to the end and follow new content. */
  scrollToEnd: () => void
  /** Scroll to the start of the conversation. */
  scrollToStart: () => void
  /** Scroll to the message with the given id. Returns `false` when the message is not found. */
  scrollToMessage: (messageId: string) => boolean
}

export type AiConversationScrollState = {
  /** `true` when the conversation is scrolled to the start. */
  isAtStart: boolean
  /** `true` when the conversation is scrolled to the end. */
  isAtEnd: boolean
}

export type AiConversationVisibility = {
  /** The id of the message from the user that starts the turn the user is reading. Stays set when the message is scrolled above the view. */
  currentTurnId: string | null
  /** The ids of the messages that are visible, in the order they are shown. */
  visibleMessageIds: Array<string>
}
