/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Library Index progress to autogenerate all the components and patterns
 * Used by "prepareProgresss"
 */

import Progress from './progress/Progress'
export * from './progress/Progress'
export default Progress
