/**
 * ATTENTION: This file is auto generated by using "prepareTemplates".
 * Do not change the content!
 *
 */

/**
 * Main Index template to autogenerate all the libs
 *
 */

// import all the aviable components and patterns
import Button from './components/button/Button'
import Dropdown from './components/dropdown/Dropdown'
import FormLabel from './components/form-label/FormLabel'
import FormStatus from './components/form-status/FormStatus'
import Icon from './components/icon/Icon'
import IconPrimary from './components/icon-primary/IconPrimary'
import Input from './components/input/Input'
import InputMasked from './components/input-masked/InputMasked'
import LineTitle from './components/line-title/LineTitle'
import Logo from './components/logo/Logo'
import Modal from './components/modal/Modal'
import Notification from './components/notification/Notification'
import Slider from './components/slider/Slider'
import StepIndicator from './components/step-indicator/StepIndicator'
import Switch from './components/switch/Switch'
import Tabs from './components/tabs/Tabs'
import Anchor from './elements/Anchor'
import Blockquote from './elements/Blockquote'
import Code from './elements/Code'
import Dl from './elements/Dl'
import H1 from './elements/H1'
import H2 from './elements/H2'
import H3 from './elements/H3'
import H4 from './elements/H4'
import H5 from './elements/H5'
import H6 from './elements/H6'
import Hr from './elements/Hr'
import Img from './elements/Img'
import Lead from './elements/Lead'
import Link from './elements/Link'
import Ol from './elements/Ol'
import P from './elements/P'
import Table from './elements/Table'
import Textarea from './elements/Textarea'
import Ul from './elements/Ul'
import ActionNav from './patterns/action-nav/ActionNav'
import DescriptionList from './patterns/description-list/DescriptionList'
import FieldsetDescription from './patterns/fieldset-description/FieldsetDescription'
import Footer from './patterns/footer/Footer'
import Form from './patterns/form/Form'
import FormSummary from './patterns/form-summary/FormSummary'
import Grid from './patterns/grid/Grid'
import MainNav from './patterns/main-nav/MainNav'
import RangeSlider from './patterns/range-slider/RangeSlider'
import SummaryTable from './patterns/summary-table/SummaryTable'
import ViewTitle from './patterns/view-title/ViewTitle'

// define / export all the aviable components
export {
  Button,
  Dropdown,
  FormLabel,
  FormStatus,
  Icon,
  IconPrimary,
  Input,
  InputMasked,
  LineTitle,
  Logo,
  Modal,
  Notification,
  Slider,
  StepIndicator,
  Switch,
  Tabs,
  Anchor,
  Blockquote,
  Code,
  Dl,
  H1,
  H2,
  H3,
  H4,
  H5,
  H6,
  Hr,
  Img,
  Lead,
  Link,
  Ol,
  P,
  Table,
  Textarea,
  Ul,
  ActionNav,
  DescriptionList,
  FieldsetDescription,
  Footer,
  Form,
  FormSummary,
  Grid,
  MainNav,
  RangeSlider,
  SummaryTable,
  ViewTitle
}

export default {}
