/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const add_circled = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M8 11.111V4.89M11.111 8H4.89M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeMiterlimit={10}
      strokeLinecap="round"
    />
  </svg>
)

export default add_circled
