/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const arrow_right_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M2.25 12H22.5M15 19.5l7.5-7.5m0 0L15 4.5"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default arrow_right_medium
