/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const bankid_qr = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M1 8.778h6.222v1.555m3.111 0V15H15v-4.667h-1.556m-6.222 3.111V15m0-14v4.667h1.556m3.11 1.555H15M1 1h3.111v3.111H1V1Zm0 10.889h3.111V15H1v-3.111ZM11.889 1H15v3.111h-3.111V1Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default bankid_qr
