/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const bankid_qr_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M5.25 12.75h6v1.5m3 0v4.5h4.5v-4.5h-1.5m-6 3v1.5m0-13.5v4.5h1.5m3 1.5h3M.75 6V2.25a1.5 1.5 0 0 1 1.5-1.5H6m12 0h3.75a1.5 1.5 0 0 1 1.5 1.5V6m0 12v3.75a1.5 1.5 0 0 1-1.5 1.5H18m-12 0H2.25a1.5 1.5 0 0 1-1.5-1.5V18m4.5-12.75h3v3h-3v-3Zm0 10.5h3v3h-3v-3Zm10.5-10.5h3v3h-3v-3Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default bankid_qr_medium
