/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const bankid_mobile_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.75 20a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"
      fill="#000"
    />
    <path
      d="M15.5 5V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v20a1 1 0 0 0 1 1h11.5a1 1 0 0 0 1-1v-5"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M10 7.5h2.4m-2.4 7h2.4M10 12.077h2.4M19.6 7.5H22m-2.4 7H22m-2.4-4.846H22m-7.2 0h2.4m-2.4 2.423h2.4"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
    />
  </svg>
)

export default bankid_mobile_medium
