/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const bank = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M1 15h14M3.5 7.5v5h3v-5m3 0v5h3v-5M15 5H1l6.46-3.84a1 1 0 0 1 1.08 0L15 5Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default bank
