/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const bankid_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M.75 5.5h4.5m-4.5 13h4.5M.75 14h4.5m13.5-8.5h4.5m-4.5 13h4.5m-4.5-9h4.5m-13.5 0h4.5M9.75 14h4.5"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
    />
  </svg>
)

export default bankid_medium
