/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function brickwall(props) {
  return (
    <svg
      width={17}
      height={17}
      viewBox="0 0 17 17"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M15.6751 11.0758H1.26122M15.1764 5.92424H1.7699M8.49799 5.92424V11.0758M11.7703 11.0758L12.0794 16.2273M11.0491 0.772727L11.3582 5.92424M5.2794 11.0758L4.86728 16.2273M5.89758 0.772727L5.58849 5.92424M1.7699 5.92424L2.17875 1.7C2.20428 1.44592 2.32326 1.21038 2.51262 1.03905C2.70197 0.867718 2.9482 0.772809 3.20356 0.772727H13.7429C13.9982 0.772809 14.2445 0.867718 14.4338 1.03905C14.6232 1.21038 14.7421 1.44592 14.7677 1.7L16.1737 16.2273H0.772727L1.7699 5.92424Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default brickwall
