/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const broken_chain_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="m8.25 5.249-3-3m1.5 6h-1.5m6-4.5v-1.5m3 4.5h4.5c2.451 0 4.5 2.049 4.5 4.5s-2.049 4.5-4.5 4.5h-4.5m-9.53-4.334-2.652 2.652c-1.733 1.733-1.733 4.63 0 6.364 1.733 1.733 4.63 1.733 6.364 0l2.652-2.652"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default broken_chain_medium
