/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const camper_trailer_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M9.75 18.577c0 1.614-1.343 2.923-3 2.923s-3-1.309-3-2.923m6 0c0-1.614-1.343-2.923-3-2.923s-3 1.309-3 2.923m6 0h9m-15 0h-1.5c-.817 0-1.5-.666-1.5-1.462V3.962c0-.797.683-1.462 1.5-1.462h10.5c3.268 0 6 2.662 6 5.846v10.23m0 0h4.5m-15-13.153h-3.5c-.552 0-1 .436-1 .974v2.436c0 .538.448.975 1 .975h3.5m0-4.385h3.5c.552 0 1 .436 1 .974v2.436a.987.987 0 0 1-1 .975h-3.5m0-4.385v4.385"
    />
  </svg>
)
export default camper_trailer_medium
