/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const card_with_padlock_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M4.5 7.25a.75.75 0 0 0 0 1.5v-1.5Zm3.75 1.5a.75.75 0 0 0 0-1.5v1.5Zm-3.75 6.5a.75.75 0 0 0 0 1.5v-1.5Zm6 1.5a.75.75 0 0 0 0-1.5v1.5Zm.5 3.5a.75.75 0 0 0 0-1.5v1.5Zm3.25-4v-.75a.75.75 0 0 0-.75.75h.75Zm9 0H24a.75.75 0 0 0-.75-.75v.75Zm0 7V24a.75.75 0 0 0 .75-.75h-.75Zm-9 0h-.75c0 .414.336.75.75.75v-.75ZM22.5 11a.75.75 0 0 0 1.5 0h-1.5ZM2.75 5.25h18.5v-1.5H2.75v1.5ZM1.5 17.5v-11H0v11h1.5Zm3-8.75h3.75v-1.5H4.5v1.5Zm0 8h6v-1.5h-6v1.5Zm6.5 2H2.75v1.5H11v-1.5ZM0 17.5a2.75 2.75 0 0 0 2.75 2.75v-1.5c-.69 0-1.25-.56-1.25-1.25H0ZM21.25 5.25c.69 0 1.25.56 1.25 1.25H24a2.75 2.75 0 0 0-2.75-2.75v1.5Zm-18.5-1.5A2.75 2.75 0 0 0 0 6.5h1.5c0-.69.56-1.25 1.25-1.25v-1.5Zm19.75 12.5v7H24v-7h-1.5Zm.75 6.25h-9V24h9v-1.5Zm-8.25.75v-7h-1.5v7H15ZM16.75 15a2 2 0 0 1 2-2v-1.5a3.5 3.5 0 0 0-3.5 3.5h1.5Zm2-2a2 2 0 0 1 2 2h1.5a3.5 3.5 0 0 0-3.5-3.5V13Zm-4.5 4H16v-1.5h-1.75V17Zm1-2v1.25h1.5V15h-1.5Zm.75 2h5.5v-1.5H16V17Zm5.5 0h1.75v-1.5H21.5V17Zm-.75-2v1.25h1.5V15h-1.5Zm1.75-8.5V11H24V6.5h-1.5Z"
      fill="#000"
    />
    <circle cx={18.75} cy={19.75} r={1} fill="#000" />
  </svg>
)

export default card_with_padlock_medium
