/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const charger = (props) => (
  <svg
    width={16}
    height={17}
    viewBox="0 0 16 17"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M4 .75v3m4-3v3m-2 7v2c0 2.833 4 2.833 4 0 0-2.5 4-2.5 4 0v3m-9-9h2m1-3h1a1 1 0 0 1 1 1c0 3.5-.36 5.896-3.919 5.896-3.788 0-4-2.396-4-6 0-.149.024-.416.212-.603A1 1 0 0 1 3 3.75h1m4 0H4"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default charger
