/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function charger_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M6 0.75V5.25M12 0.75V5.25M9 15.75V18.75C9 23 15 23 15 18.75C15 15 21 15 21 18.75V23.25M7.5 8.25H10.5M6 5.25H4.49996C4.10213 5.25 3.7206 5.40804 3.4393 5.68934C3.15799 5.97064 3.12207 6.37109 3.12207 6.5938C3.12207 12 3.4393 15.5938 9.12207 15.5938C14.4585 15.5938 14.9989 12 15 6.75C15 6.36328 14.8419 5.97064 14.5606 5.68934C14.2793 5.40804 13.8978 5.25 13.5 5.25H12M6 5.25H12"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default charger_medium
