/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chip(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M5.5 1V2.5M10.5 1V2.5M5.5 15V13.5M10.5 15V13.5M15 10.5H13.5M15 5.5H13.5M1 10.5H2.5M1 5.5H2.5M2.5 5.5V3.5C2.5 2.94772 2.94772 2.5 3.5 2.5H5.5M2.5 5.5V10.5M2.5 10.5V12.5C2.5 13.0523 2.94772 13.5 3.5 13.5H5.5M5.5 13.5H10.5M10.5 13.5H12.5C13.0523 13.5 13.5 13.0523 13.5 12.5V10.5M13.5 10.5V5.5M13.5 5.5V3.5C13.5 2.94772 13.0523 2.5 12.5 2.5H10.5M10.5 2.5H5.5M5.85714 5H10.1429C10.6162 5 11 5.38376 11 5.85714V10.1429C11 10.6162 10.6162 11 10.1429 11H5.85714C5.38376 11 5 10.6162 5 10.1429V5.85714C5 5.38376 5.38376 5 5.85714 5Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default chip
