/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function chip_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M12 1.5V3.75M6.75 1.5V3.75M17.25 1.5V3.75M12 22.5V20.25M6.75 22.5V20.25M17.25 22.5V20.25M22.5 12H20.25M22.5 17.25H20.25M22.5 6.75H20.25M1.5 12H3.75M1.5 17.25H3.75M1.5 6.75H3.75M3.75 6.75V5.25C3.75 4.42157 4.42157 3.75 5.25 3.75H6.75M3.75 6.75V12M3.75 12V17.25M3.75 17.25V18.75C3.75 19.5784 4.42157 20.25 5.25 20.25H6.75M6.75 20.25H12M12 20.25H17.25M17.25 20.25H18.75C19.5784 20.25 20.25 19.5784 20.25 18.75V17.25M20.25 17.25V12M20.25 12V6.75M20.25 6.75V5.25C20.25 4.42157 19.5784 3.75 18.75 3.75H17.25M17.25 3.75H12M12 3.75H6.75M8.25 6.75H15.75C16.5784 6.75 17.25 7.42157 17.25 8.25V15.75C17.25 16.5784 16.5784 17.25 15.75 17.25H8.25C7.42157 17.25 6.75 16.5784 6.75 15.75V8.25C6.75 7.42157 7.42157 6.75 8.25 6.75Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default chip_medium
