/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const cookie = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13.6 6.127a2.333 2.333 0 0 1-2.335-2.348 2.314 2.314 0 0 1-2.511.2A2.334 2.334 0 0 1 7.716 1a6.998 6.998 0 0 0-6.434 5.03 7.006 7.006 0 0 0 2.707 7.707 6.998 6.998 0 0 0 10.672-3.586 7.005 7.005 0 0 0 .005-4.29 2.309 2.309 0 0 1-1.067.266Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M5.5 8a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M8 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM12 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"
      fill="#000"
    />
  </svg>
)

export default cookie
