/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function document_txt_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M13 23H2.5C1.94772 23 1.5 22.5523 1.5 22V2C1.5 1.44772 1.94772 1 2.5 1H12.5362C12.8304 1 13.1096 1.12951 13.2996 1.35406L18.2634 7.22036C18.4162 7.40092 18.5 7.62979 18.5 7.86631V9"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.2617 12H5.96173V13.2H7.86173V19H9.36173V13.2H11.2617V12Z"
        fill="black"
      />
      <path
        d="M17.6078 19L15.5878 15.4L17.5178 12H15.8678L14.8178 14.11L13.8078 12H12.0978L14.0178 15.5L12.0078 19H13.7278L14.7978 16.86L15.8278 19H17.6078Z"
        fill="black"
      />
      <path
        d="M23.6539 12H18.3539V13.2H20.2539V19H21.7539V13.2H23.6539V12Z"
        fill="black"
      />
    </svg>
  )
}

export default document_txt_medium
