/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const document_pdf_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13 23H2.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h10.036a1 1 0 0 1 .764.354l4.963 5.866a1 1 0 0 1 .237.646V9"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M8.722 12h-2.51v7h1.5v-2.7h1.01c1.51 0 2.39-.79 2.39-2.15 0-1.36-.88-2.15-2.39-2.15Zm-.24 3.1h-.77v-1.9h.77c.76 0 1.11.3 1.11.95 0 .65-.35.95-1.11.95ZM14.258 12h-1.85v7h1.85c1.97 0 3.15-1.27 3.15-3.5s-1.18-3.5-3.15-3.5Zm-.14 5.8h-.21v-4.6h.21c1.15 0 1.76.75 1.76 2.3 0 1.55-.61 2.3-1.76 2.3ZM23.214 13.2V12h-4.41v7h1.5v-2.89h2.51v-1.2h-2.51V13.2h2.91Z"
      fill="#000"
    />
  </svg>
)

export default document_pdf_medium
