/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const document_word_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13 23H2.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h10.036a1 1 0 0 1 .764.354l4.963 5.866a1 1 0 0 1 .237.646V9"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M8.062 12h-1.85v7h1.85c1.97 0 3.15-1.27 3.15-3.5s-1.18-3.5-3.15-3.5Zm-.14 5.8h-.21v-4.6h.21c1.15 0 1.76.75 1.76 2.3 0 1.55-.61 2.3-1.76 2.3Zm6.886-5.9c1.68 0 2.58 1.26 2.58 3.6s-.9 3.6-2.58 3.6c-1.68 0-2.58-1.26-2.58-3.6s.9-3.6 2.58-3.6Zm0 5.9c.67 0 1.05-.83 1.05-2.3 0-1.47-.38-2.3-1.05-2.3s-1.05.83-1.05 2.3c0 1.47.38 2.3 1.05 2.3Zm5.146-2.3c0-1.39.48-2.3 1.23-2.3.64 0 .98.38 1.08 1.21l1.39-.49c-.21-1.28-1.09-2.02-2.4-2.02-1.76 0-2.83 1.36-2.83 3.6 0 2.28 1.04 3.6 2.83 3.6 1.23 0 2.01-.56 2.43-1.75l-1.25-.69c-.25.87-.54 1.14-1.23 1.14-.8 0-1.25-.83-1.25-2.3Z"
      fill="#000"
    />
  </svg>
)

export default document_word_medium
