/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const document_warning = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M10.59 3.5 8.618 1.328A1 1 0 0 0 7.878 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h1m7.5-3.273v-2m4.36 3.405a1.258 1.258 0 0 1-.059 1.256c-.119.187-.286.342-.484.449a1.363 1.363 0 0 1-.648.163H7.331c-.227 0-.45-.056-.649-.163a1.313 1.313 0 0 1-.484-.449 1.262 1.262 0 0 1-.057-1.256L9.31 7.714c.11-.215.28-.395.49-.521a1.361 1.361 0 0 1 1.4 0c.21.126.38.306.49.52l3.17 5.42Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M10.512 12.86a.528.528 0 1 0 0 1.055.528.528 0 0 0 0-1.056Z"
      fill="#000"
    />
  </svg>
)

export default document_warning
