/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const e_scooter = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <g clipPath="url(#e_scooter_svg__a)">
      <path
        fill="#000"
        fillRule="evenodd"
        d="M13.647 10.593a2.61 2.61 0 0 1 1.15.165.75.75 0 1 0 .537-1.401 4.117 4.117 0 0 0-1.808-.26c-1.232.1-2.29.734-2.994 1.653H6.214a4.154 4.154 0 0 0-3.4-1.43c-.85.05-1.627.35-2.26.823a.75.75 0 1 0 .898 1.201c.404-.301.9-.494 1.45-.526a2.648 2.648 0 0 1 2.315 1.088.748.748 0 0 0 .566.312.74.74 0 0 0 .217.032h4.9a.748.748 0 0 0 .561-.253.742.742 0 0 0 .132-.152c.464-.71 1.203-1.184 2.054-1.252Zm-10.59 2.24a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1Zm-2 .5a2 2 0 1 1 4 0 2 2 0 0 1-4 0Zm12.693-.5a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1Zm-2 .5a2 2 0 1 1 4 0 2 2 0 0 1-4 0Z"
        clipRule="evenodd"
      />
      <path
        stroke="#000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={1.5}
        d="m12.5 9.5-1-8M10 1h3"
      />
    </g>
    <defs>
      <clipPath id="e_scooter_svg__a">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
)
export default e_scooter
