/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const e_scooter_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M21.291 21.061a1.469 1.469 0 1 0 0-2.938 1.469 1.469 0 0 0 0 2.938Zm-18.612 0a1.469 1.469 0 1 0 0-2.938 1.469 1.469 0 0 0 0 2.938ZM.75 16.2a3.917 3.917 0 0 1 5.85 2.9h10.8a3.917 3.917 0 0 1 5.847-2.9M20 15.5 17.806 2.939m-2.393 0h4.898"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default e_scooter_medium
