/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const exclamation_circled = (props) => (
  <svg
    width={17}
    height={17}
    viewBox="0 0 17 17"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1.593 8.5a6.907 6.907 0 1 1 13.814 0 6.907 6.907 0 0 1-13.814 0ZM8.5 0a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17Zm.797 4.563a.797.797 0 0 0-1.594 0v4.964a.797.797 0 1 0 1.594 0V4.563Zm-1.178 6.791a.684.684 0 1 1 .761 1.138.684.684 0 0 1-.76-1.138Z"
      fill="#000"
    />
  </svg>
)

export default exclamation_circled
