/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const exclamation_circled = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 17 17"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeMiterlimit={10}
      strokeWidth={1.5}
      d="M8.5 9.527V4.563M8.5 12h.024m7.68-3.5a7.703 7.703 0 1 1-15.407 0 7.703 7.703 0 0 1 15.406 0Z"
    />
  </svg>
)
export default exclamation_circled
