/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function facebook_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M18 8.00689H13.8303V6.09773C13.775 5.53519 14.2295 4.99525 14.8091 4.99822H17.7455V1H13.5073C9.66069 1 8.93638 3.99867 8.93638 5.85784V8.00689H6V12.0051H8.93638V23H13.8303V12.0051H17.5987L18 8.00689Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default facebook_medium
