/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const file_rejected = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m9.59 2.5-.97-1.146A1 1 0 0 0 7.856 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h2m4.688-3.188 1.562-1.562m0 0 1.563-1.563M10.25 10.25l1.563 1.563M10.25 10.25 8.687 8.687m6.483 1.563a4.92 4.92 0 1 1-9.84 0 4.92 4.92 0 0 1 9.84 0Z"
    />
  </svg>
)
export default file_rejected
