/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function file_rejected_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M5 5H10.5M5 8H13.5M5 19H8.5M18.5 9V7.86631C18.5 7.62979 18.4162 7.40092 18.2634 7.22037L13.2996 1.35406C13.1096 1.12951 12.8304 1 12.5362 1L2.5 1.00001C1.94771 1.00001 1.5 1.44773 1.5 2.00001V22C1.5 22.5523 1.94772 23 2.5 23H11M16.125 19.875L18 18M18 18L19.875 16.125M18 18L19.875 19.875M18 18L16.125 16.125M23.2001 17.95C23.2001 20.8495 20.8496 23.2 17.9501 23.2C15.0506 23.2 12.7001 20.8495 12.7001 17.95C12.7001 15.0505 15.0506 12.7 17.9501 12.7C20.8496 12.7 23.2001 15.0505 23.2001 17.95Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default file_rejected_medium
