/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function file_xml_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M13 23H2.5C1.94772 23 1.5 22.5523 1.5 22V2C1.5 1.44772 1.94772 1 2.5 1H12.5362C12.8304 1 13.1096 1.12951 13.2996 1.35406L18.2634 7.22036C18.4162 7.40092 18.5 7.62979 18.5 7.86631V9"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.6 19L9.58 15.4L11.51 12H9.86L8.81 14.11L7.8 12H6.09L8.01 15.5L6 19H7.72L8.79 16.86L9.82 19H11.6Z"
        fill="black"
      />
      <path
        d="M17.4961 12.01H15.7161L14.9761 15.42L14.2361 12H12.4961V19H13.8661V15.36L14.3861 17.57H15.5961L16.0661 15.35V19.01H17.4961V12.01Z"
        fill="black"
      />
      <path
        d="M20.4922 17.8V12H18.9922V19H23.5922V17.8H20.4922Z"
        fill="black"
      />
    </svg>
  )
}

export default file_xml_medium
