/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const file_txt_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M13 23H2.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h10.036a1 1 0 0 1 .764.354l4.963 5.866a1 1 0 0 1 .237.646V9"
    />
    <path
      fill="#000"
      d="M11.262 12h-5.3v1.2h1.9V19h1.5v-5.8h1.9V12Zm6.346 7-2.02-3.6 1.93-3.4h-1.65l-1.05 2.11-1.01-2.11h-1.71l1.92 3.5-2.01 3.5h1.72l1.07-2.14 1.03 2.14h1.78Zm6.046-7h-5.3v1.2h1.9V19h1.5v-5.8h1.9V12Z"
    />
  </svg>
)
export default file_txt_medium
