/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const fund_in = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M1 15h.933M15 15h-.933M6.6 7.067a.467.467 0 01.467-.467h1.866a.467.467 0 01.467.467V15M15 3.8V1m0 0h-2.8M15 1l-3.142 3.142a1.4 1.4 0 01-1.392.351l-3.552-.95a1.4 1.4 0 00-1.352.363l-3.629 3.63m0 7.464h2.8m-2.8 0v-.467m2.8.467H6.6m-1.867 0v-.467M6.6 15h2.8m-2.8 0v-.467M9.4 15h1.867m0 0h2.8m-2.8 0V7.689a.467.467 0 01.466-.467H13.6a.467.467 0 01.467.467V15M1.156 10.8h4.666m-1.555 1.556L5.822 10.8m0 0L4.267 9.244"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)
export default fund_in
