/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const grabber_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M1 9h22M1 12h22M1 15h22"
      stroke="#000"
      strokeWidth={1.56}
      strokeLinecap="round"
    />
  </svg>
)

export default grabber_medium
