/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const hamburger_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeWidth={1.5}
      d="M.75 21h22.5M.75 12h22.5M.75 3h22.5"
    />
  </svg>
)
export default hamburger_medium
