/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const hanger_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 11.75a10.763 10.763 0 0 1 10.428 7.023 1.55 1.55 0 0 1-.2 1.353 1.433 1.433 0 0 1-1.176.624H2.95a1.432 1.432 0 0 1-1.175-.624 1.543 1.543 0 0 1-.2-1.353A10.763 10.763 0 0 1 12 11.75Zm0 0v-4a2.25 2.25 0 1 1 2.25-2.25"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default hanger_medium
