/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const kid_number = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13.749 2.5H2.25a1 1 0 0 0-1 1v9.045a1 1 0 0 0 1 1h11.499a1 1 0 0 0 1-1V3.5a1 1 0 0 0-1-1Z"
      stroke="#000"
      strokeWidth={1.5}
    />
    <path
      d="M6.66 5.901H5.597l-1.253 1.67V5.9h-.89v4.157h.89V8.793l.184-.231 1.01 1.496H6.66L5.057 7.903 6.66 5.9Zm.651 4.157h.89V5.901h-.89v4.157Zm3.119-4.157H9.211v4.157h1.217c1.295 0 2.12-.825 2.12-2.078S11.724 5.9 10.43 5.9Zm-.084 3.445h-.243V6.614h.243c.814 0 1.295.534 1.295 1.366 0 .831-.481 1.366-1.295 1.366Z"
      fill="#000"
    />
  </svg>
)

export default kid_number
