/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const loan_out = (props) => (
  <svg
    width={17}
    height={16}
    viewBox="0 0 17 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M15.75 13.5h-1m-14 0h1m7.5-7.667h-2a.5.5 0 0 0-.5.5V13.5m-5 0V3.667a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V13.5m-3 0h3m0 0h2m0 0h3m0 0h2m-2 0v-1m2 1h3m-3 0v-1m3 1v-1m-4.167-4.167h5M13.917 10l1.666-1.667m0 0-1.666-1.666"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default loan_out
