/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const log_in = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M4.776 13.134a.933.933 0 0 0 .933.933m0-11.2a.933.933 0 0 0-.933.933m6.457 3.967a.233.233 0 1 1-.233.23.232.232 0 0 1 .233-.232M3.633 6.6 5.5 8.466m0 0-1.867 1.867M5.5 8.466H1m8 6.53 5.6-.8a.466.466 0 0 0 .4-.463V2.85a.466.466 0 0 0-.369-.457l-5.6-1.382a.467.467 0 0 0-.564.457v13.067a.467.467 0 0 0 .532.461Z"
    />
  </svg>
)
export default log_in
