/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const loupe_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M17.5 17.5 23 23M18 9.5a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
    />
  </svg>
)

export default loupe_medium
