/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function megaphone(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M4.73333 10.4667H3.33333C2.06244 10.4667 1 9.40422 1 8.13333C1 6.86244 2.06244 5.8 3.33333 5.8H4.73333M4.73333 10.4667V5.8M4.73333 10.4667C7.8365 10.4669 9.95859 11.5724 12.5 13.2667V3C9.95859 4.69427 7.8365 5.79974 4.73333 5.8M4.73333 10.4667C4.73254 11.6886 5.24791 12.8912 6.13333 13.7333M15 7.2V9.06667"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default megaphone
