/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const mobilephone = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.636.25C3.871.25 3.25.87 3.25 1.636v12.728c0 .765.62 1.386 1.386 1.386h7c.766 0 1.387-.62 1.387-1.386V1.636c0-.765-.621-1.386-1.387-1.386h-7Zm.114 14V1.75h6.773v12.5H4.75ZM7.2 2.477a.75.75 0 1 0 0 1.5H9a.75.75 0 1 0 0-1.5H7.2ZM8.13 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
      fill="#000"
    />
  </svg>
)

export default mobilephone
