/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const motorcycle_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <g clipPath="url(#a)">
      <path
        d="M23.255 13.505c-.508-.508-1.043-.95-1.723-1.216a4.298 4.298 0 0 0-4.807 1.24l-2.026 2.431c-.282.338-.713.54-1.153.54h-1.607c-.433 0-.857-.195-1.139-.524-.434-.505-.857-1.051-1.3-1.585m10.75 4.359L17.878 7.125M13.875 2.25h1.783c.7 0 1.324.505 1.468 1.191l.752 3.684M3.75 18.75l5.75-4.36M7.176 7.9 2.25 8.25c-.817 0-1.5.683-1.5 1.5s.683 1.5 1.5 1.5c1.455 0 2.89-.075 4.248.551 1.21.558 2.141 1.551 3.002 2.59M7.176 7.899l2.885 2.912a1.5 1.5 0 0 0 1.06.439h1.629c.817 0 1.5-.683 1.5-1.5V7.395m-7.074.504 7.074-.504m0 0 3.628-.27M23.25 18.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-16.5 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm13.5-11.625C20.25 8.669 21.648 9 22.875 9V5.25c-1.227 0-2.625.331-2.625 1.875Z"
        stroke="#000"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </g>
    <defs>
      <clipPath id="a">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </svg>
)

export default motorcycle_medium
