/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const oil = (props) => (
  <svg
    width={16}
    height={17}
    viewBox="0 0 16 17"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M8.667 10.417h4.976m-4.976-3h4.471m.505 3a6.105 6.105 0 0 0-.504-3m.504 3c-.216 1.482-.578 2.214-1.587 3.374a5.5 5.5 0 0 1-9.39-3.889c0-1.3.415-2.565 1.183-3.612 0 0 3.958-5.54 4.32-5.54l4.315 5.54c.26.353.478.73.654 1.127"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default oil
