/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const paperclip = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="m15.176 6.723-7.014 7.014a4.313 4.313 0 1 1-6.099-6.1l5.76-5.76a2.875 2.875 0 1 1 4.066 4.066l-5.76 5.763a1.438 1.438 0 0 1-2.033-2.032l5.76-5.762"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default paperclip
