/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const pause = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M5.222 2h-1.11C3.496 2 3 2.488 3 3.09v9.82c0 .602.497 1.09 1.111 1.09h1.111c.614 0 1.111-.488 1.111-1.09V3.09c0-.602-.497-1.09-1.11-1.09ZM11.889 2h-1.111c-.614 0-1.111.488-1.111 1.09v9.82c0 .602.497 1.09 1.11 1.09h1.112c.614 0 1.111-.488 1.111-1.09V3.09C13 2.489 12.502 2 11.889 2Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default pause
