/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const pension_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#000"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M9.75 18a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0v-6M.911 16.805l3.683-13.38a2.625 2.625 0 0 1 5.156.7V9m4.5 9a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0Zm0 0v-6m8.839 4.802L19.406 3.425a2.625 2.625 0 0 0-5.156.7V9m-4.5 0v3m0-3h4.5m-4.5 3h4.5m0 0V9"
    />
  </svg>
)
export default pension_medium
