/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const phone = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M9.894 14.459c.687.4 1.433.61 2.233.522 1.075-.117 1.814-.742 2.542-1.47a1.16 1.16 0 0 0 0-1.623l-2.03-2.03a1.16 1.16 0 0 0-1.624 0 1.16 1.16 0 0 1-1.623 0L6.144 6.61a1.16 1.16 0 0 1 0-1.624 1.164 1.164 0 0 0 0-1.623l-2.03-2.032a1.16 1.16 0 0 0-1.624 0c-.727.728-1.352 1.467-1.47 2.542-.084.767.093 1.587.523 2.233a31.082 31.082 0 0 0 8.351 8.353Z"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default phone
