/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'
const pin_medium = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    viewBox="0 0 24 24"
    {...props}
  >
    <g clipPath="url(#pin_medium_svg__a)">
      <path
        stroke="#000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={1.5}
        d="m1 22.998 7.831-7.83m0 0-4.017-4.016c-.67-.668-.51-1.834.294-2.305a7.358 7.358 0 0 1 5.419-.792l4.065-6.388c.495-.78 1.631-.893 2.275-.25l5.716 5.716c.652.653.517 1.787-.25 2.276l-6.388 4.064a7.359 7.359 0 0 1-.792 5.42c-.471.803-1.637.963-2.305.293l-4.017-4.017Z"
      />
    </g>
    <defs>
      <clipPath id="pin_medium_svg__a">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </svg>
)
export default pin_medium
