/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const pin_code = (props) => (
  <svg
    width={16}
    height={17}
    viewBox="0 0 16 17"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.5 13.417a.667.667 0 1 1-1.333 0 .667.667 0 0 1 1.333 0Z"
      fill="#000"
    />
    <path
      d="M10.333 3.583V1.75a1 1 0 0 0-1-1h-7a1 1 0 0 0-1 1v12.667a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1v-3.334"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M5.25 7.208a1.125 1.125 0 1 1-2.25 0 1.125 1.125 0 0 1 2.25 0ZM8.75 7.208a1.125 1.125 0 1 1-2.25 0 1.125 1.125 0 0 1 2.25 0ZM12.25 7.208a1.125 1.125 0 1 1-2.25 0 1.125 1.125 0 0 1 2.25 0ZM15.75 7.208a1.125 1.125 0 1 1-2.25 0 1.125 1.125 0 0 1 2.25 0Z"
      fill="#000"
    />
  </svg>
)

export default pin_code
