/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function progress(props) {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M1 8C1 11.866 4.13401 15 8 15C11.866 15 15 11.866 15 8C15 4.13401 11.866 1 8 1M9.90909 5.13636L6.09091 10.8636"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
      />
      <path
        d="M7.25 6.25C7.25 6.80228 6.80228 7.25 6.25 7.25C5.69772 7.25 5.25 6.80228 5.25 6.25C5.25 5.69772 5.69772 5.25 6.25 5.25C6.80228 5.25 7.25 5.69772 7.25 6.25Z"
        fill="black"
      />
      <path
        d="M10.75 9.75C10.75 10.3023 10.3023 10.75 9.75 10.75C9.19772 10.75 8.75 10.3023 8.75 9.75C8.75 9.19772 9.19772 8.75 9.75 8.75C10.3023 8.75 10.75 9.19772 10.75 9.75Z"
        fill="black"
      />
    </svg>
  )
}

export default progress
