/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const return_1 = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="m3.8 14.133-2.8-2.8m0 0 2.8-2.8m-2.8 2.8h9.333a4.667 4.667 0 1 0 0-9.333H6.6"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default return_1
