/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const savings_account_out = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.73 14.585a.637.637 0 0 1-.594.415h-1.494a.64.64 0 0 1-.625-.524l-.108-.819a.64.64 0 0 0-.625-.524H8.19a.64.64 0 0 0-.625.525l-.073.818a.64.64 0 0 1-.625.524H5.425a.638.638 0 0 1-.607-.453l-.546-2.043a.638.638 0 0 0-.408-.42C3.073 11.823 1 10.813 1 9.623v-1.18c0-.774.592-1.414 1.359-1.514a.607.607 0 0 0 .381-.22l.349-.42a.658.658 0 0 0 .09-.692l-.32-.7a.653.653 0 0 1 .369-.889 2.807 2.807 0 0 1 2.208.135c.965-.512 2.29-.81 3.519-.81 1.649 0 3.107.55 4.178 1.437M8 1.933a.933.933 0 1 1 1.867 0M7.067 6h3.266m-.155 3.556h4.666M13.29 11.11l1.555-1.555m0 0L13.29 8"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default savings_account_out
