/** This file is auto generated by convertSvgToJsx.js */

import above_the_line from './above_the_line.js'
import account from './account.js'
import account_card from './account_card.js'
import account_in from './account_in.js'
import account_out from './account_out.js'
import account_percent from './account_percent.js'
import add_circled from './add_circled.js'
import ainvoice from './ainvoice.js'
import ambulance from './ambulance.js'
import animal_print from './animal_print.js'
import apple_watch from './apple_watch.js'
import attachment from './attachment.js'
import baby from './baby.js'
import bandage from './bandage.js'
import bank from './bank.js'
import bankid from './bankid.js'
import bankid_mobile from './bankid_mobile.js'
import bankid_qr from './bankid_qr.js'
import bicycle from './bicycle.js'
import boat from './boat.js'
import bowling from './bowling.js'
import brickwall from './brickwall.js'
import broken_chain from './broken_chain.js'
import brush from './brush.js'
import bsu from './bsu.js'
import bubble from './bubble.js'
import building_construction from './building_construction.js'
import camera from './camera.js'
import camper_trailer from './camper_trailer.js'
import car_1 from './car_1.js'
import car_2 from './car_2.js'
import caravan from './caravan.js'
import card from './card.js'
import card_in from './card_in.js'
import card_out from './card_out.js'
import card_with_padlock from './card_with_padlock.js'
import cat from './cat.js'
import chain from './chain.js'
import charger from './charger.js'
import chat from './chat.js'
import chatbot from './chatbot.js'
import chip from './chip.js'
import clock from './clock.js'
import cloud from './cloud.js'
import cloud_download from './cloud_download.js'
import cloud_rain from './cloud_rain.js'
import cloud_sync from './cloud_sync.js'
import cloud_transfer from './cloud_transfer.js'
import cloud_upload from './cloud_upload.js'
import cog from './cog.js'
import coins_1 from './coins_1.js'
import coins_2 from './coins_2.js'
import coins_3 from './coins_3.js'
import compose from './compose.js'
import confetti from './confetti.js'
import contacts from './contacts.js'
import cookie from './cookie.js'
import copy from './copy.js'
import currency from './currency.js'
import customer_service from './customer_service.js'
import diamond from './diamond.js'
import digipass from './digipass.js'
import digipost from './digipost.js'
import dismiss_keyboard from './dismiss_keyboard.js'
import dog from './dog.js'
import edit from './edit.js'
import einvoice from './einvoice.js'
import email from './email.js'
import equities_and_mutual_funds from './equities_and_mutual_funds.js'
import exclamation_circled from './exclamation_circled.js'
import exclamation_triangle from './exclamation_triangle.js'
import factory from './factory.js'
import file from './file.js'
import file_add from './file_add.js'
import file_contract from './file_contract.js'
import file_csv from './file_csv.js'
import file_loupe from './file_loupe.js'
import file_pdf from './file_pdf.js'
import file_ppt from './file_ppt.js'
import file_rejected from './file_rejected.js'
import file_signing from './file_signing.js'
import file_txt from './file_txt.js'
import file_warning from './file_warning.js'
import file_word from './file_word.js'
import file_xls from './file_xls.js'
import file_xml from './file_xml.js'
import filter from './filter.js'
import first_aid from './first_aid.js'
import flying_money from './flying_money.js'
import folder from './folder.js'
import fridge from './fridge.js'
import fullscreen from './fullscreen.js'
import funds from './funds.js'
import funds_in from './funds_in.js'
import funds_out from './funds_out.js'
import globe from './globe.js'
import grabber from './grabber.js'
import graph_decrease from './graph_decrease.js'
import graph_increase from './graph_increase.js'
import hamburger from './hamburger.js'
import hand_money from './hand_money.js'
import hanger from './hanger.js'
import heart from './heart.js'
import heart_rate from './heart_rate.js'
import hide from './hide.js'
import history from './history.js'
import home from './home.js'
import horse from './horse.js'
import hourglass from './hourglass.js'
import house_1 from './house_1.js'
import house_2 from './house_2.js'
import house_value from './house_value.js'
import information_bubble from './information_bubble.js'
import information_circled from './information_circled.js'
import insurance from './insurance.js'
import kid_number from './kid_number.js'
import language from './language.js'
import launch from './launch.js'
import leaf from './leaf.js'
import lightbulb from './lightbulb.js'
import list from './list.js'
import loan from './loan.js'
import loan_in from './loan_in.js'
import loan_out from './loan_out.js'
import location from './location.js'
import log_in from './log_in.js'
import log_out from './log_out.js'
import mastercard from './mastercard.js'
import mastercard_card from './mastercard_card.js'
import megaphone from './megaphone.js'
import microphone from './microphone.js'
import minimize from './minimize.js'
import mobilephone from './mobilephone.js'
import more_vertical from './more_vertical.js'
import motorcycle from './motorcycle.js'
import move from './move.js'
import office_buildings from './office_buildings.js'
import oil from './oil.js'
import owl from './owl.js'
import padlock from './padlock.js'
import paperclip from './paperclip.js'
import paragraph from './paragraph.js'
import pause from './pause.js'
import pay_from from './pay_from.js'
import pension from './pension.js'
import people_1 from './people_1.js'
import people_2 from './people_2.js'
import person from './person.js'
import person_shield from './person_shield.js'
import phone from './phone.js'
import photo from './photo.js'
import pin from './pin.js'
import pin_code from './pin_code.js'
import plant from './plant.js'
import play from './play.js'
import printer from './printer.js'
import profile from './profile.js'
import progress from './progress.js'
import question_circled from './question_circled.js'
import recurring from './recurring.js'
import redo from './redo.js'
import ref_number from './ref_number.js'
import refresh from './refresh.js'
import reply from './reply.js'
import restaurant from './restaurant.js'
import return_1 from './return_1.js'
import savings_account from './savings_account.js'
import savings_account_in from './savings_account_in.js'
import savings_account_out from './savings_account_out.js'
import scissors from './scissors.js'
import scooter from './scooter.js'
import send from './send.js'
import share_android from './share_android.js'
import share_ios from './share_ios.js'
import shield from './shield.js'
import shopping_cart from './shopping_cart.js'
import snowmobile from './snowmobile.js'
import split from './split.js'
import star from './star.js'
import stocks from './stocks.js'
import stop from './stop.js'
import stopwatch from './stopwatch.js'
import subtract_circled from './subtract_circled.js'
import support from './support.js'
import swap from './swap.js'
import thumbs_down from './thumbs_down.js'
import thumbs_up from './thumbs_up.js'
import tractor from './tractor.js'
import trailer from './trailer.js'
import train from './train.js'
import transfer from './transfer.js'
import transfer_to from './transfer_to.js'
import trash from './trash.js'
import undo from './undo.js'
import upload from './upload.js'
import video from './video.js'
import view from './view.js'
import vintage_car from './vintage_car.js'
import volume_off from './volume_off.js'
import volume_on from './volume_on.js'
import wallet from './wallet.js'
import wearables from './wearables.js'
import web from './web.js'
import wheelchair from './wheelchair.js'
import widget_android from './widget_android.js'
import widget_ios from './widget_ios.js'

export {
  above_the_line,
  account,
  account_card,
  account_in,
  account_out,
  account_percent,
  add_circled,
  ainvoice,
  ambulance,
  animal_print,
  apple_watch,
  attachment,
  baby,
  bandage,
  bank,
  bankid,
  bankid_mobile,
  bankid_qr,
  bicycle,
  boat,
  bowling,
  brickwall,
  broken_chain,
  brush,
  bsu,
  bubble,
  building_construction,
  camera,
  camper_trailer,
  car_1,
  car_2,
  caravan,
  card,
  card_in,
  card_out,
  card_with_padlock,
  cat,
  chain,
  charger,
  chat,
  chatbot,
  chip,
  clock,
  cloud,
  cloud_download,
  cloud_rain,
  cloud_sync,
  cloud_transfer,
  cloud_upload,
  cog,
  coins_1,
  coins_2,
  coins_3,
  compose,
  confetti,
  contacts,
  cookie,
  copy,
  currency,
  customer_service,
  diamond,
  digipass,
  digipost,
  dismiss_keyboard,
  dog,
  edit,
  einvoice,
  email,
  equities_and_mutual_funds,
  exclamation_circled,
  exclamation_triangle,
  factory,
  file,
  file_add,
  file_contract,
  file_csv,
  file_loupe,
  file_pdf,
  file_ppt,
  file_rejected,
  file_signing,
  file_txt,
  file_warning,
  file_word,
  file_xls,
  file_xml,
  filter,
  first_aid,
  flying_money,
  folder,
  fridge,
  fullscreen,
  funds,
  funds_in,
  funds_out,
  globe,
  grabber,
  graph_decrease,
  graph_increase,
  hamburger,
  hand_money,
  hanger,
  heart,
  heart_rate,
  hide,
  history,
  home,
  horse,
  hourglass,
  house_1,
  house_2,
  house_value,
  information_bubble,
  information_circled,
  insurance,
  kid_number,
  language,
  launch,
  leaf,
  lightbulb,
  list,
  loan,
  loan_in,
  loan_out,
  location,
  log_in,
  log_out,
  mastercard,
  mastercard_card,
  megaphone,
  microphone,
  minimize,
  mobilephone,
  more_vertical,
  motorcycle,
  move,
  office_buildings,
  oil,
  owl,
  padlock,
  paperclip,
  paragraph,
  pause,
  pay_from,
  pension,
  people_1,
  people_2,
  person,
  person_shield,
  phone,
  photo,
  pin,
  pin_code,
  plant,
  play,
  printer,
  profile,
  progress,
  question_circled,
  recurring,
  redo,
  ref_number,
  refresh,
  reply,
  restaurant,
  return_1,
  savings_account,
  savings_account_in,
  savings_account_out,
  scissors,
  scooter,
  send,
  share_android,
  share_ios,
  shield,
  shopping_cart,
  snowmobile,
  split,
  star,
  stocks,
  stop,
  stopwatch,
  subtract_circled,
  support,
  swap,
  thumbs_down,
  thumbs_up,
  tractor,
  trailer,
  train,
  transfer,
  transfer_to,
  trash,
  undo,
  upload,
  video,
  view,
  vintage_car,
  volume_off,
  volume_on,
  wallet,
  wearables,
  web,
  wheelchair,
  widget_android,
  widget_ios,
}
