/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

function share_android_medium(props) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M8.746 9.891L15.254 7.36M8.605 12.928L15.395 16.323M9 11.25C9 13.3211 7.32107 15 5.25 15C3.17893 15 1.5 13.3211 1.5 11.25C1.5 9.17893 3.17893 7.5 5.25 7.5C7.32107 7.5 9 9.17893 9 11.25ZM22.5 6C22.5 8.07107 20.8211 9.75 18.75 9.75C16.6789 9.75 15 8.07107 15 6C15 3.92893 16.6789 2.25 18.75 2.25C20.8211 2.25 22.5 3.92893 22.5 6ZM22.5 18C22.5 20.0711 20.8211 21.75 18.75 21.75C16.6789 21.75 15 20.0711 15 18C15 15.9289 16.6789 14.25 18.75 14.25C20.8211 14.25 22.5 15.9289 22.5 18Z"
        stroke="black"
        strokeWidth={1.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default share_android_medium
