/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const snowmobile = (props) => (
  <svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.198 8.006h2.588m.214 3.32c0 1.208-1.095 1.424-2.023 1.424m-2.646 0h2.646m-4.98-9.495c.6 0 1.359-.102 1.634.597l.607 1.593m4.548 2.561a6.96 6.96 0 0 0-2.664-3.642c-.868-.58-1.45.491-1.884 1.08m4.548 2.562c.223.713.383 1.896-.72 1.898h-1.868m-1.96-4.46c-.336.456-.666 1.14-1.308 1.14H6.515c-.988 0-1.214-1.424-2.174-1.424H2.054C1.203 5.156.706 6.182 1.19 6.864c.954.943 1.929 1.86 2.868 2.818m0 0 1.822-.695c.91-.347 1.923.096 2.362.917m-4.184-.222-2.35.897c-1.074.412-.82 2.17.388 2.171H6.55c1.397.001 2.351-1.612 1.692-2.846m0 0h3.956m0 0 .779 2.846"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default snowmobile
