/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const subtract_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M21 12.75a.75.75 0 0 0 0-1.5v1.5Zm-18-1.5a.75.75 0 0 0 0 1.5v-1.5Zm18 0H3v1.5h18v-1.5Z"
      fill="#000"
    />
  </svg>
)

export default subtract_medium
