/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const swap_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="m16.5 6.75 3-3m0 0 3 3m-3-3V15.5a3.75 3.75 0 1 1-7.5 0v-8a3.75 3.75 0 1 0-7.5 0v11.75m3-3-3 3m0 0-3-3"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default swap_medium
