/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const vintage_car_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M20.25 15v-3.75m0 3.75a3 3 0 1 1 0 6c-2.28 0-3.717-2.567-2.599-4.5M20.25 15c-1.11 0-2.08.603-2.599 1.5m2.599-5.25V7.5m0 3.75c0-.817-.683-1.5-1.5-1.5h-4.5m0 0V3m0 6.75h-6m6-6.75 2.25.75M14.25 3h-6m0 6.75V3m0 6.75h-6m8.25 3H9M8.25 3h-4.5c-.817 0-1.5.683-1.5 1.5v5.25m15.401 6.75H6.35m0 0c-.82-1.416-2.691-1.913-4.099-1.099M6.349 16.5C7.467 18.433 6.03 21 3.75 21a3 3 0 0 1-1.5-5.599m0 0V9.75"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default vintage_car_medium
