/** This file is auto generated by convertSvgToJsx.js */

import React from 'react'

const volume_off_medium = (props) => (
  <svg
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="m10.816 16.735 3.284 2.09c.446.334 1.072.39 1.57.142.5-.25.83-.785.83-1.342v-5.25m-.83-8.092a1.525 1.525 0 0 0-1.57.142l-6.6 4.2h-3c-.817 0-1.5.683-1.5 1.5v3c0 .817.683 1.5 1.5 1.5M3 19.875l18-15"
      stroke="#000"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)

export default volume_off_medium
