#!/bin/sh

# Export local environment variables
if [[ -f ".env.local" ]]; then
  . ".env.local"
fi

# Run Husky
. "$(dirname "$0")/_/husky.sh"

# Run precommit
if [ "$OMIT_LINT_STAGED" != "1" ]; then
  if command -v yarn >/dev/null 2>&1; then
    yarn precommit
  fi
fi
