## This is the first step

name: actions-verify # Name is used in workflows: ['actions-verify']

on:
  push:
    branches:
      - main
      - release
      - beta
      - alpha
      - chore/*
      - rc/*
      - fix/*
      - feat/*
      - feature/*
      - eufemia-icons
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  actions:
    name: Run Integration Tests

    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
          # - windows-latest

    runs-on: ${{ matrix.platform }}

    env:
      GH_EMAIL: ${{ secrets.GH_EMAIL }}
      GH_NAME: ${{ secrets.GH_NAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Audit dependencies
        run: yarn workspace @dnb/eufemia audit:ci

      - name: Run lint
        run: yarn workspace @dnb/eufemia lint:ci && yarn workspace dnb-design-system-portal lint:ci

      - name: Run tests
        run: yarn workspace @dnb/eufemia test:ci && yarn workspace dnb-design-system-portal test:ci

      - name: Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#eufemia-dev'
          status: ${{ job.status }}
          fields: commit,repo,ref,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: failure()
