name: Build Check

on:
  push:
    branches:
      - '**'
      - '!**--skip-ci'
      - '!**--visual-reports'
      - '!wip/**'
      - '!experiments/**'
  pull_request:
    branches:
      - 'main'
    types: [opened]

jobs:
  action:
    name: Build Check

    runs-on: ubuntu-latest

    env:
      GH_EMAIL: ${{ secrets.GH_EMAIL }}
      GH_NAME: ${{ secrets.GH_NAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      FIGMA_ICONS_FILE: ${{ secrets.FIGMA_ICONS_FILE }}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Use node_modules cache
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ secrets.CACHE_VERSION }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ secrets.CACHE_VERSION }}-${{ runner.os }}-modules-

      - name: Install dependencies
        if: steps.modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Verify isCI
        run: yarn workspace repo-utils test-is-ci

      - name: Prebuild Library
        run: yarn workspace @dnb/eufemia prebuild:ci

      - name: Postbuild Library
        run: yarn workspace @dnb/eufemia postbuild:ci

      - name: Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#eufemia-dev'
          status: ${{ job.status }}
          fields: author,ref,workflow,job,took
          job_name: Build Check
          github_base_url: https://github.com/
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: ${{ always() && !github.event.pull_request.head.repo.fork }}
        continue-on-error: true
