name: Dev Preview

on:
  push:
    branches:
      - '**'
      - '!**--skip-ci'
      - '!**--visual-reports'
      - '!wip/**'
      - '!experiments/**'
  pull_request:
    branches:
      - 'portal'
      - 'release'
      - 'beta'
      - 'alpha'
      - 'next'
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GH_EMAIL: ${{ secrets.GH_EMAIL }}
  GH_NAME: ${{ secrets.GH_NAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  FIGMA_ICONS_FILE: ${{ secrets.FIGMA_ICONS_FILE }}

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}

      - name: Build
        run: yarn workspace @dnb/eufemia build:ci

      - name: Publish to StackBlitz
        run: yarn workspace eufemia-starter remove-src && yarn dlx pkg-pr-new publish './packages/dnb-eufemia/build' --template './packages/eufemia-starter' --packageManager=yarn
